# Generated by Django 5.0.1 on 2025-01-30 14:56

import colorfield.fields
import django.db.models.deletion
import parler.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dipendenti', '0077_historicaldipendente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, verbose_name='Data di creazione')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data di ultima modifica')),
                ('colore', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Colore')),
                ('fa_icon', models.CharField(default='fa-solid fa-circle', max_length=60, verbose_name='Classe icona FontAwesome')),
                ('fa_visible', models.BooleanField(default=True, verbose_name='Icona Visibile')),
            ],
            options={
                'verbose_name': 'Edificio',
                'verbose_name_plural': 'Edifici',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, verbose_name='Data di creazione')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data di ultima modifica')),
                ('nome_breve', models.CharField(max_length=30, verbose_name='Nome Breve')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marche',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, verbose_name='Data di creazione')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data di ultima modifica')),
                ('colore', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Colore')),
                ('fa_icon', models.CharField(default='fa-solid fa-circle', max_length=60, verbose_name='Classe icona FontAwesome')),
                ('fa_visible', models.BooleanField(default=True, verbose_name='Icona Visibile')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Tipologia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, verbose_name='Data di creazione')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data di ultima modifica')),
                ('nome_breve', models.CharField(max_length=30, verbose_name='Nome Breve')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
            ],
            options={
                'verbose_name': 'Tipo di oggetto',
                'verbose_name_plural': 'Tipi di oggetto',
            },
        ),
        migrations.CreateModel(
            name='EdificioTanslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('nome_breve', models.CharField(max_length=30, verbose_name='Nome Breve')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='inventario.edificio')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Oggetto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, verbose_name='Data di creazione')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data di ultima modifica')),
                ('nome_breve', models.CharField(max_length=30, verbose_name='Nome Breve')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.marca', verbose_name='Marca')),
                ('tipologia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.tipologia', verbose_name='Tipo di oggetto')),
            ],
            options={
                'verbose_name': 'Oggetto',
                'verbose_name_plural': 'Oggetti',
            },
        ),
        migrations.CreateModel(
            name='Stanza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, verbose_name='Data di creazione')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data di ultima modifica')),
                ('colore', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Colore')),
                ('fa_icon', models.CharField(default='fa-solid fa-circle', max_length=60, verbose_name='Classe icona FontAwesome')),
                ('fa_visible', models.BooleanField(default=True, verbose_name='Icona Visibile')),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.edificio', verbose_name='Edificio')),
            ],
            options={
                'verbose_name': 'Stanza',
                'verbose_name_plural': 'Stanze',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StanzaTanslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('nome_breve', models.CharField(max_length=30, verbose_name='Nome Breve')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='inventario.stanza')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, verbose_name='Data di creazione')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data di ultima modifica')),
                ('seriale', models.CharField(max_length=30, verbose_name='Numero Seriale')),
                ('remark1', models.CharField(blank=True, max_length=30, null=True, verbose_name='Remark 1')),
                ('remark2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Remark 2')),
                ('remark3', models.CharField(blank=True, max_length=30, null=True, verbose_name='Remark 3')),
                ('dipendente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dipendenti.dipendente', verbose_name='Dipendente consegnatario')),
                ('oggetto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.oggetto', verbose_name='Oggetto')),
                ('stanza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.stanza', verbose_name='Stanza')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Records',
            },
        ),
        migrations.CreateModel(
            name='HistoricalRecord',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True, verbose_name='Codice Identificativo')),
                ('data_creazione', models.DateTimeField(blank=True, editable=False, verbose_name='Data di creazione')),
                ('data_modifica', models.DateTimeField(blank=True, editable=False, verbose_name='Data di ultima modifica')),
                ('seriale', models.CharField(max_length=30, verbose_name='Numero Seriale')),
                ('remark1', models.CharField(blank=True, max_length=30, null=True, verbose_name='Remark 1')),
                ('remark2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Remark 2')),
                ('remark3', models.CharField(blank=True, max_length=30, null=True, verbose_name='Remark 3')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('dipendente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dipendenti.dipendente', verbose_name='Dipendente consegnatario')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('oggetto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventario.oggetto', verbose_name='Oggetto')),
                ('stanza', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventario.stanza', verbose_name='Stanza')),
                ('status', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventario.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'historical Record',
                'verbose_name_plural': 'historical Records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
