# Generated by Django 5.0.1 on 2025-01-30 16:09

import django.db.models.deletion
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0077_historicaldipendente'),
        ('inventario', '0002_historicalrecord_note_record_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='dipendente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dipendenti.dipendente', verbose_name='Dipendente consegnatario'),
        ),
        migrations.CreateModel(
            name='StatusTanslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('nome_breve', models.CharField(max_length=30, verbose_name='Nome Breve')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='inventario.status')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
