# Generated by Django 5.0.1 on 2025-01-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_record_dipendente_statustanslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='stanza',
            name='sigla',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Sigla'),
        ),
        migrations.AddField(
            model_name='status',
            name='sigla',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Sigla'),
        ),
    ]
