# Generated by Django 5.0.1 on 2025-01-31 08:14

import django.db.models.deletion
import inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_stanza_sigla_status_sigla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrecord',
            name='stanza',
            field=models.ForeignKey(blank=True, db_constraint=False, default=inventario.models.Default.stanza, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventario.stanza', verbose_name='Stanza'),
        ),
        migrations.AlterField(
            model_name='historicalrecord',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, default=inventario.models.Default.status, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventario.status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='record',
            name='stanza',
            field=models.ForeignKey(default=inventario.models.Default.stanza, on_delete=django.db.models.deletion.PROTECT, to='inventario.stanza', verbose_name='Stanza'),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.ForeignKey(default=inventario.models.Default.status, on_delete=django.db.models.deletion.PROTECT, to='inventario.status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='stanza',
            name='edificio',
            field=models.ForeignKey(default=inventario.models.Default.edificio, on_delete=django.db.models.deletion.PROTECT, to='inventario.edificio', verbose_name='Edificio'),
        ),
    ]
