# Generated by Django 5.0.1 on 2025-01-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_historicalrecord_stanza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificio',
            name='sigla',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Sigla'),
        ),
    ]
