# Generated by Django 5.0.1 on 2025-02-03 08:54

import colorfield.fields
import django.db.models.deletion
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_edificio_creato_da_historicalrecord_creato_da_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipologia',
            name='descrizione',
        ),
        migrations.RemoveField(
            model_name='tipologia',
            name='nome_breve',
        ),
        migrations.AddField(
            model_name='tipologia',
            name='colore',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Colore'),
        ),
        migrations.AddField(
            model_name='tipologia',
            name='fa_icon',
            field=models.CharField(default='fa-solid fa-circle', max_length=60, verbose_name='Classe icona FontAwesome'),
        ),
        migrations.AddField(
            model_name='tipologia',
            name='fa_visible',
            field=models.BooleanField(default=True, verbose_name='Icona Visibile'),
        ),
        migrations.AlterField(
            model_name='edificiotanslation',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='inventario.edificio'),
        ),
        migrations.AlterField(
            model_name='stanzatanslation',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='inventario.stanza'),
        ),
        migrations.AlterField(
            model_name='statustanslation',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='inventario.status'),
        ),
        migrations.CreateModel(
            name='TipologiaTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('nome_breve', models.CharField(max_length=30, verbose_name='Nome Breve')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='inventario.tipologia')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
