# Generated by Django 5.0.1 on 2025-02-03 10:41

import colorfield.fields
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import parler.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_remove_tipologia_descrizione_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oggetto',
            name='tipologia',
        ),
        migrations.RemoveField(
            model_name='tipologiatranslation',
            name='master',
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, verbose_name='Data di creazione')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data di ultima modifica')),
                ('colore', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Colore')),
                ('fa_icon', models.CharField(default='fa-solid fa-circle', max_length=60, verbose_name='Classe icona FontAwesome')),
                ('fa_visible', models.BooleanField(default=True, verbose_name='Icona Visibile')),
                ('sigla', models.CharField(blank=True, max_length=3, null=True, verbose_name='Sigla')),
                ('creato_da', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modificato_da', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo di oggetto',
                'verbose_name_plural': 'Tipi di oggetto',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='oggetto',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.tipo', verbose_name='Tipo di oggetto'),
        ),
        migrations.CreateModel(
            name='TipoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('nome_breve', models.CharField(max_length=30, verbose_name='Nome Breve')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='inventario.tipo')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='Tipologia',
        ),
        migrations.DeleteModel(
            name='TipologiaTranslation',
        ),
    ]
