# Generated by Django 5.0.1 on 2025-02-04 10:20

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_remove_oggetto_tipologia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrecord',
            name='data_acquisto',
            field=models.DateField(blank=True, null=True, verbose_name='Data di Acquisto'),
        ),
        migrations.AddField(
            model_name='historicalrecord',
            name='data_fine_garanzia',
            field=models.DateField(blank=True, null=True, verbose_name='Data di Fine Garanzia'),
        ),
        migrations.AddField(
            model_name='record',
            name='data_acquisto',
            field=models.DateField(blank=True, null=True, verbose_name='Data di Acquisto'),
        ),
        migrations.AddField(
            model_name='record',
            name='data_fine_garanzia',
            field=models.DateField(blank=True, null=True, verbose_name='Data di Fine Garanzia'),
        ),
        migrations.CreateModel(
            name='Fornitore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, verbose_name='Data di creazione')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data di ultima modifica')),
                ('nome_breve', models.CharField(max_length=30, verbose_name='Nome Breve')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numero di telefono')),
                ('cel', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numero di cellulare')),
                ('contatto', models.CharField(blank=True, max_length=120, null=True, verbose_name='Persona di contatto')),
                ('creato_da', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modificato_da', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fornitore',
                'verbose_name_plural': 'Fornitori',
            },
        ),
        migrations.AddField(
            model_name='historicalrecord',
            name='fornitore',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventario.fornitore', verbose_name='Fornitore'),
        ),
        migrations.AddField(
            model_name='record',
            name='fornitore',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventario.fornitore', verbose_name='Fornitore'),
            preserve_default=False,
        ),
    ]
