# Generated by Django 5.0.1 on 2025-02-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_historicalrecord_data_acquisto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrecord',
            name='remark1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Remark 1 (MAC Address)'),
        ),
        migrations.AlterField(
            model_name='record',
            name='remark1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Remark 1 (MAC Address)'),
        ),
    ]
