# Generated by Django 4.0.4 on 2023-03-03 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dipendenti', '0013_dipendente_attivo_alter_dipendente_qualifica_data_da_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='counter',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='ID del contatore')),
                ('valore', models.IntegerField(verbose_name='valore del contatore')),
            ],
        ),
        migrations.CreateModel(
            name='GruppoSupporto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome del gruppo')),
                ('membri', models.ManyToManyField(blank=True, null=True, to='dipendenti.dipendente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tipologia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome della tipologia')),
                ('sigla', models.CharField(max_length=2, verbose_name='Sigla della tipologia(2 caratteri)')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
                ('gruppo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.grupposupporto', verbose_name='Gruppo incaricato')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=12, verbose_name='ID ticket')),
                ('testo', models.TextField(verbose_name='Descrizione del problema')),
                ('data_apertura', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('data_chiusura', models.DateTimeField(blank=True, null=True)),
                ('soluzione', models.TextField(blank=True, null=True, verbose_name='Descrizione del problema')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipendenti.dipendente', verbose_name='persona richiedente')),
                ('tipologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.tipologia', verbose_name='Tipologia di problema')),
                ('utente_apertura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_aperti', to='dipendenti.dipendente', verbose_name='utente di apertura ticket')),
                ('utente_chiusura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_chiusi', to='dipendenti.dipendente', verbose_name='utente chiusura ticket')),
                ('utente_modifica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_modificati', to='dipendenti.dipendente', verbose_name='utente ultima modifica')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Allegato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=120, verbose_name="Descrizione dell'allegato")),
                ('file', models.FileField(upload_to='allegati/%Y', verbose_name='File Allegato')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.ticket', verbose_name='Ticket di riferimento')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
