# Generated by Django 4.0.4 on 2023-03-06 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allegato',
            options={'verbose_name': 'Allegato', 'verbose_name_plural': 'Allegati'},
        ),
        migrations.AlterModelOptions(
            name='counter',
            options={'verbose_name': 'Contatore', 'verbose_name_plural': 'Contatori'},
        ),
        migrations.AlterModelOptions(
            name='grupposupporto',
            options={'verbose_name': 'Gruppo di supporto', 'verbose_name_plural': 'Gruppi di supporto'},
        ),
        migrations.AlterModelOptions(
            name='tipologia',
            options={'verbose_name': 'Tipologia di supporto', 'verbose_name_plural': 'Tipologie di supporti'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='nome',
            field=models.CharField(max_length=12, unique=True, verbose_name='ID ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='utente_apertura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_aperti', to=settings.AUTH_USER_MODEL, verbose_name='utente di apertura ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='utente_chiusura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_chiusi', to=settings.AUTH_USER_MODEL, verbose_name='utente chiusura ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='utente_modifica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_modificati', to=settings.AUTH_USER_MODEL, verbose_name='utente ultima modifica'),
        ),
        migrations.AlterField(
            model_name='tipologia',
            name='sigla',
            field=models.CharField(max_length=2, verbose_name='Sigla della tipologia (2 caratteri)'),
        ),
    ]
