# Generated by Django 4.0.4 on 2023-03-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_alter_allegato_options_alter_counter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note Interne'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='soluzione',
            field=models.TextField(blank=True, null=True, verbose_name='Soluzione'),
        ),
    ]
