# Generated by Django 4.0.4 on 2023-03-06 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0003_ticket_note_alter_ticket_soluzione'),
    ]

    operations = [
        migrations.CreateModel(
            name='Azione',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_azione', models.DateTimeField(auto_now=True)),
                ('nota', models.TextField(verbose_name='Descrizione azione')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.ticket', verbose_name='Ticket')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utente agente')),
            ],
            options={
                'verbose_name': 'Azione',
                'verbose_name_plural': 'Azioni',
            },
        ),
    ]
