# Generated by Django 4.0.4 on 2023-03-06 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0004_azione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azione',
            name='utente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='azioni_rel', to=settings.AUTH_USER_MODEL, verbose_name='Utente agente'),
        ),
    ]
