# Generated by Django 4.0.4 on 2023-03-07 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0005_alter_azione_utente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='chiuso',
            field=models.BooleanField(default=False, verbose_name='Ticket chiuso'),
        ),
        migrations.AlterField(
            model_name='azione',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='azioni_rel', to='helpdesk.ticket', verbose_name='Ticket'),
        ),
        migrations.AlterField(
            model_name='azione',
            name='utente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utente agente'),
        ),
    ]
