# Generated by Django 4.0.4 on 2023-03-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_ticket_chiuso_alter_azione_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='azione',
            name='interna',
            field=models.BooleanField(default=False, verbose_name='Annotazione interna'),
        ),
    ]
