# Generated by Django 4.0.4 on 2023-03-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0007_azione_interna'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupposupporto',
            name='email',
            field=models.TextField(default='Buon giorno, {nomecompleto}.\r\n\r\nÈ stata svolta una nuova attività sul tuo ticket {ticket}.\r\n\r\n\r\nAgente: {agente}\r\nAzione: {azione}\r\n\r\n\r\nper controllare i tuoi ticket: http://leifersdjango.leifers.gvcc.net/helpdesk/lista/', verbose_name='Testo e-mail'),
        ),
    ]
