# Generated by Django 4.0.4 on 2023-03-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0008_grupposupporto_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipologia',
            name='principale',
            field=models.BooleanField(default=False, verbose_name='Tipologia primaria'),
        ),
        migrations.AlterField(
            model_name='grupposupporto',
            name='email',
            field=models.TextField(default='Buon giorno, {}.\r\n\r\nÈ stata svolta una nuova attività sul tuo ticket {}.\r\n\r\nAgente: {}\r\nAzione: {}\r\n\r\n\r\nper controllare i tuoi ticket: http://leifersdjango.leifers.gvcc.net/helpdesk/lista/', verbose_name='Testo e-mail'),
        ),
    ]
