# Generated by Django 4.0.4 on 2023-03-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0009_tipologia_principale_alter_grupposupporto_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupposupporto',
            name='email',
        ),
        migrations.AddField(
            model_name='tipologia',
            name='email_apertura',
            field=models.TextField(default='Buon giorno, {}.\r\n\r\nÈ stato aperto un ticket di intervento a tuo nome da {} il {}.\r\nIl ticket verrà gestito quanto prima dal servizio informatica.\r\n\r\nper controllare i tuoi ticket: http://leifersdjango.leifers.gvcc.net/helpdesk/lista/', verbose_name='Testo e-mail apertura ticket'),
        ),
        migrations.AddField(
            model_name='tipologia',
            name='email_azione',
            field=models.TextField(default='Buon giorno, {}.\r\n\r\nÈ stata svolta una nuova attività sul tuo ticket {}.\r\n\r\nAgente: {}\r\nAzione: {}\r\n\r\n\r\nper controllare i tuoi ticket: http://leifersdjango.leifers.gvcc.net/helpdesk/lista/', verbose_name='Testo e-mail azione pubblica'),
        ),
        migrations.AddField(
            model_name='tipologia',
            name='email_chiusura',
            field=models.TextField(default='Buon giorno, {}.\r\n\r\nSiamo lieti di comunicare che il suo ticket di intervento tecnico è stato risolto.\r\n\r\nData della soluzione: {}\r\nAutore della soluzione: {}\r\nSoluzione:\r\n\r\n {} \r\n\r\nper controllare i tuoi ticket: http://leifersdjango.leifers.gvcc.net/helpdesk/lista/', verbose_name='Testo e-mail chiusura ticket'),
        ),
    ]
