# Generated by Django 4.0.4 on 2023-03-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0010_remove_grupposupporto_email_tipologia_email_apertura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipologia',
            name='email_apertura',
            field=models.TextField(default='Buon giorno, {persona}.\r\n\r\nÈ stato aperto il ticket di intervento {ticket} a tuo nome da {agente_apertura} il {data_apertura}.\r\nRichiesta: {testo_apertura}\r\n\r\nIl ticket verrà gestito quanto prima dal servizio informatica.\r\n\r\nper controllare i tuoi ticket: http://leifersdjango.leifers.gvcc.net/helpdesk/lista/', help_text="{persona} titolare del ticket ;\r\n{ticket} id del ticket;\r\n{agente_azione} incaricato che inoltra l'azione;\r\n{data_azione} data di inserimento dell'azione';\r\n{azione} testo dell'azione svolta;\r\n{agente_apertura} incaricato che apre il ticket;\r\n{data_apertura} data di apertura del ticket;\r\n{testo_apertura} testo del ticket inserito;\r\n{data_chiusura} data di chiusura del ticket;\r\n{agente_chiusura} incaricato che ha concluso il ticket;\r\n{soluzione} testo della risoluzione del ticket;\r\n", verbose_name='Testo e-mail apertura ticket'),
        ),
        migrations.AlterField(
            model_name='tipologia',
            name='email_azione',
            field=models.TextField(default='Buon giorno, {persona}.\r\n\r\nÈ stata svolta una nuova attività sul tuo ticket {ticket}.\r\n\r\nAgente: {agente_azione}\r\nAzione: {azione}\r\n\r\n\r\nper controllare i tuoi ticket: http://leifersdjango.leifers.gvcc.net/helpdesk/lista/', help_text="{persona} titolare del ticket ;\r\n{ticket} id del ticket;\r\n{agente_azione} incaricato che inoltra l'azione;\r\n{data_azione} data di inserimento dell'azione';\r\n{azione} testo dell'azione svolta;\r\n{agente_apertura} incaricato che apre il ticket;\r\n{data_apertura} data di apertura del ticket;\r\n{testo_apertura} testo del ticket inserito;\r\n{data_chiusura} data di chiusura del ticket;\r\n{agente_chiusura} incaricato che ha concluso il ticket;\r\n{soluzione} testo della risoluzione del ticket;\r\n", verbose_name='Testo e-mail azione pubblica'),
        ),
        migrations.AlterField(
            model_name='tipologia',
            name='email_chiusura',
            field=models.TextField(default='Buon giorno, {persona}.\r\n\r\nSiamo lieti di comunicare che il suo ticket di intervento tecnico {ticket} è stato risolto.\r\n\r\nData della soluzione: {data_chiusura}\r\nAutore della soluzione: {agente_chiusura}\r\nSoluzione:\r\n\r\n {soluzione} \r\n\r\nper controllare i tuoi ticket: http://leifersdjango.leifers.gvcc.net/helpdesk/lista/', help_text="{persona} titolare del ticket ;\r\n{ticket} id del ticket;\r\n{agente_azione} incaricato che inoltra l'azione;\r\n{data_azione} data di inserimento dell'azione';\r\n{azione} testo dell'azione svolta;\r\n{agente_apertura} incaricato che apre il ticket;\r\n{data_apertura} data di apertura del ticket;\r\n{testo_apertura} testo del ticket inserito;\r\n{data_chiusura} data di chiusura del ticket;\r\n{agente_chiusura} incaricato che ha concluso il ticket;\r\n{soluzione} testo della risoluzione del ticket;\r\n", verbose_name='Testo e-mail chiusura ticket'),
        ),
    ]
