# Generated by Django 4.0.4 on 2023-04-17 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0031_alter_dipendente_qualifica_data_da_and_more'),
        ('helpdesk', '0011_alter_tipologia_email_apertura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='incaricato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_in_carico', to='dipendenti.dipendente', verbose_name='Incaricato'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipendenti.dipendente', verbose_name='Persona richiedente'),
        ),
    ]
