# Generated by Django 4.0.4 on 2023-06-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0041_alter_dipendente_qualifica_data_da_and_more'),
        ('helpdesk', '0012_ticket_incaricato_alter_ticket_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupposupporto',
            name='membri',
            field=models.ManyToManyField(to='dipendenti.dipendente'),
        ),
    ]
