# Generated by Django 5.0.1 on 2025-01-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0013_alter_grupposupporto_membri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipologia',
            name='email_apertura',
            field=models.TextField(default='Buon giorno, {persona}.\r\n\r\nÈ stato aperto il ticket di intervento {ticket} a tuo nome da {agente_apertura} il {data_apertura}.\r\nRichiesta: {testo_apertura}\r\n\r\nIl ticket verrà gestito quanto prima dal servizio informatica.\r\n\r\nper controllare i tuoi ticket: {base_url}helpdesk/lista/', help_text="{persona} titolare del ticket <br />{ticket} id del ticket<br />{agente_azione} incaricato che inoltra l'azione<br />{data_azione} data di inserimento dell'azione'<br />{azione} testo dell'azione svolta<br />{agente_apertura} incaricato che apre il ticket<br />{data_apertura} data di apertura del ticket<br />{testo_apertura} testo del ticket inserito<br />{data_chiusura} data di chiusura del ticket<br />{agente_chiusura} incaricato che ha concluso il ticket<br />{soluzione} testo della risoluzione del ticket<br />{base_url} URL base del server", verbose_name='Testo e-mail apertura ticket'),
        ),
        migrations.AlterField(
            model_name='tipologia',
            name='email_azione',
            field=models.TextField(default='Buon giorno, {persona}.\r\n\r\nÈ stata svolta una nuova attività sul tuo ticket {ticket}.\r\n\r\nAgente: {agente_azione}\r\nAzione: {azione}\r\n\r\n\r\nper controllare i tuoi ticket: {base_url}helpdesk/lista/', help_text="{persona} titolare del ticket <br />{ticket} id del ticket<br />{agente_azione} incaricato che inoltra l'azione<br />{data_azione} data di inserimento dell'azione'<br />{azione} testo dell'azione svolta<br />{agente_apertura} incaricato che apre il ticket<br />{data_apertura} data di apertura del ticket<br />{testo_apertura} testo del ticket inserito<br />{data_chiusura} data di chiusura del ticket<br />{agente_chiusura} incaricato che ha concluso il ticket<br />{soluzione} testo della risoluzione del ticket<br />{base_url} URL base del server", verbose_name='Testo e-mail azione pubblica'),
        ),
        migrations.AlterField(
            model_name='tipologia',
            name='email_chiusura',
            field=models.TextField(default='Buon giorno, {persona}.\r\n\r\nSiamo lieti di comunicare che il suo ticket di intervento tecnico {ticket} è stato risolto.\r\n\r\nData della soluzione: {data_chiusura}\r\nAutore della soluzione: {agente_chiusura}\r\nSoluzione:\r\n\r\n {soluzione} \r\n\r\nper controllare i tuoi ticket: {base_url}helpdesk/lista/', help_text="{persona} titolare del ticket <br />{ticket} id del ticket<br />{agente_azione} incaricato che inoltra l'azione<br />{data_azione} data di inserimento dell'azione'<br />{azione} testo dell'azione svolta<br />{agente_apertura} incaricato che apre il ticket<br />{data_apertura} data di apertura del ticket<br />{testo_apertura} testo del ticket inserito<br />{data_chiusura} data di chiusura del ticket<br />{agente_chiusura} incaricato che ha concluso il ticket<br />{soluzione} testo della risoluzione del ticket<br />{base_url} URL base del server", verbose_name='Testo e-mail chiusura ticket'),
        ),
    ]
