# Generated by Django 4.0.4 on 2022-04-14 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dipendenti', '0005_rapportolavoro_dipendente_qualifica_determinato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('anno', models.IntegerField(verbose_name='Anno di riferimento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('descrizione_it', models.CharField(max_length=30, verbose_name='Giudizio in italiano')),
                ('descrizione_td', models.CharField(max_length=30, verbose_name='Giudizio in tedesco')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('anno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valutazioni.anno', verbose_name='Anno di riferimento')),
            ],
        ),
        migrations.CreateModel(
            name='TipoValutazione',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome del tipo di valutazione')),
                ('descrizione_it', models.TextField(blank=True, null=True, verbose_name='Descrizione estesa del tipo di valutazione in italiano')),
                ('descrizione_td', models.TextField(blank=True, null=True, verbose_name='Descrizione estesa del tipo di valutazione in tedesco')),
                ('sezione', models.CharField(max_length=1, verbose_name='Sezione di valutazione')),
                ('indice', models.IntegerField(verbose_name='Indice di ordinamento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('valore', models.IntegerField(verbose_name='Valore della votazione')),
                ('descrizione_it', models.CharField(max_length=30, verbose_name='Giudizio in italiano')),
                ('descrizione_td', models.CharField(max_length=30, verbose_name='Giudizio in tedesco')),
                ('desc_estesa_it', models.TextField(blank=True, null=True, verbose_name='Descrizione in italiano')),
                ('desc_estesa_td', models.TextField(blank=True, null=True, verbose_name='Descrizione in tedesco')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Formulario_Sociale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valutazioni.formulario')),
                ('sociale', models.ForeignKey(limit_choices_to=models.Q(('tipo_valutazione__sezione__iexact', 'c')), on_delete=django.db.models.deletion.CASCADE, to='valutazioni.elemento')),
                ('voto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='valutazioni.voto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Formulario_Prestazione',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valutazioni.formulario')),
                ('prestazione', models.ForeignKey(limit_choices_to=models.Q(('tipo_valutazione__sezione__iexact', 'b')), on_delete=django.db.models.deletion.CASCADE, to='valutazioni.elemento')),
                ('voto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='valutazioni.voto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Formulario_Obiettivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('descrizione', models.CharField(max_length=100, verbose_name="Descrizione dell'obiettivo")),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valutazioni.formulario')),
                ('obiettivo', models.ForeignKey(default=1, limit_choices_to=models.Q(('tipo_valutazione__sezione__iexact', 'a')), on_delete=django.db.models.deletion.CASCADE, to='valutazioni.elemento')),
                ('voto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='valutazioni.voto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Formulario_Coordinamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('coordinamento', models.ForeignKey(limit_choices_to=models.Q(('tipo_valutazione__sezione__iexact', 'd')), on_delete=django.db.models.deletion.CASCADE, to='valutazioni.elemento')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valutazioni.formulario')),
                ('voto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='valutazioni.voto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='formulario',
            name='coordinamenti',
            field=models.ManyToManyField(help_text='Tra il dipendente ed il diretto superiore devono essere fissati a priori 2 criteri di competenze direttive o di coordinamento da valutare.', related_name='coordinamenti', through='valutazioni.Formulario_Coordinamento', to='valutazioni.elemento'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='dipqual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipendenti.dipendente_qualifica', verbose_name='Dipendente valutato'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='obiettivi',
            field=models.ManyToManyField(help_text='Tra il dipendente ed il diretto superiore deve essere fissato almeno un obiettivo annuale.', related_name='obiettivi', through='valutazioni.Formulario_Obiettivo', to='valutazioni.elemento'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='prestazioni',
            field=models.ManyToManyField(help_text='Tra il dipendente ed il diretto superiore devono essere fissati a priori 7 criteri di prestazioni da valutare.', related_name='prestazioni', through='valutazioni.Formulario_Prestazione', to='valutazioni.elemento'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='sociali',
            field=models.ManyToManyField(help_text='Tra il dipendente ed il diretto superiore devono essere fissati a priori 3 criteri di competenze sociali da valutare.', related_name='sociali', through='valutazioni.Formulario_Sociale', to='valutazioni.elemento'),
        ),
        migrations.AddField(
            model_name='elemento',
            name='tipo_valutazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valutazioni.tipovalutazione', verbose_name='Sezione della valutazione'),
        ),
        migrations.AlterUniqueTogether(
            name='formulario',
            unique_together={('anno', 'dipqual')},
        ),
    ]
