# Generated by Django 4.0.4 on 2022-04-20 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valutazioni', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anno',
            options={'verbose_name': 'Anno', 'verbose_name_plural': 'Anni'},
        ),
        migrations.AlterModelOptions(
            name='tipovalutazione',
            options={'ordering': ['indice', 'nome'], 'verbose_name': 'Tipo di valutazione', 'verbose_name_plural': 'Tipi di valutazione'},
        ),
        migrations.AlterModelOptions(
            name='voto',
            options={'verbose_name': 'Voto', 'verbose_name_plural': 'Voti'},
        ),
        migrations.AlterField(
            model_name='formulario_coordinamento',
            name='voto',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='valutazioni.voto'),
        ),
        migrations.AlterField(
            model_name='formulario_obiettivo',
            name='voto',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='valutazioni.voto'),
        ),
        migrations.AlterField(
            model_name='formulario_prestazione',
            name='voto',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='valutazioni.voto'),
        ),
        migrations.AlterField(
            model_name='formulario_sociale',
            name='voto',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='valutazioni.voto'),
        ),
    ]
