# Generated by Django 4.0.4 on 2022-04-20 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valutazioni', '0002_alter_anno_options_alter_tipovalutazione_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elemento',
            options={'verbose_name': 'Elemento di valutazione', 'verbose_name_plural': 'Elementi di valutazione'},
        ),
    ]
