# Generated by Django 4.0.4 on 2022-04-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valutazioni', '0003_alter_elemento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulario',
            options={'verbose_name': 'Formulario di valutazione annuale', 'verbose_name_plural': 'Formulari di valutazione annuali'},
        ),
        migrations.AddField(
            model_name='tipovalutazione',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0.3, max_digits=5, verbose_name='Peso della valutazione per dipendenti'),
        ),
        migrations.AddField(
            model_name='tipovalutazione',
            name='peso_coord',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=5, verbose_name='Peso della valutazione per coordinatori e responsabili'),
        ),
    ]
