# Generated by Django 4.0.4 on 2022-04-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valutazioni', '0004_alter_formulario_options_tipovalutazione_peso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elemento',
            options={'ordering': ['indice'], 'verbose_name': 'Elemento di valutazione', 'verbose_name_plural': 'Elementi di valutazione'},
        ),
        migrations.AddField(
            model_name='elemento',
            name='indice',
            field=models.IntegerField(default=0, verbose_name='indice della voce'),
        ),
    ]
