# Generated by Django 4.0.4 on 2022-04-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valutazioni', '0005_alter_elemento_options_elemento_indice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='descrizione_it',
            field=models.CharField(max_length=100, verbose_name='Descrizione in italiano'),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='descrizione_td',
            field=models.CharField(max_length=100, verbose_name='Descrizione in tedesco'),
        ),
    ]
