# Generated by Django 4.0.4 on 2022-04-21 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valutazioni', '0006_alter_elemento_descrizione_it_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulario_coordinamento',
            options={'verbose_name': 'Criterio di Coordinamento', 'verbose_name_plural': 'SOLO COORDINATORI. Tra il dipendente ed il diretto superiore devono essere fissati a priori 2 criteri di competenze direttive o di coordinamento da valutare.'},
        ),
        migrations.AlterModelOptions(
            name='formulario_obiettivo',
            options={'verbose_name': 'Obiettivo annuale.', 'verbose_name_plural': 'Tra il dipendente ed il diretto superiore deve essere fissato almeno un obiettivo annuale.'},
        ),
        migrations.AlterModelOptions(
            name='formulario_prestazione',
            options={'verbose_name': 'Criterio di prestazione', 'verbose_name_plural': 'Tra il dipendente ed il diretto superiore devono essere fissati a priori 7 criteri di prestazioni da valutare.'},
        ),
        migrations.AlterModelOptions(
            name='formulario_sociale',
            options={'verbose_name': 'Criterio di competenza sociale', 'verbose_name_plural': 'Tra il dipendente ed il diretto superiore devono essere fissati a priori 3 criteri di competenze sociali da valutare.'},
        ),
        migrations.AlterField(
            model_name='formulario_coordinamento',
            name='coordinamento',
            field=models.ForeignKey(limit_choices_to=models.Q(('tipo_valutazione__sezione__iexact', 'd')), on_delete=django.db.models.deletion.CASCADE, to='valutazioni.elemento', verbose_name='Competenza di coordinamento'),
        ),
        migrations.AlterField(
            model_name='formulario_coordinamento',
            name='voto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='valutazioni.voto'),
        ),
        migrations.AlterField(
            model_name='formulario_obiettivo',
            name='voto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='valutazioni.voto'),
        ),
        migrations.AlterField(
            model_name='formulario_prestazione',
            name='voto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='valutazioni.voto'),
        ),
        migrations.AlterField(
            model_name='formulario_sociale',
            name='sociale',
            field=models.ForeignKey(limit_choices_to=models.Q(('tipo_valutazione__sezione__iexact', 'c')), on_delete=django.db.models.deletion.CASCADE, to='valutazioni.elemento', verbose_name='Competenza sociale'),
        ),
        migrations.AlterField(
            model_name='formulario_sociale',
            name='voto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='valutazioni.voto'),
        ),
    ]
