# Generated by Django 4.0.4 on 2022-04-22 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valutazioni', '0007_alter_formulario_coordinamento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='data_obiettivo',
            field=models.DateField(default=datetime.datetime(2022, 4, 22, 11, 34, 6, 680945), verbose_name='Data di DISCUSSIONE criteri ed obiettivi'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='data_valutazione',
            field=models.DateField(blank=True, null=True, verbose_name='Data di VALUTAZIONE criteri ed obiettivi'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note del dipendente'),
        ),
        migrations.AlterUniqueTogether(
            name='formulario_coordinamento',
            unique_together={('formulario', 'coordinamento')},
        ),
        migrations.AlterUniqueTogether(
            name='formulario_obiettivo',
            unique_together={('formulario', 'obiettivo', 'descrizione')},
        ),
        migrations.AlterUniqueTogether(
            name='formulario_prestazione',
            unique_together={('formulario', 'prestazione')},
        ),
        migrations.AlterUniqueTogether(
            name='formulario_sociale',
            unique_together={('formulario', 'sociale')},
        ),
    ]
