# Generated by Django 4.0.4 on 2022-04-27 11:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0010_logo_alter_dipendente_qualifica_options_and_more'),
        ('valutazioni', '0008_formulario_data_obiettivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='logo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dipendenti.logo', verbose_name='logo del modello'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='data_obiettivo',
            field=models.DateField(default=datetime.datetime(2022, 4, 27, 13, 29, 30, 262596), verbose_name='Data di DISCUSSIONE criteri ed obiettivi'),
        ),
    ]
