# Generated by Django 4.0.4 on 2022-05-02 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valutazioni', '0009_formulario_logo_alter_formulario_data_obiettivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario_obiettivo',
            name='risultato',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Risultato del conseguimento dell'obiettivo"),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='data_obiettivo',
            field=models.DateField(default=datetime.datetime(2022, 5, 2, 11, 42, 45, 801907), verbose_name='Data di DISCUSSIONE criteri ed obiettivi'),
        ),
    ]
