# Generated by Django 4.0.4 on 2022-05-02 10:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valutazioni', '0010_formulario_obiettivo_risultato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaElementi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('indice', models.IntegerField(default=0, verbose_name='indice della voce')),
                ('descrizione_it', models.CharField(max_length=100, verbose_name='Descrizione in italiano')),
                ('descrizione_td', models.CharField(max_length=100, verbose_name='Descrizione in tedesco')),
            ],
            options={
                'verbose_name': 'Categoria di elementi di valutazione',
                'verbose_name_plural': 'Categorie di elementi di valutazione',
            },
        ),
        migrations.AlterField(
            model_name='formulario',
            name='data_obiettivo',
            field=models.DateField(default=datetime.datetime(2022, 5, 2, 12, 1, 34, 380630), verbose_name='Data di DISCUSSIONE criteri ed obiettivi'),
        ),
        migrations.AddField(
            model_name='elemento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='valutazioni.categoriaelementi', verbose_name="Categoria dell'elemento"),
        ),
    ]
