# Generated by Django 4.0.4 on 2023-03-06 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valutazioni', '0011_categoriaelementi_alter_formulario_data_obiettivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='data_obiettivo',
            field=models.DateField(default=datetime.datetime(2023, 3, 6, 11, 59, 30, 598343), verbose_name='Data di DISCUSSIONE criteri ed obiettivi'),
        ),
    ]
