# Generated by Django 4.0.4 on 2023-03-06 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valutazioni', '0013_alter_formulario_data_obiettivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='data_obiettivo',
            field=models.DateField(default=datetime.datetime(2023, 3, 6, 12, 50, 17, 561627), verbose_name='Data di DISCUSSIONE criteri ed obiettivi'),
        ),
    ]
