# Generated by Django 4.0.4 on 2023-03-06 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valutazioni', '0014_alter_formulario_data_obiettivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='data_obiettivo',
            field=models.DateField(default=datetime.datetime(2023, 3, 6, 16, 2, 40, 372852), verbose_name='Data di DISCUSSIONE criteri ed obiettivi'),
        ),
    ]
