# Generated by Django 4.0.4 on 2023-03-13 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valutazioni', '0017_alter_formulario_data_obiettivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='data_obiettivo',
            field=models.DateField(default=datetime.datetime(2023, 3, 13, 10, 28, 53, 10986), verbose_name='Data di DISCUSSIONE criteri ed obiettivi'),
        ),
    ]
