# Generated by Django 4.0.4 on 2023-03-20 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valutazioni', '0023_alter_formulario_data_obiettivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='data_obiettivo',
            field=models.DateField(default=datetime.datetime(2023, 3, 20, 12, 33, 38, 583090), verbose_name='Data di DISCUSSIONE criteri ed obiettivi'),
        ),
    ]
