# Generated by Django 4.0.4 on 2023-03-21 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valutazioni', '0025_alter_formulario_data_obiettivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='data_obiettivo',
            field=models.DateField(default=datetime.datetime(2023, 3, 21, 11, 30, 59, 597942), verbose_name='Data di DISCUSSIONE criteri ed obiettivi'),
        ),
    ]
