# Generated by Django 4.0.4 on 2023-04-06 10:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0029_alter_dipendente_qualifica_data_da_and_more'),
        ('valutazioni', '0026_alter_formulario_data_obiettivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_firma', models.DateTimeField(auto_now=True, verbose_name='Data di firma')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note del dipendente')),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipendenti.dipendente', verbose_name='Utente firmatario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='formulario',
            name='data_modifica',
            field=models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='firme',
            field=models.ManyToManyField(help_text='Elenco firme', related_name='formulari', through='valutazioni.Firma', to='dipendenti.dipendente'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='data_obiettivo',
            field=models.DateField(default=datetime.datetime(2023, 4, 6, 12, 16, 26, 772979), verbose_name='Data di DISCUSSIONE criteri ed obiettivi'),
        ),
        migrations.AddField(
            model_name='firma',
            name='formulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valutazioni.formulario', verbose_name='Formulario in firma'),
        ),
    ]
