# Generated by Django 4.0.4 on 2023-04-14 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valutazioni', '0027_firma_formulario_data_modifica_formulario_firme_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firma',
            options={'verbose_name': 'Firma', 'verbose_name_plural': 'Firme'},
        ),
        migrations.AddField(
            model_name='firma',
            name='tipo_formulario',
            field=models.CharField(default='Obiettivi', max_length=12, verbose_name='Tipo di Formulario'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='data_obiettivo',
            field=models.DateField(default=datetime.datetime(2023, 4, 14, 8, 35, 19, 738215), verbose_name='Data di DISCUSSIONE criteri ed obiettivi'),
        ),
    ]
