# Generated by Django 4.0.4 on 2023-04-17 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valutazioni', '0028_alter_firma_options_firma_tipo_formulario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='data_obiettivo',
            field=models.DateField(default=datetime.datetime(2023, 4, 17, 8, 31, 27, 90181), verbose_name='Data di DISCUSSIONE criteri ed obiettivi'),
        ),
    ]
