# Generated by Django 4.0.4 on 2023-04-18 05:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0032_alter_dipendente_qualifica_data_da_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('valutazioni', '0029_alter_formulario_data_obiettivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='data_obiettivo',
            field=models.DateField(default=datetime.datetime(2023, 4, 18, 7, 43, 36, 406159), verbose_name='Data di DISCUSSIONE criteri ed obiettivi'),
        ),
        migrations.CreateModel(
            name='HistoricalFormulario',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True, verbose_name='Codice Identificativo')),
                ('data_obiettivo', models.DateField(default=datetime.datetime(2023, 4, 18, 7, 43, 36, 406159), verbose_name='Data di DISCUSSIONE criteri ed obiettivi')),
                ('data_valutazione', models.DateField(blank=True, null=True, verbose_name='Data di VALUTAZIONE criteri ed obiettivi')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note del dipendente')),
                ('data_modifica', models.DateTimeField(blank=True, editable=False, verbose_name='Data ultima modifica')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('anno', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='valutazioni.anno', verbose_name='Anno di riferimento')),
                ('dipqual', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dipendenti.dipendente_qualifica', verbose_name='Dipendente valutato')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('logo', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dipendenti.logo', verbose_name='logo del modello')),
            ],
            options={
                'verbose_name': 'historical Formulario di valutazione annuale',
                'verbose_name_plural': 'historical Formulari di valutazione annuali',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
