# Generated by Django 4.0.4 on 2023-04-18 06:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0033_alter_dipendente_qualifica_data_da_and_more'),
        ('valutazioni', '0030_alter_formulario_data_obiettivo_historicalformulario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='data_obiettivo',
            field=models.DateField(default=datetime.datetime(2023, 4, 18, 8, 8, 10, 302734), verbose_name='Data di DISCUSSIONE criteri ed obiettivi'),
        ),
        migrations.AlterField(
            model_name='historicalformulario',
            name='data_obiettivo',
            field=models.DateField(default=datetime.datetime(2023, 4, 18, 8, 8, 10, 302734), verbose_name='Data di DISCUSSIONE criteri ed obiettivi'),
        ),
        migrations.CreateModel(
            name='HistoricalFormulario_Sociale',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True, verbose_name='Codice Identificativo')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('formulario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='valutazioni.formulario')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='valutazioni.historicalformulario')),
                ('sociale', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to=models.Q(('tipo_valutazione__sezione__iexact', 'c')), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='valutazioni.elemento', verbose_name='Competenza sociale')),
                ('voto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='valutazioni.voto')),
            ],
            options={
                'verbose_name': 'HistoricalFormulario_Sociale',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFormulario_Prestazione',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True, verbose_name='Codice Identificativo')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('formulario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='valutazioni.formulario')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='valutazioni.historicalformulario')),
                ('prestazione', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to=models.Q(('tipo_valutazione__sezione__iexact', 'b')), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='valutazioni.elemento')),
                ('voto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='valutazioni.voto')),
            ],
            options={
                'verbose_name': 'HistoricalFormulario_Prestazione',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFormulario_Obiettivo',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True, verbose_name='Codice Identificativo')),
                ('descrizione', models.CharField(max_length=100, verbose_name="Descrizione dell'obiettivo")),
                ('risultato', models.CharField(blank=True, max_length=150, null=True, verbose_name="Risultato del conseguimento dell'obiettivo")),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('formulario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='valutazioni.formulario')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='valutazioni.historicalformulario')),
                ('obiettivo', models.ForeignKey(blank=True, db_constraint=False, default=1, limit_choices_to=models.Q(('tipo_valutazione__sezione__iexact', 'a')), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='valutazioni.elemento')),
                ('voto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='valutazioni.voto')),
            ],
            options={
                'verbose_name': 'HistoricalFormulario_Obiettivo',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFormulario_Coordinamento',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True, verbose_name='Codice Identificativo')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('coordinamento', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to=models.Q(('tipo_valutazione__sezione__iexact', 'd')), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='valutazioni.elemento', verbose_name='Competenza di coordinamento')),
                ('formulario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='valutazioni.formulario')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='valutazioni.historicalformulario')),
                ('voto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='valutazioni.voto')),
            ],
            options={
                'verbose_name': 'HistoricalFormulario_Coordinamento',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFirma',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True, verbose_name='Codice Identificativo')),
                ('data_firma', models.DateTimeField(blank=True, editable=False, verbose_name='Data di firma')),
                ('tipo_formulario', models.CharField(default='Obiettivi', max_length=12, verbose_name='Tipo di Formulario')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note del dipendente')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('dipendente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dipendenti.dipendente', verbose_name='Utente firmatario')),
                ('formulario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='valutazioni.formulario', verbose_name='Formulario in firma')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='valutazioni.historicalformulario')),
            ],
            options={
                'verbose_name': 'HistoricalFirma',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
