# Generated by Django 4.0.4 on 2023-06-06 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valutazioni', '0033_alter_formulario_data_obiettivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='data_obiettivo',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 16, 6, 43, 299213), verbose_name='Data di DISCUSSIONE criteri ed obiettivi'),
        ),
        migrations.AlterField(
            model_name='historicalformulario',
            name='data_obiettivo',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 16, 6, 43, 299213), verbose_name='Data di DISCUSSIONE criteri ed obiettivi'),
        ),
    ]
