# Generated by Django 4.0.4 on 2023-06-12 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valutazioni', '0038_alter_formulario_data_obiettivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='data_obiettivo',
            field=models.DateField(default=datetime.datetime(2023, 6, 12, 8, 44, 20, 330050), verbose_name='Data di DISCUSSIONE criteri ed obiettivi'),
        ),
        migrations.AlterField(
            model_name='historicalformulario',
            name='data_obiettivo',
            field=models.DateField(default=datetime.datetime(2023, 6, 12, 8, 44, 20, 330050), verbose_name='Data di DISCUSSIONE criteri ed obiettivi'),
        ),
    ]
