# Generated by Django 4.0.4 on 2023-06-12 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('valutazioni', '0039_alter_formulario_data_obiettivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='data_obiettivo',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data di DISCUSSIONE criteri ed obiettivi'),
        ),
        migrations.AlterField(
            model_name='historicalformulario',
            name='data_obiettivo',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data di DISCUSSIONE criteri ed obiettivi'),
        ),
    ]
