# Generated by Django 5.0.1 on 2024-06-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valutazioni', '0040_alter_formulario_data_obiettivo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulario_coordinamento',
            options={'verbose_name': 'Criterio di Coordinamento', 'verbose_name_plural': 'SOLO COORDINATORI (2)'},
        ),
        migrations.AlterModelOptions(
            name='formulario_obiettivo',
            options={'verbose_name': 'Obiettivo annuale.', 'verbose_name_plural': 'Obiettivi annuali (1+)'},
        ),
        migrations.AlterModelOptions(
            name='formulario_prestazione',
            options={'verbose_name': 'Criterio di prestazione', 'verbose_name_plural': 'Prestazioni (7)'},
        ),
        migrations.AlterModelOptions(
            name='formulario_sociale',
            options={'verbose_name': 'Criterio di competenza sociale', 'verbose_name_plural': 'Sociali (3)'},
        ),
    ]
