# Generated by Django 5.0.1 on 2024-01-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gic', '0016_attivita_fa_icon_cdc_fa_icon_evento_fa_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segnalazione',
            name='eventi',
            field=models.ManyToManyField(related_name='segnalazioni', to='gic.evento', verbose_name='Eventi collegati'),
        ),
        migrations.DeleteModel(
            name='EventoSegnalazione',
        ),
    ]
