# Generated by Django 5.0.1 on 2024-01-19 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gic', '0017_alter_segnalazione_eventi_delete_eventosegnalazione'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoSegnalazione',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, verbose_name='Data di creazione')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data di ultima modifica')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gic.evento', verbose_name='Evento')),
                ('segnalazione', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gic.segnalazione', verbose_name='Segnalazione')),
            ],
            options={
                'verbose_name': 'Evento - Segnalazione',
                'verbose_name_plural': 'Eventi - Segnalazioni',
            },
        ),
        migrations.AlterField(
            model_name='segnalazione',
            name='eventi',
            field=models.ManyToManyField(related_name='segnalazioni', through='gic.EventoSegnalazione', to='gic.evento', verbose_name='Eventi collegati'),
        ),
    ]
