# Generated by Django 4.0.4 on 2022-05-17 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dipendenti', '0011_alter_logo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GruppoPratica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome del Gruppo')),
                ('responsabile', models.ForeignKey(limit_choices_to={'ruolo__responsabile': True}, on_delete=django.db.models.deletion.CASCADE, related_name='responsabile_gruppo', to='dipendenti.dipendente')),
            ],
            options={
                'verbose_name': 'Gruppo di gestione pratiche',
                'verbose_name_plural': 'Gruppi di gestione pratiche',
            },
        ),
        migrations.CreateModel(
            name='Delega',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('documento', models.CharField(max_length=10, verbose_name='ID documento')),
                ('peso', models.IntegerField(verbose_name='Carico della pratica')),
                ('data_assegnazione', models.DateField(auto_now_add=True, verbose_name='Data di assegnazione')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Annotazioni')),
                ('assegnatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipendenti.dipendente', verbose_name='Assegnatario della pratica')),
            ],
            options={
                'verbose_name': 'Delega',
                'verbose_name_plural': 'Deleghe',
            },
        ),
    ]
