# Generated by Django 4.0.4 on 2022-05-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0011_alter_logo_options'),
        ('pratiche', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gruppopratica',
            name='delegato',
            field=models.ManyToManyField(related_name='delegato', to='dipendenti.dipendente'),
        ),
    ]
