# Generated by Django 4.0.4 on 2022-05-18 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0002_gruppopratica_delegato'),
    ]

    operations = [
        migrations.AddField(
            model_name='delega',
            name='gruppo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pratiche.gruppopratica', verbose_name='Gruppo gestione pratiche'),
        ),
    ]
