# Generated by Django 4.0.4 on 2022-05-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0003_delega_gruppo'),
    ]

    operations = [
        migrations.AddField(
            model_name='delega',
            name='completato',
            field=models.BooleanField(default=False, verbose_name='Pratica completata'),
        ),
        migrations.AddField(
            model_name='delega',
            name='data_completamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data di completamento'),
        ),
    ]
