# Generated by Django 4.0.4 on 2022-06-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0005_delega_pratica_collegata'),
    ]

    operations = [
        migrations.AddField(
            model_name='delega',
            name='system',
            field=models.BooleanField(default=False, verbose_name='sistema'),
        ),
    ]
