# Generated by Django 4.0.4 on 2022-06-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0006_delega_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='gruppopratica',
            name='email',
            field=models.TextField(default='Il dirigente \r\n\r\nArch. Alessandra Montel', verbose_name='Testo della e-mail da inviare'),
        ),
    ]
