# Generated by Django 4.0.4 on 2022-06-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0007_gruppopratica_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gruppopratica',
            name='email',
            field=models.TextField(default='Il dirigente \r\n\r\nNOME DIRIGENTE', verbose_name='Testo della e-mail da inviare'),
        ),
    ]
