# Generated by Django 4.0.4 on 2022-06-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0008_alter_gruppopratica_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gruppopratica',
            name='email',
            field=models.TextField(default='Buon giorno. Ti è stata assegnata una nuova pratica da espletare.\r\n\r\nIl documento {}, relativo alla pratica, lo trovi qui: {}\r\n\r\nIl riepilogo delle pratiche lo trovi al link http://leifersdjango.leifers.gvcc.net/pratiche/lista/\r\n\r\nCordiali saluti.\r\n\r\nIl dirigente \r\n\r\nNOME DIRIGENTE', verbose_name='Testo della e-mail da inviare'),
        ),
    ]
