# Generated by Django 4.0.4 on 2022-06-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0009_alter_gruppopratica_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='gruppopratica',
            name='titolo_email',
            field=models.CharField(default='Assegnazione Pratica', max_length=120, verbose_name='Titolo della e-mail'),
        ),
    ]
