# Generated by Django 4.0.4 on 2022-06-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0010_gruppopratica_titolo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='gruppopratica',
            name='mittente',
            field=models.CharField(default='urbanistica@comune.laives.bz.it', max_length=120, verbose_name='Mittente della e-mail'),
        ),
    ]
