# Generated by Django 4.0.4 on 2022-06-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0011_gruppopratica_mittente'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPratica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome della pratica')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Annotazioni')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='gruppopratica',
            name='delegato',
        ),
        migrations.AlterField(
            model_name='gruppopratica',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome del gruppo'),
        ),
    ]
