# Generated by Django 4.0.4 on 2022-06-16 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0011_alter_logo_options'),
        ('pratiche', '0012_tipopratica_remove_gruppopratica_delegato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dipendente_GruppoPratica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipendenti.dipendente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='gruppopratica',
            name='delegato',
            field=models.ManyToManyField(through='pratiche.Dipendente_GruppoPratica', to='dipendenti.dipendente'),
        ),
        migrations.AddField(
            model_name='gruppopratica',
            name='pratiche',
            field=models.ManyToManyField(to='pratiche.tipopratica'),
        ),
        migrations.AddField(
            model_name='dipendente_gruppopratica',
            name='gruppopratica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pratiche.gruppopratica'),
        ),
        migrations.AddField(
            model_name='dipendente_gruppopratica',
            name='pratiche',
            field=models.ManyToManyField(to='pratiche.tipopratica'),
        ),
    ]
