# Generated by Django 4.0.4 on 2022-06-16 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0013_dipendente_gruppopratica_gruppopratica_delegato_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipopratica',
            options={'verbose_name': 'Tipologia di pratica', 'verbose_name_plural': 'Tipologie di pratiche'},
        ),
        migrations.AddField(
            model_name='delega',
            name='tipo_pratica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pratiche.tipopratica', verbose_name='Tipologia di pratica'),
        ),
    ]
