# Generated by Django 4.0.4 on 2022-06-16 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0011_alter_logo_options'),
        ('pratiche', '0014_alter_tipopratica_options_delega_tipo_pratica'),
    ]

    operations = [
        migrations.AddField(
            model_name='gruppopratica',
            name='gestori',
            field=models.ManyToManyField(related_name='gruppo_gestore', to='dipendenti.dipendente'),
        ),
        migrations.AlterField(
            model_name='gruppopratica',
            name='responsabile',
            field=models.ForeignKey(limit_choices_to={'ruolo__responsabile': True}, on_delete=django.db.models.deletion.CASCADE, related_name='gruppo_responsabile', to='dipendenti.dipendente'),
        ),
    ]
