# Generated by Django 4.0.4 on 2022-06-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0015_gruppopratica_gestori_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dipendente_gruppopratica',
            options={'verbose_name': 'Dipendente - Gruppo di gestione pratiche', 'verbose_name_plural': 'Dipendenti - Gruppi di gestione pratiche'},
        ),
        migrations.AddField(
            model_name='delega',
            name='origine',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Assegnazione'),
        ),
    ]
