# Generated by Django 4.0.4 on 2022-06-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0016_alter_dipendente_gruppopratica_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delega',
            name='origine',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Assegnazione'),
        ),
    ]
