# Generated by Django 4.0.4 on 2023-03-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0017_alter_delega_origine'),
    ]

    operations = [
        migrations.AddField(
            model_name='delega',
            name='richiedente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Richiedente:'),
        ),
    ]
