# Generated by Django 3.2 on 2022-04-11 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date_through_abstract',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Matricola')),
                ('data_da', models.DateField(verbose_name='Data di inizio')),
                ('data_a', models.DateField(blank=True, null=True, verbose_name='Data di fine')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Annotazioni')),
            ],
        ),
        migrations.CreateModel(
            name='Dipendente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Matricola')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('cognome', models.CharField(max_length=40, verbose_name='Cognome')),
                ('userid', models.CharField(max_length=16, verbose_name='Nome Utente')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('telefono', models.CharField(blank=True, max_length=40, null=True, verbose_name='Telefono')),
                ('cellulare', models.CharField(blank=True, max_length=40, null=True, verbose_name='Cellulare')),
                ('catprotetta', models.BooleanField(default=False, verbose_name='Categoria Protetta')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note aggiuntive')),
            ],
        ),
        migrations.CreateModel(
            name='Livello',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome Breve')),
                ('nome_it_m', models.CharField(max_length=40, verbose_name='Nome italiano maschile')),
                ('nome_it_f', models.CharField(max_length=40, verbose_name='Nome italiano femminile')),
                ('nome_dt_m', models.CharField(max_length=40, verbose_name='Nome tedesco maschile')),
                ('nome_dt_f', models.CharField(max_length=40, verbose_name='Nome tedesco femminile')),
                ('coefficiente', models.IntegerField(verbose_name='Coefficiente premio produzione')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Qualifica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome Breve')),
                ('nome_it_m', models.CharField(max_length=40, verbose_name='Nome italiano maschile')),
                ('nome_it_f', models.CharField(max_length=40, verbose_name='Nome italiano femminile')),
                ('nome_dt_m', models.CharField(max_length=40, verbose_name='Nome tedesco maschile')),
                ('nome_dt_f', models.CharField(max_length=40, verbose_name='Nome tedesco femminile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ruolo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome Breve')),
                ('nome_it_m', models.CharField(max_length=40, verbose_name='Nome italiano maschile')),
                ('nome_it_f', models.CharField(max_length=40, verbose_name='Nome italiano femminile')),
                ('nome_dt_m', models.CharField(max_length=40, verbose_name='Nome tedesco maschile')),
                ('nome_dt_f', models.CharField(max_length=40, verbose_name='Nome tedesco femminile')),
                ('dirigente', models.BooleanField(default=False, verbose_name='Ruolo dirigenziale')),
                ('coordinatore', models.BooleanField(default=False, verbose_name='Ruolo di coordinamento')),
                ('responsabile', models.BooleanField(default=False, verbose_name='Ruolo di responsabile')),
                ('segretario', models.BooleanField(default=False, verbose_name='Ruolo segretario generale')),
                ('ammsistema', models.BooleanField(default=False, verbose_name='Ruolo amministratore di sistema')),
                ('sindaco', models.BooleanField(default=False, verbose_name='Ruolo da sindaco')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Servizio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome Breve')),
                ('nome_it_m', models.CharField(max_length=40, verbose_name='Nome italiano maschile')),
                ('nome_it_f', models.CharField(max_length=40, verbose_name='Nome italiano femminile')),
                ('nome_dt_m', models.CharField(max_length=40, verbose_name='Nome tedesco maschile')),
                ('nome_dt_f', models.CharField(max_length=40, verbose_name='Nome tedesco femminile')),
                ('esente_irap', models.BooleanField(default=False, verbose_name='Servizio esente IRAP')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ufficio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome Breve')),
                ('nome_it_m', models.CharField(max_length=40, verbose_name='Nome italiano maschile')),
                ('nome_it_f', models.CharField(max_length=40, verbose_name='Nome italiano femminile')),
                ('nome_dt_m', models.CharField(max_length=40, verbose_name='Nome tedesco maschile')),
                ('nome_dt_f', models.CharField(max_length=40, verbose_name='Nome tedesco femminile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Servizio_Ufficio',
            fields=[
                ('date_through_abstract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personale.date_through_abstract')),
                ('dirigente', models.ForeignKey(limit_choices_to={'ruolo__dirigente': True}, on_delete=django.db.models.deletion.CASCADE, to='personale.dipendente')),
                ('servizio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personale.servizio')),
                ('ufficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personale.ufficio')),
            ],
            bases=('personale.date_through_abstract',),
        ),
        migrations.AddField(
            model_name='servizio',
            name='ufficio',
            field=models.ManyToManyField(through='personale.Servizio_Ufficio', to='personale.Ufficio'),
        ),
        migrations.CreateModel(
            name='Dipendente_Ruolo',
            fields=[
                ('date_through_abstract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personale.date_through_abstract')),
                ('Ruolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personale.ruolo')),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personale.dipendente')),
            ],
            options={
                'abstract': False,
            },
            bases=('personale.date_through_abstract',),
        ),
        migrations.CreateModel(
            name='Dipendente_qualifica',
            fields=[
                ('date_through_abstract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personale.date_through_abstract')),
                ('Qualifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personale.qualifica')),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personale.dipendente')),
            ],
            options={
                'abstract': False,
            },
            bases=('personale.date_through_abstract',),
        ),
        migrations.CreateModel(
            name='Dipendente_Livello',
            fields=[
                ('date_through_abstract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personale.date_through_abstract')),
                ('Livello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personale.livello')),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personale.dipendente')),
            ],
            options={
                'abstract': False,
            },
            bases=('personale.date_through_abstract',),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='livello',
            field=models.ManyToManyField(through='personale.Dipendente_Livello', to='personale.Livello'),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='qualifica',
            field=models.ManyToManyField(through='personale.Dipendente_qualifica', to='personale.Qualifica'),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='ruolo',
            field=models.ManyToManyField(through='personale.Dipendente_Ruolo', to='personale.Ruolo'),
        ),
    ]
