# Generated by Django 3.2 on 2022-04-11 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dipendente_livello',
            old_name='Livello',
            new_name='livello',
        ),
        migrations.RenameField(
            model_name='dipendente_qualifica',
            old_name='Qualifica',
            new_name='qualifica',
        ),
        migrations.RenameField(
            model_name='dipendente_ruolo',
            old_name='Ruolo',
            new_name='ruolo',
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='qualifica',
            field=models.ManyToManyField(through='personale.Dipendente_Qualifica', to='personale.Qualifica'),
        ),
        migrations.CreateModel(
            name='Dipendente_Servizio',
            fields=[
                ('date_through_abstract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personale.date_through_abstract')),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personale.dipendente')),
                ('servizio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personale.servizio')),
            ],
            options={
                'abstract': False,
            },
            bases=('personale.date_through_abstract',),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='servizio',
            field=models.ManyToManyField(through='personale.Dipendente_Servizio', to='personale.Servizio'),
        ),
    ]
