# Generated by Django 3.2 on 2022-04-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0002_auto_20220411_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='date_through_abstract',
            options={'ordering': ['data_da']},
        ),
        migrations.AlterModelOptions(
            name='dipendente',
            options={'ordering': ['cognome', 'nome'], 'verbose_name': 'Dipendente', 'verbose_name_plural': 'Dipendenti'},
        ),
        migrations.AlterModelOptions(
            name='livello',
            options={'ordering': ['nome'], 'verbose_name': 'Livello', 'verbose_name_plural': 'Livelli'},
        ),
        migrations.AlterModelOptions(
            name='qualifica',
            options={'ordering': ['nome'], 'verbose_name': 'Qualifica', 'verbose_name_plural': 'Qualifiche'},
        ),
        migrations.AlterModelOptions(
            name='ruolo',
            options={'ordering': ['nome'], 'verbose_name': 'Ruolo', 'verbose_name_plural': 'Ruoli'},
        ),
        migrations.AlterModelOptions(
            name='servizio',
            options={'ordering': ['nome'], 'verbose_name': 'Servizio', 'verbose_name_plural': 'Servizi'},
        ),
        migrations.AlterModelOptions(
            name='ufficio',
            options={'ordering': ['nome'], 'verbose_name': 'Ufficio', 'verbose_name_plural': 'Uffici'},
        ),
        migrations.AlterField(
            model_name='date_through_abstract',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo'),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo'),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='qualifica',
            field=models.ManyToManyField(through='personale.Dipendente_Qualifica', to='personale.Qualifica'),
        ),
    ]
