# Generated by Django 3.2 on 2022-04-11 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0003_auto_20220411_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dipendente',
            name='livello',
        ),
        migrations.RemoveField(
            model_name='dipendente',
            name='qualifica',
        ),
        migrations.RemoveField(
            model_name='dipendente',
            name='ruolo',
        ),
        migrations.RemoveField(
            model_name='dipendente',
            name='servizio',
        ),
    ]
