# Generated by Django 3.2 on 2022-04-12 06:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0005_auto_20220411_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servizio_Responsabile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_da', models.DateField(verbose_name='Data di inizio')),
                ('data_a', models.DateField(blank=True, null=True, verbose_name='Data di fine')),
            ],
            options={
                'verbose_name': 'Servizio - Responsabile',
                'verbose_name_plural': 'Servizi - Responsabili',
            },
        ),
        migrations.CreateModel(
            name='Ufficio_Dirigente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_da', models.DateField(verbose_name='Data di inizio')),
                ('data_a', models.DateField(blank=True, null=True, verbose_name='Data di fine')),
            ],
            options={
                'verbose_name': 'Ufficio - Dirigente',
                'verbose_name_plural': 'Uffici - Dirigenti',
            },
        ),
        migrations.RemoveField(
            model_name='dipendente_livello',
            name='date_through_abstract_ptr',
        ),
        migrations.RemoveField(
            model_name='dipendente_livello',
            name='dipendente',
        ),
        migrations.RemoveField(
            model_name='dipendente_livello',
            name='livello',
        ),
        migrations.AlterModelOptions(
            name='dipendente_qualifica',
            options={'verbose_name': 'Dipendente - Qualifica', 'verbose_name_plural': 'Dipendenti - Qualifiche'},
        ),
        migrations.AlterModelOptions(
            name='dipendente_ruolo',
            options={'verbose_name': 'Dipendente - Ruolo', 'verbose_name_plural': 'Dipendenti - Ruoli'},
        ),
        migrations.AlterModelOptions(
            name='dipendente_servizio',
            options={'verbose_name': 'Dipendente - Servizio', 'verbose_name_plural': 'Dipendenti - Servizi'},
        ),
        migrations.AlterModelOptions(
            name='livello',
            options={'ordering': ['indice'], 'verbose_name': 'Livello', 'verbose_name_plural': 'Livelli'},
        ),
        migrations.AlterModelOptions(
            name='servizio_ufficio',
            options={'ordering': ['data_da']},
        ),
        migrations.RemoveField(
            model_name='dipendente',
            name='livello',
        ),
        migrations.RemoveField(
            model_name='dipendente_qualifica',
            name='date_through_abstract_ptr',
        ),
        migrations.RemoveField(
            model_name='dipendente_ruolo',
            name='date_through_abstract_ptr',
        ),
        migrations.RemoveField(
            model_name='dipendente_servizio',
            name='date_through_abstract_ptr',
        ),
        migrations.RemoveField(
            model_name='livello',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='livello',
            name='nome_dt_f',
        ),
        migrations.RemoveField(
            model_name='livello',
            name='nome_dt_m',
        ),
        migrations.RemoveField(
            model_name='livello',
            name='nome_it_f',
        ),
        migrations.RemoveField(
            model_name='livello',
            name='nome_it_m',
        ),
        migrations.RemoveField(
            model_name='servizio_ufficio',
            name='date_through_abstract_ptr',
        ),
        migrations.RemoveField(
            model_name='servizio_ufficio',
            name='dirigente',
        ),
        migrations.AddField(
            model_name='dipendente_qualifica',
            name='data_a',
            field=models.DateField(blank=True, null=True, verbose_name='Data di fine'),
        ),
        migrations.AddField(
            model_name='dipendente_qualifica',
            name='data_da',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data di inizio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dipendente_qualifica',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='Codice Identificativo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dipendente_ruolo',
            name='data_a',
            field=models.DateField(blank=True, null=True, verbose_name='Data di fine'),
        ),
        migrations.AddField(
            model_name='dipendente_ruolo',
            name='data_da',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data di inizio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dipendente_ruolo',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='Codice Identificativo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dipendente_servizio',
            name='data_a',
            field=models.DateField(blank=True, null=True, verbose_name='Data di fine'),
        ),
        migrations.AddField(
            model_name='dipendente_servizio',
            name='data_da',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data di inizio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dipendente_servizio',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='Codice Identificativo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livello',
            name='indice',
            field=models.IntegerField(default=1, verbose_name='Indice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livello',
            name='livello',
            field=models.CharField(default=1, max_length=5, verbose_name='Livello'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualifica',
            name='livello',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='personale.livello', verbose_name='Livello'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servizio_ufficio',
            name='data_a',
            field=models.DateField(blank=True, null=True, verbose_name='Data di fine'),
        ),
        migrations.AddField(
            model_name='servizio_ufficio',
            name='data_da',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data di inizio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servizio_ufficio',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='Codice Identificativo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='qualifica',
            field=models.ManyToManyField(through='personale.Dipendente_Qualifica', to='personale.Qualifica'),
        ),
        migrations.AlterField(
            model_name='qualifica',
            name='nome_dt_f',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome tedesco femminile'),
        ),
        migrations.AlterField(
            model_name='qualifica',
            name='nome_dt_m',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome tedesco maschile'),
        ),
        migrations.AlterField(
            model_name='qualifica',
            name='nome_it_f',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome italiano femminile'),
        ),
        migrations.AlterField(
            model_name='ruolo',
            name='nome_dt_f',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome tedesco femminile'),
        ),
        migrations.AlterField(
            model_name='ruolo',
            name='nome_dt_m',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome tedesco maschile'),
        ),
        migrations.AlterField(
            model_name='ruolo',
            name='nome_it_f',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome italiano femminile'),
        ),
        migrations.AlterField(
            model_name='servizio',
            name='nome_dt_f',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome tedesco femminile'),
        ),
        migrations.AlterField(
            model_name='servizio',
            name='nome_dt_m',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome tedesco maschile'),
        ),
        migrations.AlterField(
            model_name='servizio',
            name='nome_it_f',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome italiano femminile'),
        ),
        migrations.AlterField(
            model_name='ufficio',
            name='nome_dt_f',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome tedesco femminile'),
        ),
        migrations.AlterField(
            model_name='ufficio',
            name='nome_dt_m',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome tedesco maschile'),
        ),
        migrations.AlterField(
            model_name='ufficio',
            name='nome_it_f',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome italiano femminile'),
        ),
        migrations.DeleteModel(
            name='Date_through_abstract',
        ),
        migrations.DeleteModel(
            name='Dipendente_Livello',
        ),
        migrations.AddField(
            model_name='ufficio_dirigente',
            name='dirigente',
            field=models.ForeignKey(limit_choices_to={'ruolo__dirigente': True}, on_delete=django.db.models.deletion.CASCADE, to='personale.dipendente'),
        ),
        migrations.AddField(
            model_name='ufficio_dirigente',
            name='ufficio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personale.ufficio'),
        ),
        migrations.AddField(
            model_name='servizio_responsabile',
            name='responsabile',
            field=models.ForeignKey(limit_choices_to={'ruolo__responsabile': True}, on_delete=django.db.models.deletion.CASCADE, to='personale.dipendente'),
        ),
        migrations.AddField(
            model_name='servizio_responsabile',
            name='servizio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personale.servizio'),
        ),
        migrations.AddField(
            model_name='servizio',
            name='responsabile',
            field=models.ManyToManyField(related_name='responsabile', through='personale.Servizio_Responsabile', to='personale.Dipendente'),
        ),
        migrations.AddField(
            model_name='ufficio',
            name='dirigente',
            field=models.ManyToManyField(related_name='dirigente', through='personale.Ufficio_Dirigente', to='personale.Dipendente'),
        ),
    ]
