# Generated by Django 3.2 on 2022-04-12 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personale', '0002_alter_livello_livello'),
        ('personale', '0006_auto_20220412_0859'),
    ]

    operations = [
    ]
