# Generated by Django 3.2 on 2021-04-26 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fascia',
            fields=[
                ('nome', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Abbreviazione')),
                ('descrizione', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrizione della Fascia Oraria')),
            ],
            options={
                'verbose_name': 'Fascia oraria',
                'verbose_name_plural': 'Fasce orarie',
            },
        ),
        migrations.CreateModel(
            name='Giorno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(unique=True, verbose_name='Giorno')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Annotazioni')),
            ],
            options={
                'verbose_name': 'Giorno',
                'verbose_name_plural': 'Giorni',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('cognome', models.CharField(max_length=40, verbose_name='Cognome')),
                ('email', models.CharField(blank=True, max_length=40, null=True, verbose_name='E-mail')),
                ('telefono', models.CharField(blank=True, max_length=40, null=True, verbose_name='Telefono')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note aggiuntive')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Persone',
            },
        ),
        migrations.CreateModel(
            name='Ruolo',
            fields=[
                ('nome', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Abbreviazione')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione del ruolo')),
            ],
            options={
                'verbose_name': 'Ruolo',
                'verbose_name_plural': 'Ruoli',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avvisato', models.BooleanField(default=False, verbose_name='Persona Avvisata')),
                ('fascia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turni.fascia')),
                ('giorno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turni.giorno')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turni.persona')),
                ('ruolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turni.ruolo')),
            ],
            options={
                'verbose_name': 'Turno assegnato',
                'verbose_name_plural': 'Turni assegnati',
                'unique_together': {('giorno', 'fascia', 'ruolo')},
            },
        ),
    ]
