# Generated by Django 3.2 on 2021-04-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruolo',
            name='colore',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Codice esadecimale colore'),
        ),
        migrations.AddField(
            model_name='ruolo',
            name='ordine',
            field=models.IntegerField(default=0, verbose_name='Indice di ordinamento'),
        ),
    ]
