# Generated by Django 3.2 on 2021-04-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turni', '0002_auto_20210426_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='confermato',
            field=models.BooleanField(default=False, verbose_name='Turno confermato'),
        ),
    ]
