# Generated by Django 3.2 on 2021-04-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turni', '0003_turno_confermato'),
    ]

    operations = [
        migrations.AddField(
            model_name='fascia',
            name='descrizione_de',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrizione della Fascia Oraria (Tedesco)'),
        ),
        migrations.AddField(
            model_name='ruolo',
            name='descrizione_de',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del ruolo (Tedesco)'),
        ),
    ]
