# Generated by Django 3.2 on 2021-04-27 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turni', '0004_auto_20210426_1448'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together=set(),
        ),
    ]
