# Generated by Django 3.2 on 2021-04-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turni', '0005_alter_turno_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='disponibilita',
            field=models.ManyToManyField(to='turni.Fascia'),
        ),
    ]
