# Generated by Django 3.2 on 2021-04-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turni', '0006_persona_disponibilita'),
    ]

    operations = [
        migrations.AddField(
            model_name='fascia',
            name='tipo',
            field=models.CharField(choices=[('MA', 'Mattino'), ('PO', 'Pomeriggio')], default='MA', max_length=2, verbose_name='Tipo di fascia oraria'),
        ),
    ]
