# Generated by Django 3.2 on 2021-04-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turni', '0007_fascia_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fascia',
            name='ordine',
            field=models.IntegerField(default=0, verbose_name='Indice di ordinamento'),
        ),
    ]
