# Generated by Django 3.2 on 2021-04-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turni', '0008_fascia_ordine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fascia',
            options={'ordering': ['ordine'], 'verbose_name': 'Fascia oraria', 'verbose_name_plural': 'Fasce orarie'},
        ),
        migrations.AlterModelOptions(
            name='giorno',
            options={'ordering': ['data'], 'verbose_name': 'Giorno', 'verbose_name_plural': 'Giorni'},
        ),
        migrations.AlterModelOptions(
            name='ruolo',
            options={'ordering': ['ordine'], 'verbose_name': 'Ruolo', 'verbose_name_plural': 'Ruoli'},
        ),
        migrations.AddField(
            model_name='fascia',
            name='desc_breve',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Descrizione breve per tabella'),
        ),
    ]
