# Generated by Django 3.2 on 2021-04-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turni', '0009_auto_20210428_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='capacita',
            field=models.ManyToManyField(to='turni.Ruolo'),
        ),
    ]
