# Generated by Django 3.2 on 2021-05-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turni', '0010_persona_capacita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='capacita',
            field=models.ManyToManyField(blank=True, null=True, to='turni.Ruolo'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='disponibilita',
            field=models.ManyToManyField(blank=True, null=True, to='turni.Fascia'),
        ),
    ]
