# Generated by Django 3.2 on 2021-05-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turni', '0011_auto_20210503_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruolo',
            name='richiesti',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name=''),
        ),
    ]
