# Generated by Django 3.2 on 2021-05-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turni', '0012_ruolo_richiesti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruolo',
            name='richiesti',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Numero di persone richieste per il ruolo'),
        ),
    ]
