# Generated by Django 4.0.4 on 2023-07-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turni', '0014_alter_persona_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='capacita',
            field=models.ManyToManyField(to='turni.ruolo'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='disponibilita',
            field=models.ManyToManyField(to='turni.fascia'),
        ),
    ]
