# Generated by Django 4.0.4 on 2023-03-20 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dipendenti', '0025_alter_dipendente_qualifica_data_da_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbitiPassword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=30, verbose_name="Nome dell'ambito password")),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione dettagliata')),
            ],
            options={
                'verbose_name': 'Ambito della password',
                'verbose_name_plural': 'Ambiti della password',
            },
        ),
        migrations.CreateModel(
            name='Atto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data', models.DateField(verbose_name="Data dell'atto")),
                ('amministratore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atti_amm', to='dipendenti.dipendente', verbose_name='Amministratore di sistema')),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atti', to='dipendenti.dipendente', verbose_name='Dipendente assegnatario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Atto_D3Diritto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data di inserimento')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica')),
                ('data_disattivazione', models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazipone')),
                ('diritto_attivato', models.BooleanField(default=False, verbose_name='Diritto assegnato')),
                ('atto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.atto', verbose_name='Atti')),
            ],
            options={
                'verbose_name': 'Dipendente - Diritto D3',
                'verbose_name_plural': 'Dipendenti - Diritti D3',
            },
        ),
        migrations.CreateModel(
            name='Atto_D3Gruppo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data di inserimento')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica')),
                ('data_disattivazione', models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazipone')),
                ('diritto_attivato', models.BooleanField(default=False, verbose_name='Diritto assegnato')),
                ('lettura', models.BooleanField(default=False, verbose_name='Lettura documenti')),
                ('scrittura', models.BooleanField(default=False, verbose_name='Modifica documenti')),
                ('lettura_r', models.BooleanField(default=False, verbose_name='Lettura documenti riservati')),
                ('scrittura_r', models.BooleanField(default=False, verbose_name='Modifica documenti riservati')),
                ('posta', models.BooleanField(default=False, verbose_name='Accesso casella postale')),
                ('atto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.atto', verbose_name='Atti')),
            ],
            options={
                'verbose_name': 'Dipendente - Diritto Gruppo D3',
                'verbose_name_plural': 'Dipendenti - Diritti Gruppi D3',
            },
        ),
        migrations.CreateModel(
            name='Atto_DirittoRete',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data di inserimento')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica')),
                ('data_disattivazione', models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazipone')),
                ('diritto_attivato', models.BooleanField(default=False, verbose_name='Diritto assegnato')),
                ('atto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.atto', verbose_name='Atti')),
            ],
            options={
                'verbose_name': 'Dipendente - Diritto di Rete',
                'verbose_name_plural': 'Dipendenti - Diritti di Rete',
            },
        ),
        migrations.CreateModel(
            name='Atto_GebevDiritto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data di inserimento')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica')),
                ('data_disattivazione', models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazipone')),
                ('diritto_attivato', models.BooleanField(default=False, verbose_name='Diritto assegnato')),
                ('atto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.atto', verbose_name='Atti')),
            ],
            options={
                'verbose_name': 'Dipendente - Diritto WebApp Django',
                'verbose_name_plural': 'Dipendenti - Diritti WebApp Django',
            },
        ),
        migrations.CreateModel(
            name='Atto_GebevRipartizione',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data di inserimento')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica')),
                ('data_disattivazione', models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazipone')),
                ('diritto_attivato', models.BooleanField(default=False, verbose_name='Diritto assegnato')),
                ('default', models.BooleanField(default=False, verbose_name='Ripartizione di default')),
                ('del_v', models.BooleanField(default=False, verbose_name='Visibilità delibere')),
                ('det_v', models.BooleanField(default=False, verbose_name='Visibilità determinazioni')),
                ('int_v', models.BooleanField(default=False, verbose_name='Visibilità decisioni interne')),
                ('dis_v', models.BooleanField(default=False, verbose_name='Visibilità disposizioni')),
                ('pri_v', models.BooleanField(default=False, verbose_name='Visibilità privacy')),
                ('del_pt', models.BooleanField(default=False, verbose_name='Parere tecnico delibere')),
                ('del_pc', models.BooleanField(default=False, verbose_name='Parere contabile delibere')),
                ('det_pt', models.BooleanField(default=False, verbose_name='Parere tecnico determinazioni')),
                ('det_pc', models.BooleanField(default=False, verbose_name='Parere contabile determinazioni')),
                ('int_p', models.BooleanField(default=False, verbose_name='Parere decisioni interne')),
                ('atto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.atto', verbose_name='Atti')),
            ],
            options={
                'verbose_name': 'Dipendente - Diritto',
                'verbose_name_plural': 'Dipendenti - Diritti',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Atto_Generico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data di inserimento')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica')),
                ('data_disattivazione', models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazipone')),
                ('diritto_attivato', models.BooleanField(default=False, verbose_name='Diritto assegnato')),
                ('atto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.atto', verbose_name='Atti')),
            ],
            options={
                'verbose_name': 'Dipendente - Diritto Gruppo D3',
                'verbose_name_plural': 'Dipendenti - Diritti Gruppi D3',
            },
        ),
        migrations.CreateModel(
            name='Atto_GOffice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data di inserimento')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica')),
                ('data_disattivazione', models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazipone')),
                ('diritto_attivato', models.BooleanField(default=False, verbose_name='Diritto assegnato')),
                ('atto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.atto', verbose_name='Atti')),
            ],
            options={
                'verbose_name': 'Dipendente - Diritto GOffice',
                'verbose_name_plural': 'Dipendenti - Diritti GOffice',
            },
        ),
        migrations.CreateModel(
            name='Atto_GruppoSamba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data di inserimento')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica')),
                ('data_disattivazione', models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazipone')),
                ('diritto_attivato', models.BooleanField(default=False, verbose_name='Diritto assegnato')),
                ('atto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.atto', verbose_name='Atti')),
            ],
            options={
                'verbose_name': 'Dipendente - Gruppo Samba',
                'verbose_name_plural': 'Dipendenti - Gruppi Samba',
            },
        ),
        migrations.CreateModel(
            name='Atto_NextCloud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data di inserimento')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica')),
                ('data_disattivazione', models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazipone')),
                ('diritto_attivato', models.BooleanField(default=False, verbose_name='Diritto assegnato')),
                ('atto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.atto', verbose_name='Atti')),
            ],
            options={
                'verbose_name': 'Dipendente - Gruppo NextCloud',
                'verbose_name_plural': 'Dipendenti - Gruppi NextCloud',
            },
        ),
        migrations.CreateModel(
            name='Atto_O365Gruppo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data di inserimento')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica')),
                ('data_disattivazione', models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazipone')),
                ('diritto_attivato', models.BooleanField(default=False, verbose_name='Diritto assegnato')),
                ('atto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.atto', verbose_name='Atti')),
            ],
            options={
                'verbose_name': 'Dipendente - Gruppo Office 365',
                'verbose_name_plural': 'Dipendenti - Gruppi Office 365',
            },
        ),
        migrations.CreateModel(
            name='Atto_Porta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data di inserimento')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica')),
                ('data_disattivazione', models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazipone')),
                ('diritto_attivato', models.BooleanField(default=False, verbose_name='Diritto assegnato')),
                ('atto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.atto', verbose_name='Atti')),
            ],
            options={
                'verbose_name': 'Dipendente - Porta',
                'verbose_name_plural': 'Dipendenti - Porte',
            },
        ),
        migrations.CreateModel(
            name='Atto_WebApp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data di inserimento')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica')),
                ('data_disattivazione', models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazipone')),
                ('diritto_attivato', models.BooleanField(default=False, verbose_name='Diritto assegnato')),
                ('atto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.atto', verbose_name='Atti')),
            ],
            options={
                'verbose_name': 'Dipendente - Diritto WebApp Django',
                'verbose_name_plural': 'Dipendenti - Diritti WebApp Django',
            },
        ),
        migrations.CreateModel(
            name='GruppoSamba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome del diritto')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto')),
                ('atti', models.ManyToManyField(related_name='gruppi_samba', through='accessi.Atto_GruppoSamba', to='accessi.atto', verbose_name='Atto di Assegnazione')),
            ],
            options={
                'verbose_name': 'Gruppo Samba',
                'verbose_name_plural': 'Gruppi Samba',
            },
        ),
        migrations.CreateModel(
            name='TipoGenerico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome del tipo di diritto')),
                ('sigla', models.CharField(max_length=2, unique=True, verbose_name='Sigla del diritto')),
                ('gruppo', models.CharField(choices=[('D3', 'Diritto D3'), ('TX', 'Testo'), ('GE', 'Generico'), ('GO', 'Gruppo Office365'), ('GB', 'Programa delibere'), ('AT', 'Atto')], max_length=2, verbose_name='Gruppo di tipologie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebApp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome del diritto')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto')),
                ('atti', models.ManyToManyField(related_name='django', through='accessi.Atto_WebApp', to='accessi.atto', verbose_name='Atto di Assegnazione')),
            ],
            options={
                'verbose_name': 'Diritto WebApp Django',
                'verbose_name_plural': 'Diritti WebApp Django',
            },
        ),
        migrations.CreateModel(
            name='TestoFisso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=30, verbose_name='nome del testo fisso')),
                ('testo_fisso_it', models.TextField(verbose_name='Testo fisso italiano')),
                ('testo_fisso_de', models.TextField(verbose_name='Testo fisso tedesco')),
                ('tipologia', models.ForeignKey(limit_choices_to={'gruppo': 'TX'}, on_delete=django.db.models.deletion.CASCADE, to='accessi.tipogenerico', verbose_name='Tipologia di testo fisso')),
            ],
            options={
                'verbose_name': 'Testo fisso',
                'verbose_name_plural': 'Testi fissi',
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=30, verbose_name='nome dello share')),
                ('percorso', models.CharField(max_length=100, verbose_name='percorso di rete dello share')),
                ('GruppoSamba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='accessi.grupposamba', verbose_name='Gruppo samba proprietario')),
            ],
            options={
                'verbose_name': 'Share',
                'verbose_name_plural': 'Shares',
            },
        ),
        migrations.CreateModel(
            name='Porta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome del diritto')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto')),
                ('num_stanza', models.IntegerField(blank=True, null=True, verbose_name='Numero Stanza')),
                ('transponder', models.IntegerField(blank=True, null=True, verbose_name='Codice Transponder')),
                ('atti', models.ManyToManyField(related_name='porta', through='accessi.Atto_Porta', to='accessi.atto', verbose_name='Atto di Assegnazione')),
            ],
            options={
                'verbose_name': 'Porta',
                'verbose_name_plural': 'Porte',
            },
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('password', models.CharField(max_length=24, verbose_name='Password temporanea')),
                ('data_attribuzione', models.DateField(verbose_name="Data dell'attribuzione")),
                ('ambiti', models.ManyToManyField(to='accessi.ambitipassword', verbose_name='Ambiti della password')),
                ('atto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accessi.atto', verbose_name='Atto di assegnazione')),
                ('testo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.testofisso', verbose_name='Testo Fisso')),
            ],
            options={
                'verbose_name': 'Attribuzione password',
                'verbose_name_plural': 'Attribuzioni password',
            },
        ),
        migrations.CreateModel(
            name='O365Gruppo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome del diritto')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto')),
                ('atti', models.ManyToManyField(related_name='o365gruppi', through='accessi.Atto_O365Gruppo', to='accessi.atto', verbose_name='Atto di Assegnazione')),
                ('tipologia', models.ForeignKey(limit_choices_to={'gruppo': 'GO'}, on_delete=django.db.models.deletion.CASCADE, to='accessi.tipogenerico', verbose_name='Tipologia di testo fisso')),
            ],
            options={
                'verbose_name': 'Gruppo Office365',
                'verbose_name_plural': 'Gruppi Office365',
            },
        ),
        migrations.CreateModel(
            name='NextCloud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome del diritto')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto')),
                ('atti', models.ManyToManyField(related_name='nextcloud', through='accessi.Atto_NextCloud', to='accessi.atto', verbose_name='Atto di Assegnazione')),
            ],
            options={
                'verbose_name': 'Gruppo Nextcloud',
                'verbose_name_plural': 'Gruppi Nextcloud',
            },
        ),
        migrations.CreateModel(
            name='GOffice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome del diritto')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto')),
                ('atti', models.ManyToManyField(related_name='goffice', through='accessi.Atto_GOffice', to='accessi.atto', verbose_name='Atto di Assegnazione')),
            ],
            options={
                'verbose_name': 'Diritto GOffice',
                'verbose_name_plural': 'Diritti GOffice',
            },
        ),
        migrations.CreateModel(
            name='Generico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome del diritto')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto')),
                ('atti', models.ManyToManyField(related_name='generici', through='accessi.Atto_Generico', to='accessi.atto', verbose_name='Atto di Assegnazione')),
            ],
            options={
                'verbose_name': 'Diritto Generico',
                'verbose_name_plural': 'Diritti Generici',
            },
        ),
        migrations.CreateModel(
            name='GebevRipartizione',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome del diritto')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto')),
                ('atti', models.ManyToManyField(related_name='gebev_ripartizioni', through='accessi.Atto_GebevRipartizione', to='accessi.atto', verbose_name='Atto di Assegnazione')),
            ],
            options={
                'verbose_name': 'Ripartizione programa Delibere',
                'verbose_name_plural': 'Ripartizioni programa Delibere',
            },
        ),
        migrations.CreateModel(
            name='GebevDiritto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome del diritto')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto')),
                ('atti', models.ManyToManyField(related_name='gebev_diritti', through='accessi.Atto_GebevDiritto', to='accessi.atto', verbose_name='Atto di Assegnazione')),
                ('tipologia', models.ForeignKey(limit_choices_to={'gruppo': 'GB'}, on_delete=django.db.models.deletion.CASCADE, to='accessi.tipogenerico', verbose_name='Tipologia di diritto programma delibere')),
            ],
            options={
                'verbose_name': 'Diritto Programma Delibere',
                'verbose_name_plural': 'Diritti Programma Delibere',
            },
        ),
        migrations.CreateModel(
            name='DirittoRete',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome del diritto')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto')),
                ('atti', models.ManyToManyField(related_name='diritti_rete', through='accessi.Atto_DirittoRete', to='accessi.atto', verbose_name='Atto di Assegnazione')),
            ],
            options={
                'verbose_name': 'Diritto di Rete',
                'verbose_name_plural': 'Diritti di Rete',
            },
        ),
        migrations.CreateModel(
            name='Designazione',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_designazione', models.DateField(verbose_name='Data della designazione')),
                ('atto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accessi.atto', verbose_name='Atto di designazione')),
                ('testo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.testofisso', verbose_name='Testo Fisso')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='D3Gruppo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome del diritto')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto')),
                ('atti', models.ManyToManyField(related_name='d3gruppi', through='accessi.Atto_D3Gruppo', to='accessi.atto', verbose_name='Atto di Assegnazione')),
            ],
            options={
                'verbose_name': 'Diritto Gruppo D3',
                'verbose_name_plural': 'Diritti Gruppi D3',
            },
        ),
        migrations.CreateModel(
            name='D3Diritto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome del diritto')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto')),
                ('atti', models.ManyToManyField(related_name='d3diritti', through='accessi.Atto_D3Diritto', to='accessi.atto', verbose_name='Atto di Assegnazione')),
                ('tipologia', models.ForeignKey(limit_choices_to={'gruppo': 'D3'}, on_delete=django.db.models.deletion.CASCADE, to='accessi.tipogenerico', verbose_name='Tipologia di testo fisso')),
            ],
            options={
                'verbose_name': 'Diritto D3',
                'verbose_name_plural': 'Diritti D3',
            },
        ),
        migrations.AddField(
            model_name='atto_webapp',
            name='diritto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.webapp', verbose_name='Diritto WebApp Django'),
        ),
        migrations.AddField(
            model_name='atto_webapp',
            name='utente_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dipendenti.dipendente', verbose_name='Utente amministratore abilitante'),
        ),
        migrations.AddField(
            model_name='atto_webapp',
            name='utente_disattivazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto'),
        ),
        migrations.AddField(
            model_name='atto_webapp',
            name='utente_inserimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di attribuzione diritto'),
        ),
        migrations.AddField(
            model_name='atto_webapp',
            name='utente_modifica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di modifica diritto'),
        ),
        migrations.AddField(
            model_name='atto_porta',
            name='diritto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.porta', verbose_name='Porta'),
        ),
        migrations.AddField(
            model_name='atto_porta',
            name='utente_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dipendenti.dipendente', verbose_name='Utente amministratore abilitante'),
        ),
        migrations.AddField(
            model_name='atto_porta',
            name='utente_disattivazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto'),
        ),
        migrations.AddField(
            model_name='atto_porta',
            name='utente_inserimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di attribuzione diritto'),
        ),
        migrations.AddField(
            model_name='atto_porta',
            name='utente_modifica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di modifica diritto'),
        ),
        migrations.AddField(
            model_name='atto_o365gruppo',
            name='diritto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.o365gruppo', verbose_name='Gruppo Office 365'),
        ),
        migrations.AddField(
            model_name='atto_o365gruppo',
            name='utente_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dipendenti.dipendente', verbose_name='Utente amministratore abilitante'),
        ),
        migrations.AddField(
            model_name='atto_o365gruppo',
            name='utente_disattivazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto'),
        ),
        migrations.AddField(
            model_name='atto_o365gruppo',
            name='utente_inserimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di attribuzione diritto'),
        ),
        migrations.AddField(
            model_name='atto_o365gruppo',
            name='utente_modifica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di modifica diritto'),
        ),
        migrations.AddField(
            model_name='atto_nextcloud',
            name='diritto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.nextcloud', verbose_name='Gruppo NextCloud'),
        ),
        migrations.AddField(
            model_name='atto_nextcloud',
            name='tipo',
            field=models.ForeignKey(limit_choices_to={'gruppo': 'GE'}, on_delete=django.db.models.deletion.CASCADE, to='accessi.tipogenerico', verbose_name='Tipologia di diritto'),
        ),
        migrations.AddField(
            model_name='atto_nextcloud',
            name='utente_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dipendenti.dipendente', verbose_name='Utente amministratore abilitante'),
        ),
        migrations.AddField(
            model_name='atto_nextcloud',
            name='utente_disattivazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto'),
        ),
        migrations.AddField(
            model_name='atto_nextcloud',
            name='utente_inserimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di attribuzione diritto'),
        ),
        migrations.AddField(
            model_name='atto_nextcloud',
            name='utente_modifica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di modifica diritto'),
        ),
        migrations.AddField(
            model_name='atto_grupposamba',
            name='diritto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.grupposamba', verbose_name='Gruppo Samba'),
        ),
        migrations.AddField(
            model_name='atto_grupposamba',
            name='utente_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dipendenti.dipendente', verbose_name='Utente amministratore abilitante'),
        ),
        migrations.AddField(
            model_name='atto_grupposamba',
            name='utente_disattivazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto'),
        ),
        migrations.AddField(
            model_name='atto_grupposamba',
            name='utente_inserimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di attribuzione diritto'),
        ),
        migrations.AddField(
            model_name='atto_grupposamba',
            name='utente_modifica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di modifica diritto'),
        ),
        migrations.AddField(
            model_name='atto_goffice',
            name='diritto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.goffice', verbose_name='Diritto GOffice'),
        ),
        migrations.AddField(
            model_name='atto_goffice',
            name='utente_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dipendenti.dipendente', verbose_name='Utente amministratore abilitante'),
        ),
        migrations.AddField(
            model_name='atto_goffice',
            name='utente_disattivazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto'),
        ),
        migrations.AddField(
            model_name='atto_goffice',
            name='utente_inserimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di attribuzione diritto'),
        ),
        migrations.AddField(
            model_name='atto_goffice',
            name='utente_modifica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di modifica diritto'),
        ),
        migrations.AddField(
            model_name='atto_generico',
            name='diritto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.generico', verbose_name='Sottosistema Ascot'),
        ),
        migrations.AddField(
            model_name='atto_generico',
            name='tipo',
            field=models.ForeignKey(limit_choices_to={'gruppo': 'GE'}, on_delete=django.db.models.deletion.CASCADE, to='accessi.tipogenerico', verbose_name='Tipologia di diritto'),
        ),
        migrations.AddField(
            model_name='atto_generico',
            name='utente_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dipendenti.dipendente', verbose_name='Utente amministratore abilitante'),
        ),
        migrations.AddField(
            model_name='atto_generico',
            name='utente_disattivazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto'),
        ),
        migrations.AddField(
            model_name='atto_generico',
            name='utente_inserimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di attribuzione diritto'),
        ),
        migrations.AddField(
            model_name='atto_generico',
            name='utente_modifica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di modifica diritto'),
        ),
        migrations.AddField(
            model_name='atto_gebevripartizione',
            name='diritto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.gebevripartizione', verbose_name='Diritto di Gruppo Programma delibere'),
        ),
        migrations.AddField(
            model_name='atto_gebevripartizione',
            name='utente_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dipendenti.dipendente', verbose_name='Utente amministratore abilitante'),
        ),
        migrations.AddField(
            model_name='atto_gebevripartizione',
            name='utente_disattivazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto'),
        ),
        migrations.AddField(
            model_name='atto_gebevripartizione',
            name='utente_inserimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di attribuzione diritto'),
        ),
        migrations.AddField(
            model_name='atto_gebevripartizione',
            name='utente_modifica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di modifica diritto'),
        ),
        migrations.AddField(
            model_name='atto_gebevdiritto',
            name='diritto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.gebevdiritto', verbose_name='Diritto Generale Programa delibere'),
        ),
        migrations.AddField(
            model_name='atto_gebevdiritto',
            name='utente_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dipendenti.dipendente', verbose_name='Utente amministratore abilitante'),
        ),
        migrations.AddField(
            model_name='atto_gebevdiritto',
            name='utente_disattivazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto'),
        ),
        migrations.AddField(
            model_name='atto_gebevdiritto',
            name='utente_inserimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di attribuzione diritto'),
        ),
        migrations.AddField(
            model_name='atto_gebevdiritto',
            name='utente_modifica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di modifica diritto'),
        ),
        migrations.AddField(
            model_name='atto_dirittorete',
            name='diritto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.dirittorete', verbose_name='Diritto di Rete'),
        ),
        migrations.AddField(
            model_name='atto_dirittorete',
            name='utente_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dipendenti.dipendente', verbose_name='Utente amministratore abilitante'),
        ),
        migrations.AddField(
            model_name='atto_dirittorete',
            name='utente_disattivazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto'),
        ),
        migrations.AddField(
            model_name='atto_dirittorete',
            name='utente_inserimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di attribuzione diritto'),
        ),
        migrations.AddField(
            model_name='atto_dirittorete',
            name='utente_modifica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di modifica diritto'),
        ),
        migrations.AddField(
            model_name='atto_d3gruppo',
            name='diritto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.d3gruppo', verbose_name='Diritto di Gruppo D3'),
        ),
        migrations.AddField(
            model_name='atto_d3gruppo',
            name='utente_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dipendenti.dipendente', verbose_name='Utente amministratore abilitante'),
        ),
        migrations.AddField(
            model_name='atto_d3gruppo',
            name='utente_disattivazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto'),
        ),
        migrations.AddField(
            model_name='atto_d3gruppo',
            name='utente_inserimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di attribuzione diritto'),
        ),
        migrations.AddField(
            model_name='atto_d3gruppo',
            name='utente_modifica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di modifica diritto'),
        ),
        migrations.AddField(
            model_name='atto_d3diritto',
            name='diritto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.d3diritto', verbose_name='Diritto D3'),
        ),
        migrations.AddField(
            model_name='atto_d3diritto',
            name='utente_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dipendenti.dipendente', verbose_name='Utente amministratore abilitante'),
        ),
        migrations.AddField(
            model_name='atto_d3diritto',
            name='utente_disattivazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto'),
        ),
        migrations.AddField(
            model_name='atto_d3diritto',
            name='utente_inserimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di attribuzione diritto'),
        ),
        migrations.AddField(
            model_name='atto_d3diritto',
            name='utente_modifica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di modifica diritto'),
        ),
        migrations.AddField(
            model_name='atto',
            name='tipo',
            field=models.ForeignKey(limit_choices_to={'gruppo': 'AT'}, on_delete=django.db.models.deletion.CASCADE, to='accessi.tipogenerico', verbose_name='Tipologia di Atto'),
        ),
    ]
