# Generated by Django 4.0.4 on 2023-03-20 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0026_alter_dipendente_qualifica_data_da_and_more'),
        ('accessi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atto',
            options={'verbose_name': 'Atto', 'verbose_name_plural': 'Atti'},
        ),
        migrations.AlterModelOptions(
            name='atto_gebevdiritto',
            options={'verbose_name': 'Dipendente - Diritto Generale Delibere', 'verbose_name_plural': 'Dipendenti - Diritti Generali Delibere'},
        ),
        migrations.AlterModelOptions(
            name='atto_gebevripartizione',
            options={'verbose_name': 'Dipendente - Ripartizione Delibere', 'verbose_name_plural': 'Dipendenti - Ripartizioni Delibere'},
        ),
        migrations.AlterModelOptions(
            name='designazione',
            options={'verbose_name': 'Designazione autorizzato', 'verbose_name_plural': 'Designazioni autorizzati'},
        ),
        migrations.AlterModelOptions(
            name='tipogenerico',
            options={'verbose_name': 'Tipo Generico', 'verbose_name_plural': 'Tipi Generici'},
        ),
        migrations.RenameField(
            model_name='share',
            old_name='GruppoSamba',
            new_name='grupposamba',
        ),
        migrations.AlterField(
            model_name='atto',
            name='amministratore',
            field=models.ForeignKey(limit_choices_to={'ruolo__nome': 'Amministratore'}, on_delete=django.db.models.deletion.CASCADE, related_name='atti_amm', to='dipendenti.dipendente', verbose_name='Amministratore di sistema'),
        ),
        migrations.AlterField(
            model_name='atto_d3diritto',
            name='data_disattivazione',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazione'),
        ),
        migrations.AlterField(
            model_name='atto_d3gruppo',
            name='data_disattivazione',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazione'),
        ),
        migrations.AlterField(
            model_name='atto_dirittorete',
            name='data_disattivazione',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazione'),
        ),
        migrations.AlterField(
            model_name='atto_gebevdiritto',
            name='data_disattivazione',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazione'),
        ),
        migrations.AlterField(
            model_name='atto_gebevripartizione',
            name='data_disattivazione',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazione'),
        ),
        migrations.AlterField(
            model_name='atto_generico',
            name='data_disattivazione',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazione'),
        ),
        migrations.AlterField(
            model_name='atto_goffice',
            name='data_disattivazione',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazione'),
        ),
        migrations.AlterField(
            model_name='atto_grupposamba',
            name='data_disattivazione',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazione'),
        ),
        migrations.AlterField(
            model_name='atto_nextcloud',
            name='data_disattivazione',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazione'),
        ),
        migrations.AlterField(
            model_name='atto_o365gruppo',
            name='data_disattivazione',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazione'),
        ),
        migrations.AlterField(
            model_name='atto_porta',
            name='data_disattivazione',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazione'),
        ),
        migrations.AlterField(
            model_name='atto_webapp',
            name='data_disattivazione',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazione'),
        ),
        migrations.AlterField(
            model_name='d3diritto',
            name='tipologia',
            field=models.ForeignKey(limit_choices_to={'gruppo': 'D3'}, on_delete=django.db.models.deletion.CASCADE, to='accessi.tipogenerico', verbose_name='Tipologia di Diritto D3'),
        ),
        migrations.AlterField(
            model_name='designazione',
            name='testo',
            field=models.ForeignKey(limit_choices_to={'tipologia__nome': 'Designazione'}, on_delete=django.db.models.deletion.CASCADE, to='accessi.testofisso', verbose_name='Testo Fisso'),
        ),
        migrations.AlterField(
            model_name='o365gruppo',
            name='tipologia',
            field=models.ForeignKey(limit_choices_to={'gruppo': 'GO'}, on_delete=django.db.models.deletion.CASCADE, to='accessi.tipogenerico', verbose_name='Tipologia di gruppo Office365'),
        ),
        migrations.AlterField(
            model_name='password',
            name='testo',
            field=models.ForeignKey(limit_choices_to={'tipologia__nome': 'Password'}, on_delete=django.db.models.deletion.CASCADE, to='accessi.testofisso', verbose_name='Testo Fisso'),
        ),
    ]
