# Generated by Django 4.0.4 on 2023-03-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessi', '0002_alter_atto_options_alter_atto_gebevdiritto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='d3diritto',
            name='attivo',
            field=models.BooleanField(default=True, verbose_name='diritto non attivo'),
        ),
        migrations.AddField(
            model_name='d3gruppo',
            name='attivo',
            field=models.BooleanField(default=True, verbose_name='diritto non attivo'),
        ),
        migrations.AddField(
            model_name='dirittorete',
            name='attivo',
            field=models.BooleanField(default=True, verbose_name='diritto non attivo'),
        ),
        migrations.AddField(
            model_name='gebevdiritto',
            name='attivo',
            field=models.BooleanField(default=True, verbose_name='diritto non attivo'),
        ),
        migrations.AddField(
            model_name='gebevripartizione',
            name='attivo',
            field=models.BooleanField(default=True, verbose_name='diritto non attivo'),
        ),
        migrations.AddField(
            model_name='generico',
            name='attivo',
            field=models.BooleanField(default=True, verbose_name='diritto non attivo'),
        ),
        migrations.AddField(
            model_name='goffice',
            name='attivo',
            field=models.BooleanField(default=True, verbose_name='diritto non attivo'),
        ),
        migrations.AddField(
            model_name='grupposamba',
            name='attivo',
            field=models.BooleanField(default=True, verbose_name='diritto non attivo'),
        ),
        migrations.AddField(
            model_name='nextcloud',
            name='attivo',
            field=models.BooleanField(default=True, verbose_name='diritto non attivo'),
        ),
        migrations.AddField(
            model_name='o365gruppo',
            name='attivo',
            field=models.BooleanField(default=True, verbose_name='diritto non attivo'),
        ),
        migrations.AddField(
            model_name='porta',
            name='attivo',
            field=models.BooleanField(default=True, verbose_name='diritto non attivo'),
        ),
        migrations.AddField(
            model_name='webapp',
            name='attivo',
            field=models.BooleanField(default=True, verbose_name='diritto non attivo'),
        ),
        migrations.AlterField(
            model_name='share',
            name='percorso',
            field=models.CharField(default='\\user\\document\\', max_length=100, verbose_name='percorso di rete dello share'),
        ),
    ]
