# Generated by Django 4.0.4 on 2023-03-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessi', '0003_d3diritto_attivo_d3gruppo_attivo_dirittorete_attivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d3diritto',
            name='attivo',
            field=models.BooleanField(default=True, verbose_name='diritto attivo'),
        ),
        migrations.AlterField(
            model_name='d3gruppo',
            name='attivo',
            field=models.BooleanField(default=True, verbose_name='diritto attivo'),
        ),
        migrations.AlterField(
            model_name='dirittorete',
            name='attivo',
            field=models.BooleanField(default=True, verbose_name='diritto attivo'),
        ),
        migrations.AlterField(
            model_name='gebevdiritto',
            name='attivo',
            field=models.BooleanField(default=True, verbose_name='diritto attivo'),
        ),
        migrations.AlterField(
            model_name='gebevripartizione',
            name='attivo',
            field=models.BooleanField(default=True, verbose_name='diritto attivo'),
        ),
        migrations.AlterField(
            model_name='generico',
            name='attivo',
            field=models.BooleanField(default=True, verbose_name='diritto attivo'),
        ),
        migrations.AlterField(
            model_name='goffice',
            name='attivo',
            field=models.BooleanField(default=True, verbose_name='diritto attivo'),
        ),
        migrations.AlterField(
            model_name='grupposamba',
            name='attivo',
            field=models.BooleanField(default=True, verbose_name='diritto attivo'),
        ),
        migrations.AlterField(
            model_name='nextcloud',
            name='attivo',
            field=models.BooleanField(default=True, verbose_name='diritto attivo'),
        ),
        migrations.AlterField(
            model_name='o365gruppo',
            name='attivo',
            field=models.BooleanField(default=True, verbose_name='diritto attivo'),
        ),
        migrations.AlterField(
            model_name='porta',
            name='attivo',
            field=models.BooleanField(default=True, verbose_name='diritto attivo'),
        ),
        migrations.AlterField(
            model_name='webapp',
            name='attivo',
            field=models.BooleanField(default=True, verbose_name='diritto attivo'),
        ),
    ]
