# Generated by Django 4.0.4 on 2023-06-06 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accessi', '0005_alter_atto_d3diritto_utente_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atto_d3diritto',
            name='utente_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utente amministratore abilitante'),
        ),
        migrations.AlterField(
            model_name='atto_d3diritto',
            name='utente_disattivazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto'),
        ),
        migrations.AlterField(
            model_name='atto_d3gruppo',
            name='utente_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utente amministratore abilitante'),
        ),
        migrations.AlterField(
            model_name='atto_d3gruppo',
            name='utente_disattivazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto'),
        ),
        migrations.AlterField(
            model_name='atto_dirittorete',
            name='utente_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utente amministratore abilitante'),
        ),
        migrations.AlterField(
            model_name='atto_dirittorete',
            name='utente_disattivazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto'),
        ),
        migrations.AlterField(
            model_name='atto_gebevdiritto',
            name='utente_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utente amministratore abilitante'),
        ),
        migrations.AlterField(
            model_name='atto_gebevdiritto',
            name='utente_disattivazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto'),
        ),
        migrations.AlterField(
            model_name='atto_gebevripartizione',
            name='utente_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utente amministratore abilitante'),
        ),
        migrations.AlterField(
            model_name='atto_gebevripartizione',
            name='utente_disattivazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto'),
        ),
        migrations.AlterField(
            model_name='atto_generico',
            name='utente_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utente amministratore abilitante'),
        ),
        migrations.AlterField(
            model_name='atto_generico',
            name='utente_disattivazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto'),
        ),
        migrations.AlterField(
            model_name='atto_goffice',
            name='utente_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utente amministratore abilitante'),
        ),
        migrations.AlterField(
            model_name='atto_goffice',
            name='utente_disattivazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto'),
        ),
        migrations.AlterField(
            model_name='atto_grupposamba',
            name='utente_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utente amministratore abilitante'),
        ),
        migrations.AlterField(
            model_name='atto_grupposamba',
            name='utente_disattivazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto'),
        ),
        migrations.AlterField(
            model_name='atto_nextcloud',
            name='utente_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utente amministratore abilitante'),
        ),
        migrations.AlterField(
            model_name='atto_nextcloud',
            name='utente_disattivazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto'),
        ),
        migrations.AlterField(
            model_name='atto_o365gruppo',
            name='utente_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utente amministratore abilitante'),
        ),
        migrations.AlterField(
            model_name='atto_o365gruppo',
            name='utente_disattivazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto'),
        ),
        migrations.AlterField(
            model_name='atto_porta',
            name='utente_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utente amministratore abilitante'),
        ),
        migrations.AlterField(
            model_name='atto_porta',
            name='utente_disattivazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto'),
        ),
        migrations.AlterField(
            model_name='atto_webapp',
            name='utente_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utente amministratore abilitante'),
        ),
        migrations.AlterField(
            model_name='atto_webapp',
            name='utente_disattivazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto'),
        ),
    ]
