# Generated by Django 4.0.4 on 2023-06-06 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accessi', '0006_alter_atto_d3diritto_utente_admin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testofisso',
            options={'verbose_name': 'Testo fisso Atto', 'verbose_name_plural': 'Testi fissi Atto'},
        ),
        migrations.AlterField(
            model_name='testofisso',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='nome del testo fisso per atto'),
        ),
        migrations.AlterField(
            model_name='tipogenerico',
            name='gruppo',
            field=models.CharField(choices=[('D3', 'Diritto D3'), ('TX', 'Testo'), ('GE', 'Generico'), ('GO', 'Gruppo Office365'), ('GB', 'Programa delibere'), ('AT', 'Atto'), ('DE', 'Designazione')], max_length=2, verbose_name='Gruppo di tipologie'),
        ),
        migrations.CreateModel(
            name='TestoDesignazione',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=30, verbose_name='nome del testo fisso per designazione')),
                ('testo_fisso_it', models.TextField(verbose_name='Testo fisso italiano')),
                ('testo_fisso_de', models.TextField(verbose_name='Testo fisso tedesco')),
                ('tipologia', models.ForeignKey(limit_choices_to={'gruppo': 'DE'}, on_delete=django.db.models.deletion.CASCADE, to='accessi.tipogenerico', verbose_name='Tipologia di testo fisso')),
            ],
            options={
                'verbose_name': 'Testo fisso Designazione',
                'verbose_name_plural': 'Testi fissi Designazione',
            },
        ),
        migrations.AlterField(
            model_name='designazione',
            name='testo',
            field=models.ForeignKey(limit_choices_to={'tipologia__nome': 'Designazione'}, on_delete=django.db.models.deletion.CASCADE, to='accessi.testodesignazione', verbose_name='Testo Fisso'),
        ),
    ]
