# Generated by Django 4.0.4 on 2023-06-06 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accessi', '0007_alter_testofisso_options_alter_testofisso_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designazione',
            name='testo',
            field=models.ForeignKey(limit_choices_to={'tipologia__nome': 'Designazione'}, on_delete=django.db.models.deletion.CASCADE, to='accessi.testofisso', verbose_name='Testo Fisso'),
        ),
        migrations.DeleteModel(
            name='TestoDesignazione',
        ),
    ]
