# Generated by Django 4.0.4 on 2023-06-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessi', '0008_alter_designazione_testo_delete_testodesignazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='d3diritto',
            name='nome_de',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='d3gruppo',
            name='nome_de',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='dirittorete',
            name='nome_de',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='gebevdiritto',
            name='nome_de',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='gebevripartizione',
            name='nome_de',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='generico',
            name='nome_de',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='goffice',
            name='nome_de',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='grupposamba',
            name='nome_de',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='nextcloud',
            name='nome_de',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='o365gruppo',
            name='nome_de',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='porta',
            name='nome_de',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='webapp',
            name='nome_de',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='d3diritto',
            name='descrizione',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='d3diritto',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='d3gruppo',
            name='descrizione',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='d3gruppo',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='dirittorete',
            name='descrizione',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='dirittorete',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='gebevdiritto',
            name='descrizione',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='gebevdiritto',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='gebevripartizione',
            name='descrizione',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='gebevripartizione',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='generico',
            name='descrizione',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='generico',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='goffice',
            name='descrizione',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='goffice',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='grupposamba',
            name='descrizione',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='grupposamba',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='nextcloud',
            name='descrizione',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='nextcloud',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='o365gruppo',
            name='descrizione',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='o365gruppo',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='porta',
            name='descrizione',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='porta',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='webapp',
            name='descrizione',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='webapp',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome del diritto in italiano'),
        ),
    ]
