# Generated by Django 4.0.4 on 2023-07-27 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accessi', '0009_d3diritto_nome_de_d3gruppo_nome_de_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capoverso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('ordine', models.IntegerField(verbose_name='ordine del capoverso')),
                ('testo_it', models.TextField(verbose_name='Testo italiano')),
                ('testo_de', models.TextField(verbose_name='Testo tedesco')),
                ('testofisso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.testofisso', verbose_name='testo Fisso di riferimento')),
            ],
            options={
                'verbose_name': 'Capoverso testo fisso',
                'verbose_name_plural': 'Capoversi testo fisso',
            },
        ),
    ]
