# Generated by Django 4.0.4 on 2023-07-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessi', '0010_capoverso'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipogenerico',
            name='nome_de',
            field=models.CharField(default='-', max_length=20, verbose_name='Nome del tipo in tedesco'),
        ),
    ]
