# Generated by Django 4.0.4 on 2023-07-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessi', '0011_tipogenerico_nome_de'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d3gruppo',
            name='nome',
            field=models.CharField(max_length=70, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='d3gruppo',
            name='nome_de',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
    ]
