# Generated by Django 4.0.4 on 2023-07-28 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessi', '0012_alter_d3gruppo_nome_alter_d3gruppo_nome_de'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='d3diritto',
            options={'ordering': ['tipologia', 'nome'], 'verbose_name': 'Diritto D3', 'verbose_name_plural': 'Diritti D3'},
        ),
        migrations.AlterModelOptions(
            name='d3gruppo',
            options={'ordering': ['nome'], 'verbose_name': 'Diritto Gruppo D3', 'verbose_name_plural': 'Diritti Gruppi D3'},
        ),
        migrations.AlterModelOptions(
            name='dirittorete',
            options={'ordering': ['nome'], 'verbose_name': 'Diritto di Rete', 'verbose_name_plural': 'Diritti di Rete'},
        ),
        migrations.AlterModelOptions(
            name='gebevdiritto',
            options={'ordering': ['tipologia', 'nome'], 'verbose_name': 'Diritto Programma Delibere', 'verbose_name_plural': 'Diritti Programma Delibere'},
        ),
        migrations.AlterModelOptions(
            name='gebevripartizione',
            options={'ordering': ['nome'], 'verbose_name': 'Ripartizione programa Delibere', 'verbose_name_plural': 'Ripartizioni programa Delibere'},
        ),
        migrations.AlterModelOptions(
            name='generico',
            options={'ordering': ['nome'], 'verbose_name': 'Diritto Generico', 'verbose_name_plural': 'Diritti Generici'},
        ),
        migrations.AlterModelOptions(
            name='goffice',
            options={'ordering': ['nome'], 'verbose_name': 'Diritto GOffice', 'verbose_name_plural': 'Diritti GOffice'},
        ),
        migrations.AlterModelOptions(
            name='grupposamba',
            options={'ordering': ['nome'], 'verbose_name': 'Gruppo Samba', 'verbose_name_plural': 'Gruppi Samba'},
        ),
        migrations.AlterModelOptions(
            name='nextcloud',
            options={'ordering': ['nome'], 'verbose_name': 'Gruppo Nextcloud', 'verbose_name_plural': 'Gruppi Nextcloud'},
        ),
        migrations.AlterModelOptions(
            name='o365gruppo',
            options={'ordering': ['tipologia', 'nome'], 'verbose_name': 'Gruppo Office365', 'verbose_name_plural': 'Gruppi Office365'},
        ),
        migrations.AlterModelOptions(
            name='porta',
            options={'ordering': ['transponder', 'nome'], 'verbose_name': 'Porta', 'verbose_name_plural': 'Porte'},
        ),
        migrations.AlterModelOptions(
            name='webapp',
            options={'ordering': ['nome'], 'verbose_name': 'Diritto WebApp Django', 'verbose_name_plural': 'Diritti WebApp Django'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='atto_d3diritto',
            order_with_respect_to='diritto',
        ),
        migrations.AlterOrderWithRespectTo(
            name='atto_d3gruppo',
            order_with_respect_to='diritto',
        ),
        migrations.AlterOrderWithRespectTo(
            name='atto_dirittorete',
            order_with_respect_to='diritto',
        ),
        migrations.AlterOrderWithRespectTo(
            name='atto_gebevdiritto',
            order_with_respect_to='diritto',
        ),
        migrations.AlterOrderWithRespectTo(
            name='atto_gebevripartizione',
            order_with_respect_to='diritto',
        ),
        migrations.AlterOrderWithRespectTo(
            name='atto_generico',
            order_with_respect_to='diritto',
        ),
        migrations.AlterOrderWithRespectTo(
            name='atto_goffice',
            order_with_respect_to='diritto',
        ),
        migrations.AlterOrderWithRespectTo(
            name='atto_grupposamba',
            order_with_respect_to='diritto',
        ),
        migrations.AlterOrderWithRespectTo(
            name='atto_nextcloud',
            order_with_respect_to='diritto',
        ),
        migrations.AlterOrderWithRespectTo(
            name='atto_o365gruppo',
            order_with_respect_to='diritto',
        ),
        migrations.AlterOrderWithRespectTo(
            name='atto_porta',
            order_with_respect_to='diritto',
        ),
        migrations.AlterOrderWithRespectTo(
            name='atto_webapp',
            order_with_respect_to='diritto',
        ),
    ]
