# Generated by Django 4.0.4 on 2023-07-28 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessi', '0013_alter_d3diritto_options_alter_d3gruppo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atto_d3diritto',
            options={'ordering': ['diritto'], 'verbose_name': 'Dipendente - Diritto D3', 'verbose_name_plural': 'Dipendenti - Diritti D3'},
        ),
        migrations.AlterModelOptions(
            name='atto_d3gruppo',
            options={'ordering': ['diritto'], 'verbose_name': 'Dipendente - Diritto Gruppo D3', 'verbose_name_plural': 'Dipendenti - Diritti Gruppi D3'},
        ),
        migrations.AlterModelOptions(
            name='atto_dirittorete',
            options={'ordering': ['diritto'], 'verbose_name': 'Dipendente - Diritto di Rete', 'verbose_name_plural': 'Dipendenti - Diritti di Rete'},
        ),
        migrations.AlterModelOptions(
            name='atto_gebevdiritto',
            options={'ordering': ['diritto'], 'verbose_name': 'Dipendente - Diritto Generale Delibere', 'verbose_name_plural': 'Dipendenti - Diritti Generali Delibere'},
        ),
        migrations.AlterModelOptions(
            name='atto_gebevripartizione',
            options={'ordering': ['diritto'], 'verbose_name': 'Dipendente - Ripartizione Delibere', 'verbose_name_plural': 'Dipendenti - Ripartizioni Delibere'},
        ),
        migrations.AlterModelOptions(
            name='atto_generico',
            options={'ordering': ['diritto'], 'verbose_name': 'Dipendente - Diritto Gruppo D3', 'verbose_name_plural': 'Dipendenti - Diritti Gruppi D3'},
        ),
        migrations.AlterModelOptions(
            name='atto_goffice',
            options={'ordering': ['diritto'], 'verbose_name': 'Dipendente - Diritto GOffice', 'verbose_name_plural': 'Dipendenti - Diritti GOffice'},
        ),
        migrations.AlterModelOptions(
            name='atto_grupposamba',
            options={'ordering': ['diritto'], 'verbose_name': 'Dipendente - Gruppo Samba', 'verbose_name_plural': 'Dipendenti - Gruppi Samba'},
        ),
        migrations.AlterModelOptions(
            name='atto_nextcloud',
            options={'ordering': ['diritto'], 'verbose_name': 'Dipendente - Gruppo NextCloud', 'verbose_name_plural': 'Dipendenti - Gruppi NextCloud'},
        ),
        migrations.AlterModelOptions(
            name='atto_o365gruppo',
            options={'ordering': ['diritto'], 'verbose_name': 'Dipendente - Gruppo Office 365', 'verbose_name_plural': 'Dipendenti - Gruppi Office 365'},
        ),
        migrations.AlterModelOptions(
            name='atto_porta',
            options={'ordering': ['diritto'], 'verbose_name': 'Dipendente - Porta', 'verbose_name_plural': 'Dipendenti - Porte'},
        ),
        migrations.AlterModelOptions(
            name='atto_webapp',
            options={'ordering': ['diritto'], 'verbose_name': 'Dipendente - Diritto WebApp Django', 'verbose_name_plural': 'Dipendenti - Diritti WebApp Django'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='atto_d3diritto',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='atto_d3gruppo',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='atto_dirittorete',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='atto_gebevdiritto',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='atto_gebevripartizione',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='atto_generico',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='atto_goffice',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='atto_grupposamba',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='atto_nextcloud',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='atto_o365gruppo',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='atto_porta',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='atto_webapp',
            order_with_respect_to=None,
        ),
    ]
