# Generated by Django 4.0.4 on 2023-07-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessi', '0014_alter_atto_d3diritto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atto_generico',
            options={'ordering': ['diritto'], 'verbose_name': 'Dipendente - Diritto Ascot', 'verbose_name_plural': 'Dipendenti - Diritti Ascot'},
        ),
        migrations.AlterField(
            model_name='gebevripartizione',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='gebevripartizione',
            name='nome_de',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
    ]
