# Generated by Django 4.0.4 on 2023-08-08 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accessi', '0015_alter_atto_generico_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atto_Web',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data di inserimento')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica')),
                ('data_disattivazione', models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazione')),
                ('diritto_attivato', models.BooleanField(default=False, verbose_name='Diritto assegnato')),
                ('atto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.atto', verbose_name='Atti')),
            ],
            options={
                'verbose_name': 'Dipendente - Diritto Gestione Pagine Web',
                'verbose_name_plural': 'Dipendenti - Diritti Gestione Pagine Web',
                'ordering': ['diritto'],
            },
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome del diritto in italiano')),
                ('nome_de', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome del diritto in tedesco')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in tedesco')),
                ('attivo', models.BooleanField(default=True, verbose_name='diritto attivo')),
                ('atti', models.ManyToManyField(related_name='web', through='accessi.Atto_Web', to='accessi.atto', verbose_name='Atto di Assegnazione')),
            ],
            options={
                'verbose_name': 'Diritto Pagina Web',
                'verbose_name_plural': 'Diritti Pagine Web',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='atto_web',
            name='diritto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.web', verbose_name='Diritto Pagine Web'),
        ),
        migrations.AddField(
            model_name='atto_web',
            name='tipo',
            field=models.ForeignKey(limit_choices_to={'gruppo': 'WW'}, on_delete=django.db.models.deletion.CASCADE, to='accessi.tipogenerico', verbose_name='Tipologia di diritto'),
        ),
        migrations.AddField(
            model_name='atto_web',
            name='utente_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utente amministratore abilitante'),
        ),
        migrations.AddField(
            model_name='atto_web',
            name='utente_disattivazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto'),
        ),
        migrations.AddField(
            model_name='atto_web',
            name='utente_inserimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di attribuzione diritto'),
        ),
        migrations.AddField(
            model_name='atto_web',
            name='utente_modifica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di modifica diritto'),
        ),
    ]
