# Generated by Django 4.0.4 on 2023-08-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessi', '0016_atto_web_web_atto_web_diritto_atto_web_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipogenerico',
            name='gruppo',
            field=models.CharField(choices=[('D3', 'Diritto D3'), ('TX', 'Testo'), ('GE', 'Generico'), ('GO', 'Gruppo Office365'), ('GB', 'Programa delibere'), ('AT', 'Atto'), ('DE', 'Designazione'), ('WW', 'Gruppo Web')], max_length=2, verbose_name='Gruppo di tipologie'),
        ),
    ]
