# Generated by Django 4.0.4 on 2023-09-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessi', '0017_alter_tipogenerico_gruppo'),
    ]

    operations = [
        migrations.AddField(
            model_name='atto',
            name='data_firma',
            field=models.DateField(blank=True, null=True, verbose_name='Data della sottoscrizione'),
        ),
    ]
