# Generated by Django 4.0.4 on 2023-10-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessi', '0019_atto_sgvcanale_sgvcanale_atto_sgvcanale_diritto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atto_dirittorete',
            name='annotazioni',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Note aggiuntive'),
        ),
        migrations.AddField(
            model_name='atto_web',
            name='utente',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Utente utilizzato'),
        ),
        migrations.AddField(
            model_name='d3diritto',
            name='descrizione_de',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='d3gruppo',
            name='descrizione_de',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='dirittorete',
            name='descrizione_de',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='gebevdiritto',
            name='descrizione_de',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='gebevripartizione',
            name='descrizione_de',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='generico',
            name='descrizione_de',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='goffice',
            name='descrizione_de',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='grupposamba',
            name='descrizione_de',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='nextcloud',
            name='descrizione_de',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='o365gruppo',
            name='descrizione_de',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='porta',
            name='descrizione_de',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='sgvcanale',
            name='descrizione_de',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='web',
            name='descrizione_de',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='webapp',
            name='descrizione_de',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='d3diritto',
            name='descrizione',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='d3gruppo',
            name='descrizione',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='dirittorete',
            name='descrizione',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='gebevdiritto',
            name='descrizione',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='gebevripartizione',
            name='descrizione',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='generico',
            name='descrizione',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='goffice',
            name='descrizione',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='grupposamba',
            name='descrizione',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='nextcloud',
            name='descrizione',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='o365gruppo',
            name='descrizione',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='porta',
            name='descrizione',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='sgvcanale',
            name='descrizione',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='web',
            name='descrizione',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='webapp',
            name='descrizione',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in italiano'),
        ),
    ]
