# Generated by Django 4.2.7 on 2023-12-27 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accessi', '0020_atto_dirittorete_annotazioni_atto_web_utente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupposamba',
            options={'ordering': ['tipologia', 'nome'], 'verbose_name': 'Gruppo Samba', 'verbose_name_plural': 'Gruppi Samba'},
        ),
        migrations.AddField(
            model_name='grupposamba',
            name='tipologia',
            field=models.ForeignKey(blank=True, limit_choices_to={'gruppo': 'SA'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='accessi.tipogenerico', verbose_name='Tipologia di diritto Samba'),
        ),
        migrations.AlterField(
            model_name='d3diritto',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='d3diritto',
            name='nome_de',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='dirittorete',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='dirittorete',
            name='nome_de',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='gebevdiritto',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='gebevdiritto',
            name='nome_de',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='generico',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='generico',
            name='nome_de',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='goffice',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='goffice',
            name='nome_de',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='grupposamba',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='grupposamba',
            name='nome_de',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='nextcloud',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='nextcloud',
            name='nome_de',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='o365gruppo',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='o365gruppo',
            name='nome_de',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='porta',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='porta',
            name='nome_de',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='sgvcanale',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='sgvcanale',
            name='nome_de',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='tipogenerico',
            name='gruppo',
            field=models.CharField(choices=[('D3', 'Diritto D3'), ('TX', 'Testo'), ('GE', 'Generico'), ('GO', 'Gruppo Office365'), ('GB', 'Programa delibere'), ('AT', 'Atto'), ('DE', 'Designazione'), ('WW', 'Gruppo Web'), ('SA', 'Gruppo Samba')], max_length=2, verbose_name='Gruppo di tipologie'),
        ),
        migrations.AlterField(
            model_name='web',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='web',
            name='nome_de',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='webapp',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='webapp',
            name='nome_de',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
    ]
