# Generated by Django 5.0.1 on 2024-03-19 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessi', '0021_alter_grupposamba_options_grupposamba_tipologia_and_more'),
        ('dipendenti', '0045_remove_dipendente_dirigente_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='atto',
            name='dirigente_alt',
            field=models.ForeignKey(blank=True, help_text='Lasciare in bianco per scegliere in automatico il dirigente corretto.', null=True, on_delete=django.db.models.deletion.PROTECT, to='dipendenti.dirigente', verbose_name="Dirigente sostitutivo nell'ambito di trattamento"),
        ),
    ]
