# Generated by Django 5.0.1 on 2024-06-27 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessi', '0022_atto_dirigente_alt'),
        ('dipendenti', '0045_remove_dipendente_dirigente_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atto',
            name='amministratore',
            field=models.ForeignKey(limit_choices_to={'ruolo__ammsistema': True}, on_delete=django.db.models.deletion.CASCADE, related_name='atti_amm', to='dipendenti.dipendente', verbose_name='Amministratore di sistema'),
        ),
    ]
