# Generated by Django 5.0.1 on 2024-10-07 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessi', '0023_alter_atto_amministratore'),
        ('dipendenti', '0045_remove_dipendente_dirigente_alt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atto_d3diritto',
            options={'verbose_name': 'Dipendente - Diritto D3', 'verbose_name_plural': 'Dipendenti - Diritti D3'},
        ),
        migrations.AlterModelOptions(
            name='atto_d3gruppo',
            options={'verbose_name': 'Dipendente - Diritto Gruppo D3', 'verbose_name_plural': 'Dipendenti - Diritti Gruppi D3'},
        ),
        migrations.AlterModelOptions(
            name='atto_dirittorete',
            options={'verbose_name': 'Dipendente - Diritto di Rete', 'verbose_name_plural': 'Dipendenti - Diritti di Rete'},
        ),
        migrations.AlterModelOptions(
            name='atto_gebevdiritto',
            options={'verbose_name': 'Dipendente - Diritto Generale Delibere', 'verbose_name_plural': 'Dipendenti - Diritti Generali Delibere'},
        ),
        migrations.AlterModelOptions(
            name='atto_gebevripartizione',
            options={'verbose_name': 'Dipendente - Ripartizione Delibere', 'verbose_name_plural': 'Dipendenti - Ripartizioni Delibere'},
        ),
        migrations.AlterModelOptions(
            name='atto_generico',
            options={'verbose_name': 'Dipendente - Diritto Ascot', 'verbose_name_plural': 'Dipendenti - Diritti Ascot'},
        ),
        migrations.AlterModelOptions(
            name='atto_goffice',
            options={'verbose_name': 'Dipendente - Diritto GOffice', 'verbose_name_plural': 'Dipendenti - Diritti GOffice'},
        ),
        migrations.AlterModelOptions(
            name='atto_grupposamba',
            options={'verbose_name': 'Dipendente - Gruppo Samba', 'verbose_name_plural': 'Dipendenti - Gruppi Samba'},
        ),
        migrations.AlterModelOptions(
            name='atto_nextcloud',
            options={'verbose_name': 'Dipendente - Gruppo NextCloud', 'verbose_name_plural': 'Dipendenti - Gruppi NextCloud'},
        ),
        migrations.AlterModelOptions(
            name='atto_o365gruppo',
            options={'verbose_name': 'Dipendente - Gruppo Office 365', 'verbose_name_plural': 'Dipendenti - Gruppi Office 365'},
        ),
        migrations.AlterModelOptions(
            name='atto_porta',
            options={'verbose_name': 'Dipendente - Porta', 'verbose_name_plural': 'Dipendenti - Porte'},
        ),
        migrations.AlterModelOptions(
            name='atto_sgvcanale',
            options={'verbose_name': 'Dipendente - Lista Distribuzione SGV', 'verbose_name_plural': 'Dipendenti - Liste Distribuzione SGV'},
        ),
        migrations.AlterModelOptions(
            name='atto_web',
            options={'verbose_name': 'Dipendente - Diritto Gestione Pagine Web', 'verbose_name_plural': 'Dipendenti - Diritti Gestione Pagine Web'},
        ),
        migrations.AlterModelOptions(
            name='atto_webapp',
            options={'verbose_name': 'Dipendente - Diritto WebApp Django', 'verbose_name_plural': 'Dipendenti - Diritti WebApp Django'},
        ),
        migrations.AlterField(
            model_name='atto',
            name='data',
            field=models.DateField(verbose_name="Data di decorrenza della validità dell'atto"),
        ),
        migrations.CreateModel(
            name='Autorizzazione',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data', models.DateField(verbose_name="Data di decorrenza della validità dell'autorizzazione")),
                ('data_firma', models.DateField(blank=True, null=True, verbose_name='Data della sottoscrizione')),
                ('amministratore', models.ForeignKey(limit_choices_to={'ruolo__ammsistema': True}, on_delete=django.db.models.deletion.CASCADE, related_name='autorizzazione_amm', to='dipendenti.dipendente', verbose_name='Amministratore di sistema')),
                ('dirigente_alt', models.ForeignKey(blank=True, help_text='Lasciare in bianco per scegliere in automatico il dirigente corretto.', null=True, on_delete=django.db.models.deletion.PROTECT, to='dipendenti.dirigente', verbose_name="Dirigente sostitutivo nell'ambito di trattamento dell'autorizazione")),
                ('testo', models.ForeignKey(limit_choices_to={'tipologia__nome': 'Autorizzazione'}, on_delete=django.db.models.deletion.CASCADE, to='accessi.testofisso', verbose_name='Testo Fisso')),
                ('ufficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizzazioni', to='dipendenti.ufficio', verbose_name='Ufficio relativo')),
            ],
            options={
                'verbose_name': 'Autorizzazione',
                'verbose_name_plural': 'Autorizzazioni',
            },
        ),
        migrations.CreateModel(
            name='Autorizzazione_Diritto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data di inserimento')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica')),
                ('data_disattivazione', models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazione')),
                ('diritto_attivato', models.BooleanField(default=False, verbose_name='Diritto assegnato')),
                ('autorizzazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.autorizzazione', verbose_name='Autorizzazioni')),
                ('utente_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utente amministratore abilitante')),
                ('utente_disattivazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto')),
                ('utente_inserimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di attribuzione diritto')),
                ('utente_modifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di modifica diritto')),
            ],
            options={
                'verbose_name': 'Entità - Diritto',
                'verbose_name_plural': 'Entità - Diritti',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Autorizzazione_D3Diritto',
            fields=[
                ('autorizzazione_diritto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accessi.autorizzazione_diritto')),
                ('diritto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.d3diritto', verbose_name='Diritto D3')),
            ],
            options={
                'verbose_name': 'Ufficio - Diritto D3',
                'verbose_name_plural': 'Uffici - Diritti D3',
            },
            bases=('accessi.autorizzazione_diritto', models.Model),
        ),
        migrations.AddField(
            model_name='d3diritto',
            name='autorizzazioni',
            field=models.ManyToManyField(related_name='d3diritti', through='accessi.Autorizzazione_D3Diritto', to='accessi.autorizzazione', verbose_name="Autorizzazione d'ufficio"),
        ),
        migrations.CreateModel(
            name='Autorizzazione_D3Gruppo',
            fields=[
                ('autorizzazione_diritto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accessi.autorizzazione_diritto')),
                ('lettura', models.BooleanField(default=False, verbose_name='Lettura documenti')),
                ('scrittura', models.BooleanField(default=False, verbose_name='Modifica documenti')),
                ('lettura_r', models.BooleanField(default=False, verbose_name='Lettura documenti riservati')),
                ('scrittura_r', models.BooleanField(default=False, verbose_name='Modifica documenti riservati')),
                ('posta', models.BooleanField(default=False, verbose_name='Accesso casella postale')),
                ('diritto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.d3gruppo', verbose_name='Diritto di Gruppo D3')),
            ],
            options={
                'verbose_name': 'Ufficio - Diritto Gruppo D3',
                'verbose_name_plural': 'Uffici - Diritti Gruppi D3',
            },
            bases=('accessi.autorizzazione_diritto', models.Model),
        ),
        migrations.AddField(
            model_name='d3gruppo',
            name='autorizzazioni',
            field=models.ManyToManyField(related_name='d3gruppi', through='accessi.Autorizzazione_D3Gruppo', to='accessi.autorizzazione', verbose_name="Autorizzazione d'ufficio"),
        ),
        migrations.CreateModel(
            name='Autorizzazione_DirittoRete',
            fields=[
                ('autorizzazione_diritto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accessi.autorizzazione_diritto')),
                ('annotazioni', models.CharField(blank=True, max_length=50, null=True, verbose_name='Note aggiuntive')),
                ('diritto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.dirittorete', verbose_name='Diritto di Rete')),
            ],
            options={
                'verbose_name': 'Ufficio - Diritto di Rete',
                'verbose_name_plural': 'Uffici - Diritti di Rete',
            },
            bases=('accessi.autorizzazione_diritto', models.Model),
        ),
        migrations.AddField(
            model_name='dirittorete',
            name='autorizzazioni',
            field=models.ManyToManyField(related_name='diritti_rete', through='accessi.Autorizzazione_DirittoRete', to='accessi.autorizzazione', verbose_name="Autorizzazione d'ufficio"),
        ),
        migrations.CreateModel(
            name='Autorizzazione_GebevDiritto',
            fields=[
                ('autorizzazione_diritto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accessi.autorizzazione_diritto')),
                ('diritto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.gebevdiritto', verbose_name='Diritto Generale Programa delibere')),
            ],
            options={
                'verbose_name': 'Ufficio - Diritto Generale Delibere',
                'verbose_name_plural': 'Uffici - Diritti Generali Delibere',
            },
            bases=('accessi.autorizzazione_diritto', models.Model),
        ),
        migrations.AddField(
            model_name='gebevdiritto',
            name='autorizzazioni',
            field=models.ManyToManyField(related_name='gebev_diritti', through='accessi.Autorizzazione_GebevDiritto', to='accessi.autorizzazione', verbose_name="Autorizzazione d'ufficio"),
        ),
        migrations.CreateModel(
            name='Autorizzazione_GebevRipartizione',
            fields=[
                ('autorizzazione_diritto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accessi.autorizzazione_diritto')),
                ('default', models.BooleanField(default=False, verbose_name='Ripartizione di default')),
                ('del_v', models.BooleanField(default=False, verbose_name='Visibilità delibere')),
                ('det_v', models.BooleanField(default=False, verbose_name='Visibilità determinazioni')),
                ('int_v', models.BooleanField(default=False, verbose_name='Visibilità decisioni interne')),
                ('dis_v', models.BooleanField(default=False, verbose_name='Visibilità disposizioni')),
                ('pri_v', models.BooleanField(default=False, verbose_name='Visibilità privacy')),
                ('del_pt', models.BooleanField(default=False, verbose_name='Parere tecnico delibere')),
                ('del_pc', models.BooleanField(default=False, verbose_name='Parere contabile delibere')),
                ('det_pt', models.BooleanField(default=False, verbose_name='Parere tecnico determinazioni')),
                ('det_pc', models.BooleanField(default=False, verbose_name='Parere contabile determinazioni')),
                ('int_p', models.BooleanField(default=False, verbose_name='Parere decisioni interne')),
                ('diritto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.gebevripartizione', verbose_name='Diritto di Gruppo Programma delibere')),
            ],
            options={
                'verbose_name': 'Ufficio - Ripartizione Delibere',
                'verbose_name_plural': 'Uffici - Ripartizioni Delibere',
            },
            bases=('accessi.autorizzazione_diritto', models.Model),
        ),
        migrations.AddField(
            model_name='gebevripartizione',
            name='autorizzazioni',
            field=models.ManyToManyField(related_name='gebev_ripartizioni', through='accessi.Autorizzazione_GebevRipartizione', to='accessi.autorizzazione', verbose_name="Autorizzazione d'ufficio"),
        ),
        migrations.CreateModel(
            name='Autorizzazione_Generico',
            fields=[
                ('autorizzazione_diritto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accessi.autorizzazione_diritto')),
                ('diritto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.generico', verbose_name='Sottosistema Ascot')),
                ('tipo', models.ForeignKey(limit_choices_to={'gruppo': 'GE'}, on_delete=django.db.models.deletion.CASCADE, to='accessi.tipogenerico', verbose_name='Tipologia di diritto')),
            ],
            options={
                'verbose_name': 'Ufficio - Diritto Ascot',
                'verbose_name_plural': 'Ufficio - Diritti Ascot',
            },
            bases=('accessi.autorizzazione_diritto', models.Model),
        ),
        migrations.AddField(
            model_name='generico',
            name='autorizzazioni',
            field=models.ManyToManyField(related_name='generici', through='accessi.Autorizzazione_Generico', to='accessi.autorizzazione', verbose_name="Autorizzazione d'ufficio"),
        ),
        migrations.CreateModel(
            name='Autorizzazione_GOffice',
            fields=[
                ('autorizzazione_diritto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accessi.autorizzazione_diritto')),
                ('diritto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.goffice', verbose_name='Diritto GOffice')),
            ],
            options={
                'verbose_name': 'Ufficio - Diritto GOffice',
                'verbose_name_plural': 'Uffici - Diritti GOffice',
            },
            bases=('accessi.autorizzazione_diritto', models.Model),
        ),
        migrations.AddField(
            model_name='goffice',
            name='autorizzazioni',
            field=models.ManyToManyField(related_name='goffice', through='accessi.Autorizzazione_GOffice', to='accessi.autorizzazione', verbose_name="Autorizzazione d'ufficio"),
        ),
        migrations.CreateModel(
            name='Autorizzazione_GruppoSamba',
            fields=[
                ('autorizzazione_diritto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accessi.autorizzazione_diritto')),
                ('diritto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.grupposamba', verbose_name='Gruppo Samba')),
            ],
            options={
                'verbose_name': 'Ufficio - Gruppo Samba',
                'verbose_name_plural': 'Uffici - Gruppi Samba',
            },
            bases=('accessi.autorizzazione_diritto', models.Model),
        ),
        migrations.AddField(
            model_name='grupposamba',
            name='autorizzazioni',
            field=models.ManyToManyField(related_name='gruppi_samba', through='accessi.Autorizzazione_GruppoSamba', to='accessi.autorizzazione', verbose_name="Autorizzazione d'ufficio"),
        ),
        migrations.CreateModel(
            name='Autorizzazione_NextCloud',
            fields=[
                ('autorizzazione_diritto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accessi.autorizzazione_diritto')),
                ('diritto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.nextcloud', verbose_name='Gruppo NextCloud')),
                ('tipo', models.ForeignKey(limit_choices_to={'gruppo': 'GE'}, on_delete=django.db.models.deletion.CASCADE, to='accessi.tipogenerico', verbose_name='Tipologia di diritto')),
            ],
            options={
                'verbose_name': 'Ufficio - Gruppo NextCloud',
                'verbose_name_plural': 'Uffici - Gruppi NextCloud',
            },
            bases=('accessi.autorizzazione_diritto', models.Model),
        ),
        migrations.AddField(
            model_name='nextcloud',
            name='autorizzazioni',
            field=models.ManyToManyField(related_name='nextcloud', through='accessi.Autorizzazione_NextCloud', to='accessi.autorizzazione', verbose_name="Autorizzazione d'ufficio"),
        ),
        migrations.CreateModel(
            name='Autorizzazione_O365Gruppo',
            fields=[
                ('autorizzazione_diritto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accessi.autorizzazione_diritto')),
                ('diritto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.o365gruppo', verbose_name='Gruppo Office 365')),
            ],
            options={
                'verbose_name': 'Ufficio - Gruppo Office 365',
                'verbose_name_plural': 'Uffici - Gruppi Office 365',
            },
            bases=('accessi.autorizzazione_diritto', models.Model),
        ),
        migrations.AddField(
            model_name='o365gruppo',
            name='autorizzazioni',
            field=models.ManyToManyField(related_name='o365gruppi', through='accessi.Autorizzazione_O365Gruppo', to='accessi.autorizzazione', verbose_name="Autorizzazione d'ufficio"),
        ),
        migrations.CreateModel(
            name='Autorizzazione_Porta',
            fields=[
                ('autorizzazione_diritto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accessi.autorizzazione_diritto')),
                ('diritto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.porta', verbose_name='Porta')),
            ],
            options={
                'verbose_name': 'Ufficio - Porta',
                'verbose_name_plural': 'Uffici - Porte',
            },
            bases=('accessi.autorizzazione_diritto', models.Model),
        ),
        migrations.AddField(
            model_name='porta',
            name='autorizzazioni',
            field=models.ManyToManyField(related_name='porta', through='accessi.Autorizzazione_Porta', to='accessi.autorizzazione', verbose_name="Autorizzazione d'ufficio"),
        ),
        migrations.CreateModel(
            name='Autorizzazione_SGVCanale',
            fields=[
                ('autorizzazione_diritto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accessi.autorizzazione_diritto')),
                ('diritto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.sgvcanale', verbose_name='Lista Distribuzione SGV')),
            ],
            options={
                'verbose_name': 'Ufficio - Lista Distribuzione SGV',
                'verbose_name_plural': 'Uffici - Liste Distribuzione SGV',
            },
            bases=('accessi.autorizzazione_diritto', models.Model),
        ),
        migrations.AddField(
            model_name='sgvcanale',
            name='autorizzazioni',
            field=models.ManyToManyField(related_name='sgvcanale', through='accessi.Autorizzazione_SGVCanale', to='accessi.autorizzazione', verbose_name="Autorizzazione d'ufficio"),
        ),
        migrations.CreateModel(
            name='Autorizzazione_Web',
            fields=[
                ('autorizzazione_diritto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accessi.autorizzazione_diritto')),
                ('utente', models.CharField(blank=True, max_length=70, null=True, verbose_name='Utente utilizzato')),
                ('diritto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.web', verbose_name='Diritto Pagine Web')),
                ('tipo', models.ForeignKey(limit_choices_to={'gruppo': 'WW'}, on_delete=django.db.models.deletion.CASCADE, to='accessi.tipogenerico', verbose_name='Tipologia di diritto')),
            ],
            options={
                'verbose_name': 'Ufficio - Diritto Gestione Pagine Web',
                'verbose_name_plural': 'Uffici - Diritti Gestione Pagine Web',
            },
            bases=('accessi.autorizzazione_diritto', models.Model),
        ),
        migrations.AddField(
            model_name='web',
            name='autorizzazioni',
            field=models.ManyToManyField(related_name='web', through='accessi.Autorizzazione_Web', to='accessi.autorizzazione', verbose_name="Autorizzazione d'ufficio"),
        ),
        migrations.CreateModel(
            name='Autorizzazione_WebApp',
            fields=[
                ('autorizzazione_diritto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accessi.autorizzazione_diritto')),
                ('diritto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.webapp', verbose_name='Diritto WebApp Django')),
            ],
            options={
                'verbose_name': 'Ufficio - Diritto WebApp Django',
                'verbose_name_plural': 'Uffici - Diritti WebApp Django',
            },
            bases=('accessi.autorizzazione_diritto', models.Model),
        ),
        migrations.AddField(
            model_name='webapp',
            name='autorizzazioni',
            field=models.ManyToManyField(related_name='django', through='accessi.Autorizzazione_WebApp', to='accessi.autorizzazione', verbose_name="Autorizzazione d'ufficio"),
        ),
    ]
