# Generated by Django 5.0.1 on 2024-12-02 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessi', '0024_alter_atto_d3diritto_options_and_more'),
        ('dipendenti', '0046_mail_dipendente_citta_dipendente_data_nascita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizzazione',
            name='dirigente_alt',
            field=models.ForeignKey(blank=True, help_text='Lasciare in bianco per scegliere in automatico il dirigente corretto.', null=True, on_delete=django.db.models.deletion.PROTECT, to='dipendenti.dirigente', verbose_name="Dirigente sostitutivo nell'ambito di trattamento dell'autorizzazione"),
        ),
    ]
