# Generated by Django 5.0.1 on 2025-01-23 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessi', '0025_alter_autorizzazione_dirigente_alt'),
        ('dipendenti', '0076_servizio_cdc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d3diritto',
            name='autorizzazioni',
        ),
        migrations.RemoveField(
            model_name='autorizzazione_d3gruppo',
            name='autorizzazione_diritto_ptr',
        ),
        migrations.RemoveField(
            model_name='autorizzazione_d3gruppo',
            name='diritto',
        ),
        migrations.RemoveField(
            model_name='d3gruppo',
            name='autorizzazioni',
        ),
        migrations.RemoveField(
            model_name='autorizzazione_diritto',
            name='autorizzazione',
        ),
        migrations.RemoveField(
            model_name='autorizzazione_diritto',
            name='utente_admin',
        ),
        migrations.RemoveField(
            model_name='autorizzazione_diritto',
            name='utente_disattivazione',
        ),
        migrations.RemoveField(
            model_name='autorizzazione_diritto',
            name='utente_inserimento',
        ),
        migrations.RemoveField(
            model_name='autorizzazione_diritto',
            name='utente_modifica',
        ),
        migrations.RemoveField(
            model_name='autorizzazione_goffice',
            name='autorizzazione_diritto_ptr',
        ),
        migrations.RemoveField(
            model_name='autorizzazione_grupposamba',
            name='autorizzazione_diritto_ptr',
        ),
        migrations.RemoveField(
            model_name='autorizzazione_gebevripartizione',
            name='autorizzazione_diritto_ptr',
        ),
        migrations.RemoveField(
            model_name='autorizzazione_dirittorete',
            name='autorizzazione_diritto_ptr',
        ),
        migrations.RemoveField(
            model_name='autorizzazione_generico',
            name='autorizzazione_diritto_ptr',
        ),
        migrations.RemoveField(
            model_name='autorizzazione_sgvcanale',
            name='autorizzazione_diritto_ptr',
        ),
        migrations.RemoveField(
            model_name='autorizzazione_porta',
            name='autorizzazione_diritto_ptr',
        ),
        migrations.RemoveField(
            model_name='autorizzazione_o365gruppo',
            name='autorizzazione_diritto_ptr',
        ),
        migrations.RemoveField(
            model_name='autorizzazione_gebevdiritto',
            name='autorizzazione_diritto_ptr',
        ),
        migrations.RemoveField(
            model_name='autorizzazione_nextcloud',
            name='autorizzazione_diritto_ptr',
        ),
        migrations.RemoveField(
            model_name='autorizzazione_web',
            name='autorizzazione_diritto_ptr',
        ),
        migrations.RemoveField(
            model_name='autorizzazione_webapp',
            name='autorizzazione_diritto_ptr',
        ),
        migrations.RemoveField(
            model_name='autorizzazione_dirittorete',
            name='diritto',
        ),
        migrations.RemoveField(
            model_name='dirittorete',
            name='autorizzazioni',
        ),
        migrations.RemoveField(
            model_name='autorizzazione_gebevdiritto',
            name='diritto',
        ),
        migrations.RemoveField(
            model_name='gebevdiritto',
            name='autorizzazioni',
        ),
        migrations.RemoveField(
            model_name='autorizzazione_gebevripartizione',
            name='diritto',
        ),
        migrations.RemoveField(
            model_name='gebevripartizione',
            name='autorizzazioni',
        ),
        migrations.RemoveField(
            model_name='autorizzazione_generico',
            name='diritto',
        ),
        migrations.RemoveField(
            model_name='autorizzazione_generico',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='generico',
            name='autorizzazioni',
        ),
        migrations.RemoveField(
            model_name='autorizzazione_goffice',
            name='diritto',
        ),
        migrations.RemoveField(
            model_name='goffice',
            name='autorizzazioni',
        ),
        migrations.RemoveField(
            model_name='autorizzazione_grupposamba',
            name='diritto',
        ),
        migrations.RemoveField(
            model_name='grupposamba',
            name='autorizzazioni',
        ),
        migrations.RemoveField(
            model_name='autorizzazione_nextcloud',
            name='diritto',
        ),
        migrations.RemoveField(
            model_name='autorizzazione_nextcloud',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='nextcloud',
            name='autorizzazioni',
        ),
        migrations.RemoveField(
            model_name='autorizzazione_o365gruppo',
            name='diritto',
        ),
        migrations.RemoveField(
            model_name='o365gruppo',
            name='autorizzazioni',
        ),
        migrations.RemoveField(
            model_name='autorizzazione_porta',
            name='diritto',
        ),
        migrations.RemoveField(
            model_name='porta',
            name='autorizzazioni',
        ),
        migrations.RemoveField(
            model_name='autorizzazione_sgvcanale',
            name='diritto',
        ),
        migrations.RemoveField(
            model_name='sgvcanale',
            name='autorizzazioni',
        ),
        migrations.RemoveField(
            model_name='autorizzazione_web',
            name='diritto',
        ),
        migrations.RemoveField(
            model_name='autorizzazione_web',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='web',
            name='autorizzazioni',
        ),
        migrations.RemoveField(
            model_name='autorizzazione_webapp',
            name='diritto',
        ),
        migrations.RemoveField(
            model_name='webapp',
            name='autorizzazioni',
        ),
        migrations.AlterField(
            model_name='porta',
            name='atti',
            field=models.ManyToManyField(related_name='porte', through='accessi.Atto_Porta', to='accessi.atto', verbose_name='Atto di Assegnazione'),
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data', models.DateField(verbose_name='Data di decorrenza della validità del template')),
                ('data_firma', models.DateField(blank=True, null=True, verbose_name='Data della sottoscrizione')),
                ('nome', models.CharField(max_length=20, verbose_name='nome del template')),
                ('amministratore', models.ForeignKey(limit_choices_to={'ruolo__ammsistema': True}, on_delete=django.db.models.deletion.CASCADE, related_name='template_amm', to='dipendenti.dipendente', verbose_name='Amministratore di sistema')),
                ('autorizzazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='accessi.autorizzazione', verbose_name='Autorizzazione gerarchica soprastante')),
                ('dirigente_alt', models.ForeignKey(blank=True, help_text='Lasciare in bianco per scegliere in automatico il dirigente corretto.', null=True, on_delete=django.db.models.deletion.PROTECT, to='dipendenti.dirigente', verbose_name="Dirigente sostitutivo nell'ambito di trattamento dell'autorizzazione")),
                ('testo', models.ForeignKey(limit_choices_to={'tipologia__nome': 'Template'}, on_delete=django.db.models.deletion.CASCADE, to='accessi.testofisso', verbose_name='Testo Fisso')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
            },
        ),
        migrations.CreateModel(
            name='Template_D3Diritto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data di inserimento')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica')),
                ('data_disattivazione', models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazione')),
                ('diritto_attivato', models.BooleanField(default=False, verbose_name='Diritto assegnato')),
                ('diritto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.d3diritto', verbose_name='Diritto D3')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.template', verbose_name='Templates')),
                ('utente_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utente amministratore abilitante')),
                ('utente_disattivazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto')),
                ('utente_inserimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di attribuzione diritto')),
                ('utente_modifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di modifica diritto')),
            ],
            options={
                'verbose_name': 'Template - Diritto D3',
                'verbose_name_plural': 'Templates - Diritti D3',
            },
        ),
        migrations.AddField(
            model_name='d3diritto',
            name='templates',
            field=models.ManyToManyField(related_name='d3diritti', through='accessi.Template_D3Diritto', to='accessi.template', verbose_name='Template precostruito'),
        ),
        migrations.CreateModel(
            name='Template_D3Gruppo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data di inserimento')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica')),
                ('data_disattivazione', models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazione')),
                ('diritto_attivato', models.BooleanField(default=False, verbose_name='Diritto assegnato')),
                ('lettura', models.BooleanField(default=False, verbose_name='Lettura documenti')),
                ('scrittura', models.BooleanField(default=False, verbose_name='Modifica documenti')),
                ('lettura_r', models.BooleanField(default=False, verbose_name='Lettura documenti riservati')),
                ('scrittura_r', models.BooleanField(default=False, verbose_name='Modifica documenti riservati')),
                ('posta', models.BooleanField(default=False, verbose_name='Accesso casella postale')),
                ('diritto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.d3gruppo', verbose_name='Diritto di Gruppo D3')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.template', verbose_name='Templates')),
                ('utente_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utente amministratore abilitante')),
                ('utente_disattivazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto')),
                ('utente_inserimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di attribuzione diritto')),
                ('utente_modifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di modifica diritto')),
            ],
            options={
                'verbose_name': 'Template - Diritto Gruppo D3',
                'verbose_name_plural': 'Templates - Diritti Gruppi D3',
            },
        ),
        migrations.AddField(
            model_name='d3gruppo',
            name='templates',
            field=models.ManyToManyField(related_name='d3gruppi', through='accessi.Template_D3Gruppo', to='accessi.template', verbose_name='Template precostruito'),
        ),
        migrations.CreateModel(
            name='Template_DirittoRete',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data di inserimento')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica')),
                ('data_disattivazione', models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazione')),
                ('diritto_attivato', models.BooleanField(default=False, verbose_name='Diritto assegnato')),
                ('annotazioni', models.CharField(blank=True, max_length=50, null=True, verbose_name='Note aggiuntive')),
                ('diritto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.dirittorete', verbose_name='Diritto di Rete')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.template', verbose_name='Templates')),
                ('utente_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utente amministratore abilitante')),
                ('utente_disattivazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto')),
                ('utente_inserimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di attribuzione diritto')),
                ('utente_modifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di modifica diritto')),
            ],
            options={
                'verbose_name': 'Template - Diritto di Rete',
                'verbose_name_plural': 'Templates - Diritti di Rete',
            },
        ),
        migrations.AddField(
            model_name='dirittorete',
            name='templates',
            field=models.ManyToManyField(related_name='diritti_rete', through='accessi.Template_DirittoRete', to='accessi.template', verbose_name='Template precostruito'),
        ),
        migrations.CreateModel(
            name='Template_GebevDiritto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data di inserimento')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica')),
                ('data_disattivazione', models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazione')),
                ('diritto_attivato', models.BooleanField(default=False, verbose_name='Diritto assegnato')),
                ('diritto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.gebevdiritto', verbose_name='Diritto Generale Programa delibere')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.template', verbose_name='Templates')),
                ('utente_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utente amministratore abilitante')),
                ('utente_disattivazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto')),
                ('utente_inserimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di attribuzione diritto')),
                ('utente_modifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di modifica diritto')),
            ],
            options={
                'verbose_name': 'Template - Diritto Generale Delibere',
                'verbose_name_plural': 'Templates - Diritti Generali Delibere',
            },
        ),
        migrations.AddField(
            model_name='gebevdiritto',
            name='templates',
            field=models.ManyToManyField(related_name='gebev_diritti', through='accessi.Template_GebevDiritto', to='accessi.template', verbose_name='Template precostruito'),
        ),
        migrations.CreateModel(
            name='Template_GebevRipartizione',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data di inserimento')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica')),
                ('data_disattivazione', models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazione')),
                ('diritto_attivato', models.BooleanField(default=False, verbose_name='Diritto assegnato')),
                ('default', models.BooleanField(default=False, verbose_name='Ripartizione di default')),
                ('del_v', models.BooleanField(default=False, verbose_name='Visibilità delibere')),
                ('det_v', models.BooleanField(default=False, verbose_name='Visibilità determinazioni')),
                ('int_v', models.BooleanField(default=False, verbose_name='Visibilità decisioni interne')),
                ('dis_v', models.BooleanField(default=False, verbose_name='Visibilità disposizioni')),
                ('pri_v', models.BooleanField(default=False, verbose_name='Visibilità privacy')),
                ('del_pt', models.BooleanField(default=False, verbose_name='Parere tecnico delibere')),
                ('del_pc', models.BooleanField(default=False, verbose_name='Parere contabile delibere')),
                ('det_pt', models.BooleanField(default=False, verbose_name='Parere tecnico determinazioni')),
                ('det_pc', models.BooleanField(default=False, verbose_name='Parere contabile determinazioni')),
                ('int_p', models.BooleanField(default=False, verbose_name='Parere decisioni interne')),
                ('diritto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.gebevripartizione', verbose_name='Diritto di Gruppo Programma delibere')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.template', verbose_name='Templates')),
                ('utente_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utente amministratore abilitante')),
                ('utente_disattivazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto')),
                ('utente_inserimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di attribuzione diritto')),
                ('utente_modifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di modifica diritto')),
            ],
            options={
                'verbose_name': 'Template - Ripartizione Delibere',
                'verbose_name_plural': 'Templates - Ripartizioni Delibere',
            },
        ),
        migrations.AddField(
            model_name='gebevripartizione',
            name='templates',
            field=models.ManyToManyField(related_name='gebev_ripartizioni', through='accessi.Template_GebevRipartizione', to='accessi.template', verbose_name='Template precostruito'),
        ),
        migrations.CreateModel(
            name='Template_Generico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data di inserimento')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica')),
                ('data_disattivazione', models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazione')),
                ('diritto_attivato', models.BooleanField(default=False, verbose_name='Diritto assegnato')),
                ('diritto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.generico', verbose_name='Sottosistema Ascot')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.template', verbose_name='Templates')),
                ('tipo', models.ForeignKey(limit_choices_to={'gruppo': 'GE'}, on_delete=django.db.models.deletion.CASCADE, to='accessi.tipogenerico', verbose_name='Tipologia di diritto')),
                ('utente_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utente amministratore abilitante')),
                ('utente_disattivazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto')),
                ('utente_inserimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di attribuzione diritto')),
                ('utente_modifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di modifica diritto')),
            ],
            options={
                'verbose_name': 'Template - Diritto Ascot',
                'verbose_name_plural': 'Templates - Diritti Ascot',
            },
        ),
        migrations.AddField(
            model_name='generico',
            name='templates',
            field=models.ManyToManyField(related_name='generici', through='accessi.Template_Generico', to='accessi.template', verbose_name='Template precostruito'),
        ),
        migrations.CreateModel(
            name='Template_GOffice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data di inserimento')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica')),
                ('data_disattivazione', models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazione')),
                ('diritto_attivato', models.BooleanField(default=False, verbose_name='Diritto assegnato')),
                ('diritto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.goffice', verbose_name='Diritto GOffice')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.template', verbose_name='Templates')),
                ('utente_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utente amministratore abilitante')),
                ('utente_disattivazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto')),
                ('utente_inserimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di attribuzione diritto')),
                ('utente_modifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di modifica diritto')),
            ],
            options={
                'verbose_name': 'Template - Diritto GOffice',
                'verbose_name_plural': 'Templates - Diritti GOffice',
            },
        ),
        migrations.AddField(
            model_name='goffice',
            name='templates',
            field=models.ManyToManyField(related_name='goffice', through='accessi.Template_GOffice', to='accessi.template', verbose_name='Template precostruito'),
        ),
        migrations.CreateModel(
            name='Template_GruppoSamba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data di inserimento')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica')),
                ('data_disattivazione', models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazione')),
                ('diritto_attivato', models.BooleanField(default=False, verbose_name='Diritto assegnato')),
                ('diritto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.grupposamba', verbose_name='Gruppo Samba')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.template', verbose_name='Templates')),
                ('utente_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utente amministratore abilitante')),
                ('utente_disattivazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto')),
                ('utente_inserimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di attribuzione diritto')),
                ('utente_modifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di modifica diritto')),
            ],
            options={
                'verbose_name': 'Template - Gruppo Samba',
                'verbose_name_plural': 'Templates - Gruppi Samba',
            },
        ),
        migrations.AddField(
            model_name='grupposamba',
            name='templates',
            field=models.ManyToManyField(related_name='gruppi_samba', through='accessi.Template_GruppoSamba', to='accessi.template', verbose_name='Template precostruito'),
        ),
        migrations.CreateModel(
            name='Template_NextCloud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data di inserimento')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica')),
                ('data_disattivazione', models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazione')),
                ('diritto_attivato', models.BooleanField(default=False, verbose_name='Diritto assegnato')),
                ('diritto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.nextcloud', verbose_name='Gruppo NextCloud')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.template', verbose_name='Templates')),
                ('tipo', models.ForeignKey(limit_choices_to={'gruppo': 'GE'}, on_delete=django.db.models.deletion.CASCADE, to='accessi.tipogenerico', verbose_name='Tipologia di diritto')),
                ('utente_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utente amministratore abilitante')),
                ('utente_disattivazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto')),
                ('utente_inserimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di attribuzione diritto')),
                ('utente_modifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di modifica diritto')),
            ],
            options={
                'verbose_name': 'Template - Gruppo NextCloud',
                'verbose_name_plural': 'Templates - Gruppi NextCloud',
            },
        ),
        migrations.AddField(
            model_name='nextcloud',
            name='templates',
            field=models.ManyToManyField(related_name='nextcloud', through='accessi.Template_NextCloud', to='accessi.template', verbose_name='Template precostruito'),
        ),
        migrations.CreateModel(
            name='Template_O365Gruppo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data di inserimento')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica')),
                ('data_disattivazione', models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazione')),
                ('diritto_attivato', models.BooleanField(default=False, verbose_name='Diritto assegnato')),
                ('diritto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.o365gruppo', verbose_name='Gruppo Office 365')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.template', verbose_name='Templates')),
                ('utente_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utente amministratore abilitante')),
                ('utente_disattivazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto')),
                ('utente_inserimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di attribuzione diritto')),
                ('utente_modifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di modifica diritto')),
            ],
            options={
                'verbose_name': 'Template - Gruppo Office 365',
                'verbose_name_plural': 'Templates - Gruppi Office 365',
            },
        ),
        migrations.AddField(
            model_name='o365gruppo',
            name='templates',
            field=models.ManyToManyField(related_name='o365gruppi', through='accessi.Template_O365Gruppo', to='accessi.template', verbose_name='Template precostruito'),
        ),
        migrations.CreateModel(
            name='Template_Porta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data di inserimento')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica')),
                ('data_disattivazione', models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazione')),
                ('diritto_attivato', models.BooleanField(default=False, verbose_name='Diritto assegnato')),
                ('diritto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.porta', verbose_name='Porta')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.template', verbose_name='Templates')),
                ('utente_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utente amministratore abilitante')),
                ('utente_disattivazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto')),
                ('utente_inserimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di attribuzione diritto')),
                ('utente_modifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di modifica diritto')),
            ],
            options={
                'verbose_name': 'Template - Porta',
                'verbose_name_plural': 'Templates - Porte',
            },
        ),
        migrations.AddField(
            model_name='porta',
            name='templates',
            field=models.ManyToManyField(related_name='porte', through='accessi.Template_Porta', to='accessi.template', verbose_name='Template precostruito'),
        ),
        migrations.CreateModel(
            name='Template_SGVCanale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data di inserimento')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica')),
                ('data_disattivazione', models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazione')),
                ('diritto_attivato', models.BooleanField(default=False, verbose_name='Diritto assegnato')),
                ('diritto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.sgvcanale', verbose_name='Lista Distribuzione SGV')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.template', verbose_name='Templates')),
                ('utente_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utente amministratore abilitante')),
                ('utente_disattivazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto')),
                ('utente_inserimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di attribuzione diritto')),
                ('utente_modifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di modifica diritto')),
            ],
            options={
                'verbose_name': 'Template - Lista Distribuzione SGV',
                'verbose_name_plural': 'Templates - Liste Distribuzione SGV',
            },
        ),
        migrations.AddField(
            model_name='sgvcanale',
            name='templates',
            field=models.ManyToManyField(related_name='sgvcanale', through='accessi.Template_SGVCanale', to='accessi.template', verbose_name='Template precostruito'),
        ),
        migrations.CreateModel(
            name='Template_Web',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data di inserimento')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica')),
                ('data_disattivazione', models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazione')),
                ('diritto_attivato', models.BooleanField(default=False, verbose_name='Diritto assegnato')),
                ('utente', models.CharField(blank=True, max_length=70, null=True, verbose_name='Utente utilizzato')),
                ('diritto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.web', verbose_name='Diritto Pagine Web')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.template', verbose_name='Templates')),
                ('tipo', models.ForeignKey(limit_choices_to={'gruppo': 'WW'}, on_delete=django.db.models.deletion.CASCADE, to='accessi.tipogenerico', verbose_name='Tipologia di diritto')),
                ('utente_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utente amministratore abilitante')),
                ('utente_disattivazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto')),
                ('utente_inserimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di attribuzione diritto')),
                ('utente_modifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di modifica diritto')),
            ],
            options={
                'verbose_name': 'Template - Diritto Gestione Pagine Web',
                'verbose_name_plural': 'Templates - Diritti Gestione Pagine Web',
            },
        ),
        migrations.AddField(
            model_name='web',
            name='templates',
            field=models.ManyToManyField(related_name='web', through='accessi.Template_Web', to='accessi.template', verbose_name='Template precostruito'),
        ),
        migrations.CreateModel(
            name='Template_WebApp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data di inserimento')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica')),
                ('data_disattivazione', models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazione')),
                ('diritto_attivato', models.BooleanField(default=False, verbose_name='Diritto assegnato')),
                ('diritto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.webapp', verbose_name='Diritto WebApp Django')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.template', verbose_name='Templates')),
                ('utente_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utente amministratore abilitante')),
                ('utente_disattivazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto')),
                ('utente_inserimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di attribuzione diritto')),
                ('utente_modifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di modifica diritto')),
            ],
            options={
                'verbose_name': 'Template - Diritto WebApp Django',
                'verbose_name_plural': 'Templates - Diritti WebApp Django',
            },
        ),
        migrations.AddField(
            model_name='webapp',
            name='templates',
            field=models.ManyToManyField(related_name='django', through='accessi.Template_WebApp', to='accessi.template', verbose_name='Template precostruito'),
        ),
        migrations.DeleteModel(
            name='Autorizzazione_D3Diritto',
        ),
        migrations.DeleteModel(
            name='Autorizzazione_D3Gruppo',
        ),
        migrations.DeleteModel(
            name='Autorizzazione_Diritto',
        ),
        migrations.DeleteModel(
            name='Autorizzazione_DirittoRete',
        ),
        migrations.DeleteModel(
            name='Autorizzazione_GebevDiritto',
        ),
        migrations.DeleteModel(
            name='Autorizzazione_GebevRipartizione',
        ),
        migrations.DeleteModel(
            name='Autorizzazione_Generico',
        ),
        migrations.DeleteModel(
            name='Autorizzazione_GOffice',
        ),
        migrations.DeleteModel(
            name='Autorizzazione_GruppoSamba',
        ),
        migrations.DeleteModel(
            name='Autorizzazione_NextCloud',
        ),
        migrations.DeleteModel(
            name='Autorizzazione_O365Gruppo',
        ),
        migrations.DeleteModel(
            name='Autorizzazione_Porta',
        ),
        migrations.DeleteModel(
            name='Autorizzazione_SGVCanale',
        ),
        migrations.DeleteModel(
            name='Autorizzazione_Web',
        ),
        migrations.DeleteModel(
            name='Autorizzazione_WebApp',
        ),
    ]
