# Generated by Django 5.0.1 on 2025-01-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessi', '0027_autorizzazione_d3diritto_d3diritto_autorizzazioni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atto_d3gruppo',
            name='lettura',
            field=models.BooleanField(default=True, verbose_name='Lettura documenti'),
        ),
        migrations.AlterField(
            model_name='atto_d3gruppo',
            name='posta',
            field=models.BooleanField(default=True, verbose_name='Accesso casella postale'),
        ),
        migrations.AlterField(
            model_name='atto_d3gruppo',
            name='scrittura',
            field=models.BooleanField(default=True, verbose_name='Modifica documenti'),
        ),
        migrations.AlterField(
            model_name='atto_gebevripartizione',
            name='del_v',
            field=models.BooleanField(default=True, verbose_name='Visibilità delibere'),
        ),
        migrations.AlterField(
            model_name='atto_gebevripartizione',
            name='det_v',
            field=models.BooleanField(default=True, verbose_name='Visibilità determinazioni'),
        ),
        migrations.AlterField(
            model_name='atto_gebevripartizione',
            name='dis_v',
            field=models.BooleanField(default=True, verbose_name='Visibilità disposizioni'),
        ),
        migrations.AlterField(
            model_name='atto_gebevripartizione',
            name='int_v',
            field=models.BooleanField(default=True, verbose_name='Visibilità decisioni interne'),
        ),
        migrations.AlterField(
            model_name='atto_gebevripartizione',
            name='pri_v',
            field=models.BooleanField(default=True, verbose_name='Visibilità privacy'),
        ),
        migrations.AlterField(
            model_name='autorizzazione_d3gruppo',
            name='lettura',
            field=models.BooleanField(default=True, verbose_name='Lettura documenti'),
        ),
        migrations.AlterField(
            model_name='autorizzazione_d3gruppo',
            name='posta',
            field=models.BooleanField(default=True, verbose_name='Accesso casella postale'),
        ),
        migrations.AlterField(
            model_name='autorizzazione_d3gruppo',
            name='scrittura',
            field=models.BooleanField(default=True, verbose_name='Modifica documenti'),
        ),
        migrations.AlterField(
            model_name='autorizzazione_gebevripartizione',
            name='del_v',
            field=models.BooleanField(default=True, verbose_name='Visibilità delibere'),
        ),
        migrations.AlterField(
            model_name='autorizzazione_gebevripartizione',
            name='det_v',
            field=models.BooleanField(default=True, verbose_name='Visibilità determinazioni'),
        ),
        migrations.AlterField(
            model_name='autorizzazione_gebevripartizione',
            name='dis_v',
            field=models.BooleanField(default=True, verbose_name='Visibilità disposizioni'),
        ),
        migrations.AlterField(
            model_name='autorizzazione_gebevripartizione',
            name='int_v',
            field=models.BooleanField(default=True, verbose_name='Visibilità decisioni interne'),
        ),
        migrations.AlterField(
            model_name='autorizzazione_gebevripartizione',
            name='pri_v',
            field=models.BooleanField(default=True, verbose_name='Visibilità privacy'),
        ),
        migrations.AlterField(
            model_name='template_d3gruppo',
            name='lettura',
            field=models.BooleanField(default=True, verbose_name='Lettura documenti'),
        ),
        migrations.AlterField(
            model_name='template_d3gruppo',
            name='posta',
            field=models.BooleanField(default=True, verbose_name='Accesso casella postale'),
        ),
        migrations.AlterField(
            model_name='template_d3gruppo',
            name='scrittura',
            field=models.BooleanField(default=True, verbose_name='Modifica documenti'),
        ),
        migrations.AlterField(
            model_name='template_gebevripartizione',
            name='del_v',
            field=models.BooleanField(default=True, verbose_name='Visibilità delibere'),
        ),
        migrations.AlterField(
            model_name='template_gebevripartizione',
            name='det_v',
            field=models.BooleanField(default=True, verbose_name='Visibilità determinazioni'),
        ),
        migrations.AlterField(
            model_name='template_gebevripartizione',
            name='dis_v',
            field=models.BooleanField(default=True, verbose_name='Visibilità disposizioni'),
        ),
        migrations.AlterField(
            model_name='template_gebevripartizione',
            name='int_v',
            field=models.BooleanField(default=True, verbose_name='Visibilità decisioni interne'),
        ),
        migrations.AlterField(
            model_name='template_gebevripartizione',
            name='pri_v',
            field=models.BooleanField(default=True, verbose_name='Visibilità privacy'),
        ),
    ]
