# Generated by Django 5.0.1 on 2025-02-06 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessi', '0028_alter_atto_d3gruppo_lettura_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipogenerico',
            name='gruppo',
            field=models.CharField(choices=[('D3', 'Diritto D3'), ('TX', 'Testo'), ('GE', 'Generico'), ('GO', 'Gruppo Office365'), ('GB', 'Programa delibere'), ('AT', 'Atto'), ('DE', 'Designazione'), ('WW', 'Gruppo Web'), ('SA', 'Gruppo Samba'), ('G2', 'App Goffice2')], max_length=2, verbose_name='Gruppo di tipologie'),
        ),
        migrations.CreateModel(
            name='Atto_GOffice2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data di inserimento')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica')),
                ('data_disattivazione', models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazione')),
                ('diritto_attivato', models.BooleanField(default=False, verbose_name='Diritto assegnato')),
                ('atto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.atto', verbose_name='Atti')),
                ('tipo', models.ManyToManyField(limit_choices_to={'gruppo': 'G2'}, to='accessi.tipogenerico', verbose_name='Tipologia di diritto')),
                ('utente_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utente amministratore abilitante')),
                ('utente_disattivazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto')),
                ('utente_inserimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di attribuzione diritto')),
                ('utente_modifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di modifica diritto')),
            ],
            options={
                'verbose_name': 'Dipendente - App GOffice2',
                'verbose_name_plural': 'Dipendenti - Apps GOffice2',
            },
        ),
        migrations.CreateModel(
            name='Autorizzazione_GOffice2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data di inserimento')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica')),
                ('data_disattivazione', models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazione')),
                ('diritto_attivato', models.BooleanField(default=False, verbose_name='Diritto assegnato')),
                ('autorizzazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.autorizzazione', verbose_name='Autorizzazioni')),
                ('tipo', models.ManyToManyField(limit_choices_to={'gruppo': 'G2'}, to='accessi.tipogenerico', verbose_name='Tipologia di diritto')),
                ('utente_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utente amministratore abilitante')),
                ('utente_disattivazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto')),
                ('utente_inserimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di attribuzione diritto')),
                ('utente_modifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di modifica diritto')),
            ],
            options={
                'verbose_name': 'Ufficio - Diritto Gestione Pagine Web',
                'verbose_name_plural': 'Uffici - Apps GOffice2',
            },
        ),
        migrations.CreateModel(
            name='GOffice2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome del diritto in italiano')),
                ('nome_de', models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome del diritto in tedesco')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in italiano')),
                ('descrizione_de', models.TextField(blank=True, null=True, verbose_name='Descrizione del diritto in tedesco')),
                ('attivo', models.BooleanField(default=True, verbose_name='diritto attivo')),
                ('atti', models.ManyToManyField(related_name='goffice2', through='accessi.Atto_GOffice2', to='accessi.atto', verbose_name='Atto di Assegnazione')),
                ('autorizzazioni', models.ManyToManyField(related_name='goffice2', through='accessi.Autorizzazione_GOffice2', to='accessi.autorizzazione', verbose_name="Autorizzazione d'ufficio")),
            ],
            options={
                'verbose_name': 'App GOffice2',
                'verbose_name_plural': 'Apps GOffice2',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='autorizzazione_goffice2',
            name='diritto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.goffice2', verbose_name='App GOffice2'),
        ),
        migrations.AddField(
            model_name='atto_goffice2',
            name='diritto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.goffice2', verbose_name='App GOffice2'),
        ),
        migrations.CreateModel(
            name='Template_GOffice2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data di inserimento')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica')),
                ('data_disattivazione', models.DateTimeField(blank=True, null=True, verbose_name='Data di disattivazione')),
                ('diritto_attivato', models.BooleanField(default=False, verbose_name='Diritto assegnato')),
                ('diritto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.goffice2', verbose_name='App GOffice2')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessi.template', verbose_name='Templates')),
                ('tipo', models.ManyToManyField(limit_choices_to={'gruppo': 'G2'}, to='accessi.tipogenerico', verbose_name='Tipologia di diritto')),
                ('utente_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utente amministratore abilitante')),
                ('utente_disattivazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di disattivazione diritto')),
                ('utente_inserimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di attribuzione diritto')),
                ('utente_modifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utente di modifica diritto')),
            ],
            options={
                'verbose_name': 'Template - Diritto Gestione Pagine Web',
                'verbose_name_plural': 'Templates - Apps GOffice2',
            },
        ),
        migrations.AddField(
            model_name='goffice2',
            name='templates',
            field=models.ManyToManyField(related_name='wegoffice2b', through='accessi.Template_GOffice2', to='accessi.template', verbose_name='Template precostruito'),
        ),
    ]
