# Generated by Django 5.0.1 on 2025-02-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessi', '0029_alter_tipogenerico_gruppo_atto_goffice2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atto_goffice2',
            options={'verbose_name': 'Dipendente - Modulo GOffice2', 'verbose_name_plural': 'Dipendenti - Moduli GOffice2'},
        ),
        migrations.AlterModelOptions(
            name='autorizzazione_goffice2',
            options={'verbose_name': 'Ufficio - Modulo GOffice2', 'verbose_name_plural': 'Uffici - Apps GOffice2'},
        ),
        migrations.AlterModelOptions(
            name='goffice2',
            options={'ordering': ['nome'], 'verbose_name': 'Modulo GOffice2', 'verbose_name_plural': 'Moduli GOffice2'},
        ),
        migrations.AlterModelOptions(
            name='template_goffice2',
            options={'verbose_name': 'Template - Modulo GOffice2', 'verbose_name_plural': 'Templates - Moduli GOffice2'},
        ),
    ]
