# Generated by Django 5.0.1 on 2025-02-06 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessi', '0030_alter_atto_goffice2_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='d3diritto',
            name='nome_it',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='d3gruppo',
            name='nome_it',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='dirittorete',
            name='nome_it',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='gebevdiritto',
            name='nome_it',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='gebevripartizione',
            name='nome_it',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='generico',
            name='nome_it',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='goffice',
            name='nome_it',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='goffice2',
            name='nome_it',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='grupposamba',
            name='nome_it',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='nextcloud',
            name='nome_it',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='o365gruppo',
            name='nome_it',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='porta',
            name='nome_it',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='sgvcanale',
            name='nome_it',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='web',
            name='nome_it',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AddField(
            model_name='webapp',
            name='nome_it',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='atto_d3diritto',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.d3diritto', verbose_name='Diritto D3'),
        ),
        migrations.AlterField(
            model_name='atto_d3gruppo',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.d3gruppo', verbose_name='Diritto di Gruppo D3'),
        ),
        migrations.AlterField(
            model_name='atto_dirittorete',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.dirittorete', verbose_name='Diritto di Rete'),
        ),
        migrations.AlterField(
            model_name='atto_gebevdiritto',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.gebevdiritto', verbose_name='Diritto Generale Programa delibere'),
        ),
        migrations.AlterField(
            model_name='atto_gebevripartizione',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.gebevripartizione', verbose_name='Diritto di Gruppo Programma delibere'),
        ),
        migrations.AlterField(
            model_name='atto_generico',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.generico', verbose_name='Sottosistema Ascot'),
        ),
        migrations.AlterField(
            model_name='atto_goffice',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.goffice', verbose_name='Diritto GOffice'),
        ),
        migrations.AlterField(
            model_name='atto_goffice2',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.goffice2', verbose_name='App GOffice2'),
        ),
        migrations.AlterField(
            model_name='atto_grupposamba',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.grupposamba', verbose_name='Gruppo Samba'),
        ),
        migrations.AlterField(
            model_name='atto_nextcloud',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.nextcloud', verbose_name='Gruppo NextCloud'),
        ),
        migrations.AlterField(
            model_name='atto_o365gruppo',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.o365gruppo', verbose_name='Gruppo Office 365'),
        ),
        migrations.AlterField(
            model_name='atto_porta',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.porta', verbose_name='Porta'),
        ),
        migrations.AlterField(
            model_name='atto_sgvcanale',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.sgvcanale', verbose_name='Lista Distribuzione SGV'),
        ),
        migrations.AlterField(
            model_name='atto_web',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.web', verbose_name='Diritto Pagine Web'),
        ),
        migrations.AlterField(
            model_name='atto_webapp',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.webapp', verbose_name='Diritto WebApp Django'),
        ),
        migrations.AlterField(
            model_name='autorizzazione_d3diritto',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.d3diritto', verbose_name='Diritto D3'),
        ),
        migrations.AlterField(
            model_name='autorizzazione_d3gruppo',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.d3gruppo', verbose_name='Diritto di Gruppo D3'),
        ),
        migrations.AlterField(
            model_name='autorizzazione_dirittorete',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.dirittorete', verbose_name='Diritto di Rete'),
        ),
        migrations.AlterField(
            model_name='autorizzazione_gebevdiritto',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.gebevdiritto', verbose_name='Diritto Generale Programa delibere'),
        ),
        migrations.AlterField(
            model_name='autorizzazione_gebevripartizione',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.gebevripartizione', verbose_name='Diritto di Gruppo Programma delibere'),
        ),
        migrations.AlterField(
            model_name='autorizzazione_generico',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.generico', verbose_name='Sottosistema Ascot'),
        ),
        migrations.AlterField(
            model_name='autorizzazione_goffice',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.goffice', verbose_name='Diritto GOffice'),
        ),
        migrations.AlterField(
            model_name='autorizzazione_goffice2',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.goffice2', verbose_name='App GOffice2'),
        ),
        migrations.AlterField(
            model_name='autorizzazione_grupposamba',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.grupposamba', verbose_name='Gruppo Samba'),
        ),
        migrations.AlterField(
            model_name='autorizzazione_nextcloud',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.nextcloud', verbose_name='Gruppo NextCloud'),
        ),
        migrations.AlterField(
            model_name='autorizzazione_o365gruppo',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.o365gruppo', verbose_name='Gruppo Office 365'),
        ),
        migrations.AlterField(
            model_name='autorizzazione_porta',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.porta', verbose_name='Porta'),
        ),
        migrations.AlterField(
            model_name='autorizzazione_sgvcanale',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.sgvcanale', verbose_name='Lista Distribuzione SGV'),
        ),
        migrations.AlterField(
            model_name='autorizzazione_web',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.web', verbose_name='Diritto Pagine Web'),
        ),
        migrations.AlterField(
            model_name='autorizzazione_webapp',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.webapp', verbose_name='Diritto WebApp Django'),
        ),
        migrations.AlterField(
            model_name='d3diritto',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome breve del diritto'),
        ),
        migrations.AlterField(
            model_name='d3diritto',
            name='nome_de',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='dirittorete',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome breve del diritto'),
        ),
        migrations.AlterField(
            model_name='dirittorete',
            name='nome_de',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='gebevdiritto',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome breve del diritto'),
        ),
        migrations.AlterField(
            model_name='gebevdiritto',
            name='nome_de',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='generico',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome breve del diritto'),
        ),
        migrations.AlterField(
            model_name='generico',
            name='nome_de',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='goffice',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome breve del diritto'),
        ),
        migrations.AlterField(
            model_name='goffice',
            name='nome_de',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='goffice2',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome breve del diritto'),
        ),
        migrations.AlterField(
            model_name='goffice2',
            name='nome_de',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='grupposamba',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome breve del diritto'),
        ),
        migrations.AlterField(
            model_name='grupposamba',
            name='nome_de',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='nextcloud',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome breve del diritto'),
        ),
        migrations.AlterField(
            model_name='nextcloud',
            name='nome_de',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='o365gruppo',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome breve del diritto'),
        ),
        migrations.AlterField(
            model_name='o365gruppo',
            name='nome_de',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='porta',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome breve del diritto'),
        ),
        migrations.AlterField(
            model_name='porta',
            name='nome_de',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='sgvcanale',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome breve del diritto'),
        ),
        migrations.AlterField(
            model_name='sgvcanale',
            name='nome_de',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='template_d3diritto',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.d3diritto', verbose_name='Diritto D3'),
        ),
        migrations.AlterField(
            model_name='template_d3gruppo',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.d3gruppo', verbose_name='Diritto di Gruppo D3'),
        ),
        migrations.AlterField(
            model_name='template_dirittorete',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.dirittorete', verbose_name='Diritto di Rete'),
        ),
        migrations.AlterField(
            model_name='template_gebevdiritto',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.gebevdiritto', verbose_name='Diritto Generale Programa delibere'),
        ),
        migrations.AlterField(
            model_name='template_gebevripartizione',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.gebevripartizione', verbose_name='Diritto di Gruppo Programma delibere'),
        ),
        migrations.AlterField(
            model_name='template_generico',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.generico', verbose_name='Sottosistema Ascot'),
        ),
        migrations.AlterField(
            model_name='template_goffice',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.goffice', verbose_name='Diritto GOffice'),
        ),
        migrations.AlterField(
            model_name='template_goffice2',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.goffice2', verbose_name='App GOffice2'),
        ),
        migrations.AlterField(
            model_name='template_grupposamba',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.grupposamba', verbose_name='Gruppo Samba'),
        ),
        migrations.AlterField(
            model_name='template_nextcloud',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.nextcloud', verbose_name='Gruppo NextCloud'),
        ),
        migrations.AlterField(
            model_name='template_o365gruppo',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.o365gruppo', verbose_name='Gruppo Office 365'),
        ),
        migrations.AlterField(
            model_name='template_porta',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.porta', verbose_name='Porta'),
        ),
        migrations.AlterField(
            model_name='template_sgvcanale',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.sgvcanale', verbose_name='Lista Distribuzione SGV'),
        ),
        migrations.AlterField(
            model_name='template_web',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.web', verbose_name='Diritto Pagine Web'),
        ),
        migrations.AlterField(
            model_name='template_webapp',
            name='diritto',
            field=models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='accessi.webapp', verbose_name='Diritto WebApp Django'),
        ),
        migrations.AlterField(
            model_name='web',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome breve del diritto'),
        ),
        migrations.AlterField(
            model_name='web',
            name='nome_de',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
        migrations.AlterField(
            model_name='webapp',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome breve del diritto'),
        ),
        migrations.AlterField(
            model_name='webapp',
            name='nome_de',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
    ]
