# Generated by Django 5.0.1 on 2025-02-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessi', '0031_d3diritto_nome_it_d3gruppo_nome_it_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d3diritto',
            name='nome_it',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='d3gruppo',
            name='nome_it',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='dirittorete',
            name='nome_it',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='gebevdiritto',
            name='nome_it',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='gebevripartizione',
            name='nome_it',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='generico',
            name='nome_it',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='goffice',
            name='nome_it',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='goffice2',
            name='nome_it',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='grupposamba',
            name='nome_it',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='nextcloud',
            name='nome_it',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='o365gruppo',
            name='nome_it',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='porta',
            name='nome_it',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='sgvcanale',
            name='nome_it',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='web',
            name='nome_it',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in italiano'),
        ),
        migrations.AlterField(
            model_name='webapp',
            name='nome_it',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in italiano'),
        ),
    ]
