# Generated by Django 5.0.1 on 2025-02-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessi', '0032_alter_d3diritto_nome_it_alter_d3gruppo_nome_it_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d3gruppo',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome breve del diritto'),
        ),
        migrations.AlterField(
            model_name='d3gruppo',
            name='nome_de',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome del diritto in tedesco'),
        ),
    ]
