# Generated by Django 5.0.1 on 2025-04-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessi', '0033_alter_d3gruppo_nome_alter_d3gruppo_nome_de'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='nome_int',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='nome del template in LDAP'),
        ),
    ]
