
"""
Django settings for laisoft project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""

import os
import ldap
import oracledb
from django_auth_ldap.config import LDAPSearch, GroupOfNamesType, PosixGroupType
from django.utils.translation import gettext_lazy as _

# variabili dal file .env
import environ
env = environ.Env()
environ.Env.read_env()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

BASE_URL = "http://leiferstsdjango.leifers.gvcc.net/" #27/12/2023 FATTO
# BASE_URL = "https://laisoft.gvcc.net/" #14/01/2025 impostazione per accessi
 
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/dev/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = '%wiv2wurqwagwm25xzx&r=4raz$43jn=%78#@6meduuqjn7nma'
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['leiferstsdjango', 'localhost', '127.0.0.1', 'leiferstsdjango.leifers.gvcc.net', ]


# Application definition

INSTALLED_APPS = [
	'tabella.apps.TabellaConfig',
	'turni.apps.TurniConfig',
	'dipendenti.apps.DipendentiConfig',
	'valutazioni.apps.ValutazioniConfig',
	'pratiche.apps.PraticheConfig',
	'helpdesk.apps.HelpdeskConfig',
	'accessi.apps.AccessiConfig',
	'gic.apps.GicConfig',
 	'inventario.apps.InventarioConfig',
	'admin_interface', #27/12/2023 FATTO
	'colorfield', #27/12/2023 FATTO
	'django.contrib.admin',
	'django.contrib.admindocs', 
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'django.contrib.gis', #27/12/2023
	'django.forms', #27/12/2023
	'simple_history',
	'webpush',
	'rosetta', #27/12/2023 multilanguage FATTO
	'parler', #27/12/2023 multilanguage FATTO
	'fontawesomefree', #27/12/2023 multi fonts FATTO
	'debug_toolbar', # 27/12/2023 toolbar di debug FATTO
#	'thumbnails', # 15/03/2024 thumbnails per immagini
	'sorl.thumbnail', #15/03/2024 thumbnails per immagini
	'imagefit', # 12/11/2024 Resizer per immagini
    'django_summernote', # 02/12/2024 rtf editor per email
	'rest_framework', # Django REST Framework
    'rest_framework.authtoken', # Django REST Framework Token Authentication
	'corsheaders', # Django CORS Headers
	]


X_FRAME_OPTIONS = "SAMEORIGIN" #27/12/2023 admin-interface FATTO
SILENCED_SYSTEM_CHECKS = ["security.W019"] #27/12/2023 admin-interface FATTO

MIDDLEWARE = [
	'django_currentuser.middleware.ThreadLocalUserMiddleware', # django_currentuser 
	'debug_toolbar.middleware.DebugToolbarMiddleware', #27/12/2023 debug toolbar FATTO
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.locale.LocaleMiddleware', #27/12/2023 multilanguage admin interface FATTO
#	'django.middleware.cache.UpdateCacheMiddleware', #11/07/2024 Cache config
 	'corsheaders.middleware.CorsMiddleware',  # Django CORS Headers
	'django.middleware.common.CommonMiddleware',
#	'django.middleware.cache.FetchFromCacheMiddleware', #11/07/2024 Cache config
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'django.contrib.admindocs.middleware.XViewMiddleware',
	'simple_history.middleware.HistoryRequestMiddleware',

]

ROOT_URLCONF = 'laisoft.urls'

CORS_ALLOWED_ORIGINS = [
	'http://localhost',
	'https://laisoft.gvcc.net',
	'https://leiferstsdjango.leifers.gvcc.net',
	'http://172.23.44.200', # IP del server di sviluppo
]


TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': ['/home/django/progetti/laisoft/laisoft/templates/'],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]
 
TEMPLATE_CONTEXT_PROCESSORS = (
	"module.context_processors.site",
	)

# FORM_RENDERER = 'django.forms.renderers.TemplatesSetting' #27/12/2023 FATTO

WSGI_APPLICATION = 'laisoft.wsgi.application'


# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases

DATABASES = {
	"default": {
		"ENGINE": "django.contrib.gis.db.backends.postgis", #27/12/2023
		#"ENGINE": "django.db.backends.postgresql_psycopg2",
		'NAME': env("DBT_NAME"),
		'USER': env("DBT_USER"),
		'PASSWORD': env("DBT_PASSWORD"),
		'HOST': env("DBT_HOST"),
		'PORT': env("DBT_PORT"),
	},
    'oracle_r040': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': oracledb.makedsn("172.27.4.22", 1521, sid="DB"),
        'USER': env("DBR0_USER"),
		'PASSWORD': env("DBR0_PASSWORD"),
        # 'OPTIONS': {
        #     'threaded': True,
        # },
    }


 
	# "oracle_p": {
	# 	"ENGINE": "django.db.backends.oracle", #10/09/2024
	# 	'NAME': env("DBOP_NAME"),
	# 	'USER': env("DBOP_USER"),
	# 	'PASSWORD': env("DBOP_PASSWORD"),
	# 	'HOST': env("DBOP_HOST"),
	# 	'PORT': env("DBOP_PORT"),
	# },
	# "oracle_l": {
	# 	"ENGINE": "django.db.backends.oracle", #10/09/2024
	# 	'NAME': env("DBOL_NAME"),
	# 	'USER': env("DBOL_USER"),
	# 	'PASSWORD': env("DBOL_PASSWORD"),
	# 	'HOST': env("DBOL_HOST"),
	# 	'PORT': env("DBOL_PORT"),
	# },
}

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend'
    ],
}


LOGIN_URL = "/accounts/login/" #27/12/2023

# Password validation
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]

# Webpush configuration section

WEBPUSH_SETTINGS = { 
	"VAPID_PUBLIC_KEY": env("VAPID_PUBLIC_KEY"),
	"VAPID_PRIVATE_KEY": env("VAPID_PRIVATE_KEY"),
	"VAPID_ADMIN_EMAIL": "giorgio.bertoluzza@comune.laives.bz.it",
	}


# LDAP-autenthication django-auth-ldap
# https://django-auth-ldap.readthedocs.io/


AUTH_LDAP_SERVER_URI = "ldap://ldap.gvcc.net"

AUTH_LDAP_USER_DN_TEMPLATE = "uid=%(user)s, o=leifers,cn=accounts,dc=gvcc,dc=net"

AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail",
}

AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
    "o=leifers,cn=accounts,dc=gvcc,dc=net",
    ldap.SCOPE_SUBTREE,
    "(objectClass=posixGroup)",
)
AUTH_LDAP_GROUP_TYPE = PosixGroupType(name_attr="cn")

# AUTH_LDAP_MIRROR_GROUPS = True
AUTH_LDAP_MIRROR_GROUPS_EXCEPT = (
								'tutti', 
								'LS_staff', 
								'LS_admin',
								'aagg', 
								'admins', 
								'affidamenti', 
								'agenti',
								'ambiente', 
								'anagrafe', 
								'assessori', 
								'beschluss',
								'cantiere', 
								'dup', 
								'economat', 
								'edp', 
								'elezioni', 
								'et', 
								'finanz', 
								'gis', 
								'giurpers', 
								'giurperslim',
								'internet', 
								'licenze', 
								'llpp', 
								'messi', 
								'modelli', 
								'nido', 
								'personal', 
								'polizia', 
								'posta', 
								'prenotazioni',
								'protocollo', 
								'rifiuti', 
								'sektar', 
								'servizi', 
								'sindaco', 
								'tributi', 
								'tutelamb', 
								'urbanist', 
								'vicesegretaria',
								)

AUTH_LDAP_USER_FLAGS_BY_GROUP = {
    "is_active": "cn=tutti,o=leifers,cn=accounts,dc=gvcc,dc=net",
    "is_staff": "cn=LS_staff,o=leifers,cn=accounts,dc=gvcc,dc=net",
    "is_superuser": "cn=LS_admin,o=leifers,cn=accounts,dc=gvcc,dc=net",
}

AUTH_LDAP_CACHE_TIMEOUT = 3600

AUTHENTICATION_BACKENDS = [
    "django_auth_ldap.backend.LDAPBackend",
    "django.contrib.auth.backends.ModelBackend",
]

LOCALE_PATHS = [os.path.join(BASE_DIR, 'locale')]

# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n/

# 27/12/2023 sezione per il multilanguage admin interface

LANGUAGES = (
	("en", _("English")),
	("it", _("Italiano")),
	("de", _("Deutsch")),
# more than one language is expected here
)

LANGUAGE_CODE = 'it'

TIME_ZONE = 'Europe/Rome'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = "/var/www/laisoft/static/"
#STATIC_ROOT = '/home/django/progetti/laisoft/static/'
STATICFILES_DIRS = [
	os.path.join(BASE_DIR, "customstatic"), #27/12/2023
]

#MEDIA_ROOT = '/home/django/progetti/laisoft/media/'
MEDIA_ROOT = "/var/www/laisoft/media/"
MEDIA_URL = '/media/'

IMAGEFIT_ROOT = "media" # 12/11/2024 image resizer

EMAIL_HOST = 'smtp.office365.com'
EMAIL_PORT = 587

EMAIL_HOST_USER = env("EMAIL_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_PASSWORD")
EMAIL_USE_TLS = True

# django-o365mail settings

EMAIL_BACKEND = 'django_o365mail.EmailBackend'

O365_MAIL_CLIENT_ID = env("O365_MAIL_CLIENT_ID") #application ID
O365_MAIL_CLIENT_SECRET = env("O365_MAIL_CLIENT_SECRET")
O365_MAIL_TENANT_ID = env("O365_MAIL_TENANT_ID")
O365_ACTUALLY_SEND_IN_DEBUG = True
O365_MAIL_MAILBOX_KWARGS = {'resource':'mail@comune.laives.bz.it'}

# Rosetta settings 27/12/2023 FATTO
ROSETTA_SHOW_AT_ADMIN_PANEL = True
ROSETTA_ENABLE_TRANSLATION_SUGGESTIONS = True
DEEPL_AUTH_KEY = "ffa32383-1a79-936e-b407-e29e66f50ded:fx"
ROSETTA_MESSAGES_SOURCE_LANGUAGE_CODE = 'it'
ROSETTA_MESSAGES_SOURCE_LANGUAGE_NAME = 'Italiano'
# ROSETTA_REQUIRES_AUTH = False

# parler settings 27/12/2023 FATTO

PARLER_LANGUAGES = {
	None: (
		{'code': 'it',}, # English
		{'code': 'de',}, # Deutsch
		{'code': 'en',}, # Italiano
	),
	'default': {
		'fallbacks': ['it'],
		'hide_untranslated': False,
	}
}

# 11/07/2024 settings per cache



#CACHES = {
#	'default': {
#		'BACKEND': 'django_redis.cache.RedisCache',
#		'LOCATION': 'redis://localhost:6379/1',
#		'OPTIONS': {
#			'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#			}
#		}
#	}

#SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
#SESSION_CACHE_ALIAS = 'default'

#CACHE_MIDDLEWARE_ALIAS  = 'default' # cache alias
#CACHE_MIDDLEWARE_SECONDS = 60 # number of seconds each page should be cached.
# CACHE_MIDDLEWARE_KEY_PREFIX = ''  # name of site if multiple sites are used


# 15/03/2024 settings per thumbnails 
"""
THUMBNAILS = {
	'METADATA': {
		'BACKEND': 'thumbnails.backends.metadata.DatabaseBackend',
		},
	'STORAGE': {
		'BACKEND': 'django.core.files.storage.FileSystemStorage',

	},
	'SIZES': {
		'small': {
			'PROCESSORS': [
				{'PATH': 'thumbnails.processors.resize', 'width': 20, 'height': 20},
				{'PATH': 'thumbnails.processors.crop', 'width': 80, 'height': 80}
				],
			'POST_PROCESSORS': [
				{
					'PATH': 'thumbnails.post_processors.optimize',
					'png_command': 'optipng -force -o7 "%(filename)s"',
					'jpg_command': 'jpegoptim -f --strip-all "%(filename)s"',
				},
		],
		},
		'large': {
			'PROCESSORS': [
				{'PATH': 'thumbnails.processors.resize', 'width': 40, 'height': 40},
				{'PATH': 'thumbnails.processors.flip', 'direction': 'horizontal'}
			],
		},
	}
}
"""

# debug toolbar setup FATTO


INTERNAL_IPS = [
 	'127.0.0.1',
 	'172.27.44.17',
 	'172.23.44.200',
 	]