# Generated by Django 3.1 on 2019-10-07 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gruppo',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Codice Gruppo')),
                ('descrizione', models.CharField(max_length=100, verbose_name='Descrizione del gruppo')),
            ],
        ),
        migrations.CreateModel(
            name='VoceTitolario',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Codice Classifica')),
                ('descrizione', models.CharField(max_length=100, verbose_name='Descrizione della voce di titolario')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nota', models.TextField(blank=True, null=True, verbose_name='Annotazioni')),
                ('temporaneo', models.BooleanField(default=False, verbose_name='Voce proposta ma non verificata')),
                ('classifica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tabella.VoceTitolario', verbose_name='Voce di Titolario')),
                ('titolari', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tabella.Gruppo', verbose_name='Gruppo Titolare')),
                ('visibilita', models.ManyToManyField(blank=True, related_name='tipo_visibilita', to='tabella.Gruppo', verbose_name='Gruppo/i in Visibilità')),
            ],
        ),
    ]
