# Generated by Django 3.1 on 2019-10-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabella', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gruppo',
            name='descrizione',
            field=models.CharField(max_length=150, verbose_name='Descrizione del gruppo'),
        ),
        migrations.AlterField(
            model_name='vocetitolario',
            name='descrizione',
            field=models.CharField(max_length=200, verbose_name='Descrizione della voce di titolario'),
        ),
    ]
