# Generated by Django 3.1 on 2019-10-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabella', '0002_auto_20191008_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocetitolario',
            name='order',
            field=models.IntegerField(null=True, verbose_name="ordinale di presenzazione dell'elenco"),
        ),
    ]
