# Generated by Django 3.2 on 2021-04-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabella', '0003_vocetitolario_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gruppo',
            options={'verbose_name': 'gruppo', 'verbose_name_plural': 'gruppi'},
        ),
        migrations.AlterModelOptions(
            name='tipo',
            options={'verbose_name': 'tipologia di documento', 'verbose_name_plural': 'tipologie di documento'},
        ),
        migrations.AlterModelOptions(
            name='vocetitolario',
            options={'verbose_name': 'voce di titolario', 'verbose_name_plural': 'voci di titolario'},
        ),
        migrations.AlterField(
            model_name='tipo',
            name='temporaneo',
            field=models.BooleanField(default=False, verbose_name='Voce non visualizzata in tabella'),
        ),
    ]
