# Generated by Django 4.2.7 on 2023-12-28 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intervento',
            options={'verbose_name': 'Intervento', 'verbose_name_plural': 'Interventi'},
        ),
        migrations.AlterField(
            model_name='collaboratorereperibilita',
            name='reperibilita',
            field=models.ForeignKey(limit_choices_to={'tipo': 'RE'}, on_delete=django.db.models.deletion.PROTECT, to='gic.tipologia', verbose_name='Tipo di reperibilità'),
        ),
    ]
