# Generated by Django 4.2.7 on 2023-12-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gic', '0002_alter_intervento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attivita',
            options={'verbose_name': 'Attività', 'verbose_name_plural': 'Attività'},
        ),
        migrations.AlterModelOptions(
            name='lavoro',
            options={'verbose_name': 'Lavoro', 'verbose_name_plural': 'Lavoro'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team di intervento', 'verbose_name_plural': 'Teams di intervento'},
        ),
        migrations.AlterField(
            model_name='tipologia',
            name='tipo',
            field=models.CharField(choices=[('TO', 'Stato'), ('SO', 'Origine Segnalazione'), ('ST', 'Tipologia Segnalazione'), ('FO', 'Tipologia di Foto'), ('AS', 'Tipologia di assenza'), ('RE', 'Tipologia di Reperibilità')], max_length=2, verbose_name='Tipo'),
        ),
    ]
