# Generated by Django 4.2.7 on 2023-12-29 13:38

from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('gic', '0003_alter_attivita_options_alter_lavoro_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attivita',
            name='descrizione_de',
        ),
        migrations.RemoveField(
            model_name='attivita',
            name='descrizione_it',
        ),
        migrations.RemoveField(
            model_name='attivita',
            name='nome_breve',
        ),
        migrations.RemoveField(
            model_name='attivita',
            name='nome_de',
        ),
        migrations.RemoveField(
            model_name='attivita',
            name='nome_it',
        ),
        migrations.RemoveField(
            model_name='cdc',
            name='descrizione_de',
        ),
        migrations.RemoveField(
            model_name='cdc',
            name='descrizione_it',
        ),
        migrations.RemoveField(
            model_name='cdc',
            name='nome_breve',
        ),
        migrations.RemoveField(
            model_name='cdc',
            name='nome_de',
        ),
        migrations.RemoveField(
            model_name='cdc',
            name='nome_it',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='descrizione_de',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='descrizione_it',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='nome_breve',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='nome_de',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='nome_it',
        ),
        migrations.RemoveField(
            model_name='mansione',
            name='descrizione_de',
        ),
        migrations.RemoveField(
            model_name='mansione',
            name='descrizione_it',
        ),
        migrations.RemoveField(
            model_name='mansione',
            name='nome_breve',
        ),
        migrations.RemoveField(
            model_name='mansione',
            name='nome_de',
        ),
        migrations.RemoveField(
            model_name='mansione',
            name='nome_it',
        ),
        migrations.RemoveField(
            model_name='priorita',
            name='descrizione_de',
        ),
        migrations.RemoveField(
            model_name='priorita',
            name='descrizione_it',
        ),
        migrations.RemoveField(
            model_name='priorita',
            name='nome_breve',
        ),
        migrations.RemoveField(
            model_name='priorita',
            name='nome_de',
        ),
        migrations.RemoveField(
            model_name='priorita',
            name='nome_it',
        ),
        migrations.RemoveField(
            model_name='squadra',
            name='descrizione_de',
        ),
        migrations.RemoveField(
            model_name='squadra',
            name='descrizione_it',
        ),
        migrations.RemoveField(
            model_name='squadra',
            name='nome_breve',
        ),
        migrations.RemoveField(
            model_name='squadra',
            name='nome_de',
        ),
        migrations.RemoveField(
            model_name='squadra',
            name='nome_it',
        ),
        migrations.RemoveField(
            model_name='struttura',
            name='descrizione_de',
        ),
        migrations.RemoveField(
            model_name='struttura',
            name='descrizione_it',
        ),
        migrations.RemoveField(
            model_name='struttura',
            name='nome_breve',
        ),
        migrations.RemoveField(
            model_name='struttura',
            name='nome_de',
        ),
        migrations.RemoveField(
            model_name='struttura',
            name='nome_it',
        ),
        migrations.RemoveField(
            model_name='tipologia',
            name='descrizione_de',
        ),
        migrations.RemoveField(
            model_name='tipologia',
            name='descrizione_it',
        ),
        migrations.RemoveField(
            model_name='tipologia',
            name='nome_breve',
        ),
        migrations.RemoveField(
            model_name='tipologia',
            name='nome_de',
        ),
        migrations.RemoveField(
            model_name='tipologia',
            name='nome_it',
        ),
        migrations.CreateModel(
            name='TipologiaTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('nome_breve', models.CharField(max_length=30, verbose_name='Nome Breve')),
                ('descrizione', models.TextField(verbose_name='Descrizione per interfaccia')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='gic.tipologia')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StrutturaTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('nome_breve', models.CharField(max_length=30, verbose_name='Nome Breve')),
                ('descrizione', models.TextField(verbose_name='Descrizione per interfaccia')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='gic.struttura')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SquadraTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('nome_breve', models.CharField(max_length=30, verbose_name='Nome Breve')),
                ('descrizione', models.TextField(verbose_name='Descrizione per interfaccia')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='gic.squadra')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PrioritaTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('nome_breve', models.CharField(max_length=30, verbose_name='Nome Breve')),
                ('descrizione', models.TextField(verbose_name='Descrizione per interfaccia')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='gic.priorita')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MansioneTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('nome_breve', models.CharField(max_length=30, verbose_name='Nome Breve')),
                ('descrizione', models.TextField(verbose_name='Descrizione per interfaccia')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='gic.mansione')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EventoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('nome_breve', models.CharField(max_length=30, verbose_name='Nome Breve')),
                ('descrizione', models.TextField(verbose_name='Descrizione per interfaccia')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='gic.evento')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CdCTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('nome_breve', models.CharField(max_length=30, verbose_name='Nome Breve')),
                ('descrizione', models.TextField(verbose_name='Descrizione per interfaccia')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='gic.cdc')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AttivitaTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('nome_breve', models.CharField(max_length=30, verbose_name='Nome Breve')),
                ('descrizione', models.TextField(verbose_name='Descrizione per interfaccia')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='gic.attivita')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
