# Generated by Django 4.2.7 on 2023-12-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gic', '0004_remove_attivita_descrizione_de_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='struttura',
            name='indirizzo_de',
        ),
        migrations.RemoveField(
            model_name='struttura',
            name='indirizzo_it',
        ),
        migrations.AddField(
            model_name='strutturatranslation',
            name='indirizzo',
            field=models.CharField(default='-', max_length=150, verbose_name='Indirizzo in italiano'),
            preserve_default=False,
        ),
    ]
