# Generated by Django 4.2.7 on 2024-01-04 08:22

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gic', '0005_remove_struttura_indirizzo_de_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diritto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, verbose_name='Data di creazione')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data di ultima modifica')),
                ('nome', models.CharField(max_length=15, verbose_name='Nome del diritto')),
                ('capocantiere', models.BooleanField(default=False, verbose_name='Capo-cantiere')),
                ('caposquadra', models.BooleanField(default=False, verbose_name='Capo-cantiere')),
                ('coordinatore', models.BooleanField(default=False, verbose_name='Capo-cantiere')),
                ('operai', models.BooleanField(default=False, verbose_name='Capo-cantiere')),
                ('struttura', models.BooleanField(default=False, verbose_name='Capo-cantiere')),
                ('ufficio', models.BooleanField(default=False, verbose_name='Capo-cantiere')),
            ],
            options={
                'verbose_name': 'Diritto',
                'verbose_name_plural': 'Diritti',
            },
        ),
        migrations.AlterField(
            model_name='attivita',
            name='colore',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Colore'),
        ),
        migrations.AlterField(
            model_name='attivitatranslation',
            name='descrizione',
            field=models.TextField(verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='cdc',
            name='colore',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Colore'),
        ),
        migrations.AlterField(
            model_name='cdctranslation',
            name='descrizione',
            field=models.TextField(verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='colore',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Colore'),
        ),
        migrations.AlterField(
            model_name='eventotranslation',
            name='descrizione',
            field=models.TextField(verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='mansione',
            name='colore',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Colore'),
        ),
        migrations.AlterField(
            model_name='mansionetranslation',
            name='descrizione',
            field=models.TextField(verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='priorita',
            name='colore',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Colore'),
        ),
        migrations.AlterField(
            model_name='prioritatranslation',
            name='descrizione',
            field=models.TextField(verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='squadra',
            name='colore',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Colore'),
        ),
        migrations.AlterField(
            model_name='squadratranslation',
            name='descrizione',
            field=models.TextField(verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='struttura',
            name='colore',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Colore'),
        ),
        migrations.AlterField(
            model_name='strutturatranslation',
            name='descrizione',
            field=models.TextField(verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='strutturatranslation',
            name='indirizzo',
            field=models.CharField(max_length=150, verbose_name='Indirizzo'),
        ),
        migrations.AlterField(
            model_name='tipologia',
            name='colore',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Colore'),
        ),
        migrations.AlterField(
            model_name='tipologiatranslation',
            name='descrizione',
            field=models.TextField(verbose_name='Descrizione'),
        ),
    ]
