# Generated by Django 4.2.7 on 2024-01-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gic', '0006_diritto_alter_attivita_colore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diritto',
            name='caposquadra',
            field=models.BooleanField(default=False, verbose_name='Caposquadra'),
        ),
        migrations.AlterField(
            model_name='diritto',
            name='coordinatore',
            field=models.BooleanField(default=False, verbose_name='Coordinatore'),
        ),
        migrations.AlterField(
            model_name='diritto',
            name='operai',
            field=models.BooleanField(default=False, verbose_name='Operai'),
        ),
        migrations.AlterField(
            model_name='diritto',
            name='struttura',
            field=models.BooleanField(default=False, verbose_name='Referente di struttura'),
        ),
        migrations.AlterField(
            model_name='diritto',
            name='ufficio',
            field=models.BooleanField(default=False, verbose_name='Ufficio'),
        ),
    ]
