# Generated by Django 4.2.7 on 2024-01-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gic', '0007_alter_diritto_caposquadra_alter_diritto_coordinatore_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diritto',
            old_name='operai',
            new_name='operaio',
        ),
        migrations.AlterField(
            model_name='diritto',
            name='capocantiere',
            field=models.BooleanField(default=False, verbose_name='Capocantiere'),
        ),
    ]
