# Generated by Django 4.2.7 on 2024-01-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gic', '0008_rename_operai_diritto_operaio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipologia',
            name='ordine',
            field=models.IntegerField(default=1),
        ),
    ]
