# Generated by Django 4.2.7 on 2024-01-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gic', '0009_tipologia_ordine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervento',
            old_name='id_RABS',
            new_name='id_rabs',
        ),
        migrations.AlterField(
            model_name='tipologia',
            name='ordine',
            field=models.IntegerField(default=1, verbose_name='Ordine'),
        ),
    ]
