# Generated by Django 4.2.7 on 2024-01-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gic', '0010_rename_id_rabs_intervento_id_rabs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, verbose_name='Data di creazione')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data di ultima modifica')),
                ('modello', models.CharField(choices=[('Segnalazione', 'Segnalazione'), ('Intervento', 'Intervento'), ('Team', 'Team'), ('Lavoro', 'Lavoro')], max_length=25, verbose_name='Modello')),
                ('tema', models.CharField(choices=[('a', 'Tema a'), ('b', 'Tema b'), ('c', 'Tema c'), ('d', 'Temad'), ('e', 'Temae'), ('f', 'Tema f'), ('g', 'Tema g')], max_length=1, verbose_name='Tema')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temi',
            },
        ),
    ]
