# Generated by Django 5.0.1 on 2024-01-16 13:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gic', '0011_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervento',
            name='data_esecuzione',
            field=models.DateField(default=datetime.datetime.now, help_text="Data a partire dalla quale l'intervento può venire risolto.", verbose_name='Data di esecuzione'),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='data_visibilita',
            field=models.DateField(default=datetime.datetime.now, help_text="Data a partire dalla quale l'intervento diventa visibile.", verbose_name='Data di visibilità'),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='stato',
            field=models.ForeignKey(default=1, limit_choices_to={'tipo': 'TO'}, on_delete=django.db.models.deletion.PROTECT, to='gic.tipologia', verbose_name="Stato dell'elemento"),
        ),
        migrations.AlterField(
            model_name='lavoro',
            name='stato',
            field=models.ForeignKey(default=1, limit_choices_to={'tipo': 'TO'}, on_delete=django.db.models.deletion.PROTECT, to='gic.tipologia', verbose_name="Stato dell'elemento"),
        ),
        migrations.AlterField(
            model_name='segnalazione',
            name='stato',
            field=models.ForeignKey(default=1, limit_choices_to={'tipo': 'TO'}, on_delete=django.db.models.deletion.PROTECT, to='gic.tipologia', verbose_name="Stato dell'elemento"),
        ),
        migrations.AlterField(
            model_name='tema',
            name='modello',
            field=models.CharField(choices=[('Segnalazione', 'Segnalazione'), ('Intervento', 'Intervento'), ('Team', 'Team'), ('Lavoro', 'Lavoro'), ('Salva', 'Pulsante "Salva"')], max_length=25, unique=True, verbose_name='Modello'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='tema',
            field=models.CharField(choices=[('a', 'Tema a'), ('b', 'Tema b'), ('c', 'Tema c'), ('d', 'Tema d'), ('e', 'Tema e'), ('f', 'Tema f'), ('g', 'Tema g')], max_length=1, verbose_name='Tema'),
        ),
        migrations.AlterField(
            model_name='tempilavoro',
            name='inizio',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Data e ora di Inizio'),
        ),
    ]
