# Generated by Django 5.0.1 on 2024-01-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gic', '0012_alter_intervento_data_esecuzione_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboratore',
            name='sigla',
            field=models.CharField(default='XXX', max_length=3, verbose_name='Sigla'),
        ),
    ]
