# Generated by Django 5.0.1 on 2024-01-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gic', '0013_collaboratore_sigla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboratore',
            name='sigla',
            field=models.CharField(max_length=3, unique=True, verbose_name='Sigla'),
        ),
    ]
