# Generated by Django 5.0.1 on 2024-01-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gic', '0014_alter_collaboratore_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipologia',
            name='fa_icon',
            field=models.CharField(default='fa-solid fa-circle', max_length=60, verbose_name='Classe icona FontAwesome'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='modello',
            field=models.CharField(choices=[('Segnalazione', 'Segnalazione'), ('Intervento', 'Intervento'), ('Team', 'Team'), ('Lavoro', 'Lavoro'), ('Collaboratore', 'Collaboratore'), ('Salva', 'Pulsante "Salva"')], max_length=25, unique=True, verbose_name='Modello'),
        ),
    ]
