# Generated by Django 5.0.1 on 2024-01-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gic', '0015_tipologia_fa_icon_alter_tema_modello'),
    ]

    operations = [
        migrations.AddField(
            model_name='attivita',
            name='fa_icon',
            field=models.CharField(default='fa-solid fa-circle', max_length=60, verbose_name='Classe icona FontAwesome'),
        ),
        migrations.AddField(
            model_name='cdc',
            name='fa_icon',
            field=models.CharField(default='fa-solid fa-circle', max_length=60, verbose_name='Classe icona FontAwesome'),
        ),
        migrations.AddField(
            model_name='evento',
            name='fa_icon',
            field=models.CharField(default='fa-solid fa-circle', max_length=60, verbose_name='Classe icona FontAwesome'),
        ),
        migrations.AddField(
            model_name='mansione',
            name='fa_icon',
            field=models.CharField(default='fa-solid fa-circle', max_length=60, verbose_name='Classe icona FontAwesome'),
        ),
        migrations.AddField(
            model_name='priorita',
            name='fa_icon',
            field=models.CharField(default='fa-solid fa-circle', max_length=60, verbose_name='Classe icona FontAwesome'),
        ),
        migrations.AddField(
            model_name='squadra',
            name='fa_icon',
            field=models.CharField(default='fa-solid fa-circle', max_length=60, verbose_name='Classe icona FontAwesome'),
        ),
        migrations.AddField(
            model_name='struttura',
            name='fa_icon',
            field=models.CharField(default='fa-solid fa-circle', max_length=60, verbose_name='Classe icona FontAwesome'),
        ),
        migrations.AlterField(
            model_name='diritto',
            name='operaio',
            field=models.BooleanField(default=False, verbose_name='Operaio'),
        ),
        migrations.AlterField(
            model_name='tipologia',
            name='tipo',
            field=models.CharField(choices=[('TO', 'Stato'), ('SO', 'Origine Segnalazione'), ('ST', 'Tipologia Segnalazione'), ('FO', 'Tipologia di Foto'), ('AS', 'Tipologia di assenza'), ('RE', 'Tipologia di Reperibilità'), ('IN', 'Interno')], max_length=2, verbose_name='Tipo'),
        ),
    ]
