# Generated by Django 5.0.1 on 2024-01-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gic', '0016_attivita_fa_icon_cdc_fa_icon_evento_fa_icon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventosegnalazione',
            options={'verbose_name': 'Evento - Segnalazione', 'verbose_name_plural': 'Eventi - Segnalazioni'},
        ),
        migrations.RemoveField(
            model_name='eventosegnalazione',
            name='anno',
        ),
    ]
