# Generated by Django 5.0.1 on 2024-01-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gic', '0017_alter_eventosegnalazione_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gic.evento',),
        ),
        migrations.AlterField(
            model_name='segnalazione',
            name='eventi',
            field=models.ManyToManyField(related_name='+', through='gic.EventoSegnalazione', to='gic.evento', verbose_name='Eventi collegati'),
        ),
        migrations.AddField(
            model_name='segnalazione',
            name='tags',
            field=models.ManyToManyField(related_name='segnalazioni', to='gic.tag', verbose_name='Tag collegati'),
        ),
    ]
