# Generated by Django 5.0.1 on 2024-02-09 12:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gic', '0018_tag_alter_segnalazione_eventi_segnalazione_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='posizione',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='tema',
            name='modello',
            field=models.CharField(choices=[('Segnalazione', 'Segnalazione'), ('Intervento', 'Intervento'), ('Team', 'Team'), ('Lavoro', 'Lavoro'), ('Tempilavoro', 'Tempi di Lavoro'), ('Collaboratore', 'Collaboratore'), ('Salva', 'Pulsante "Salva"')], max_length=25, unique=True, verbose_name='Modello'),
        ),
    ]
