# Generated by Django 5.0.1 on 2024-03-15 08:06

import thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gic', '0019_alter_foto_posizione_alter_tema_modello'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=thumbnails.fields.ImageField(upload_to='foto/%Y/%m/'),
        ),
    ]
