# Generated by Django 5.0.1 on 2024-03-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gic', '0020_alter_foto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(upload_to='foto/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='modello',
            field=models.CharField(choices=[('Segnalazione', 'Segnalazione'), ('Intervento', 'Intervento'), ('Team', 'Team'), ('Lavoro', 'Lavoro'), ('Tempilavoro', 'Tempi di Lavoro'), ('Collaboratore', 'Collaboratore'), ('Salva', 'Pulsante "Salva"'), ('FO', 'Foto')], max_length=25, unique=True, verbose_name='Modello'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='tema',
            field=models.CharField(choices=[('a', 'Tema a'), ('b', 'Tema b'), ('c', 'Tema c'), ('d', 'Tema d'), ('e', 'Tema e'), ('f', 'Tema f'), ('g', 'Tema g'), ('h', 'Tema h'), ('i', 'Tema i'), ('j', 'Tema j')], max_length=1, verbose_name='Tema'),
        ),
    ]
