# Generated by Django 5.0.1 on 2024-03-15 11:08

import thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gic', '0021_alter_foto_foto_alter_tema_modello_alter_tema_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=thumbnails.fields.ImageField(upload_to='foto/%Y/%m/'),
        ),
    ]
