# Generated by Django 5.0.1 on 2024-03-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gic', '0022_alter_foto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(upload_to='foto/%Y/%m/'),
        ),
    ]
