# Generated by Django 5.0.1 on 2024-06-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gic', '0023_alter_foto_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaboratoreassenza',
            options={'ordering': ['data_da'], 'verbose_name': 'Periodo di assenza del Collaboratore', 'verbose_name_plural': 'Periodi di assenze del collaboratore'},
        ),
        migrations.AlterModelOptions(
            name='collaboratorereperibilita',
            options={'ordering': ['data_da'], 'verbose_name': 'Periodo di reperibilità del Collaboratore', 'verbose_name_plural': 'Periodi di reperibilità del collaboratore'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='collaboratore',
            order_with_respect_to='dipendente',
        ),
    ]
