# Generated by Django 5.0.1 on 2024-06-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gic', '0024_alter_collaboratoreassenza_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segnalazione',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='segnalazioni', to='gic.tag', verbose_name='Tag collegati'),
        ),
    ]
