# Generated by Django 5.0.1 on 2024-07-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gic', '0025_alter_segnalazione_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='allegato',
            name='descrizione',
            field=models.TextField(default='Allegato', max_length=80, verbose_name='Descrizione'),
        ),
    ]
