# Generated by Django 5.0.1 on 2024-07-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gic', '0026_allegato_descrizione'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, verbose_name='Data di creazione')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data di ultima modifica')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome della vista')),
                ('nome_modello', models.CharField(max_length=30, verbose_name='Nome del Modello')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
