# Generated by Django 5.0.1 on 2024-07-04 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gic', '0027_vista'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboratore',
            name='vista',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='gic.vista', verbose_name='Vista iniziale'),
        ),
    ]
