# Generated by Django 5.0.1 on 2024-07-05 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gic', '0028_collaboratore_vista'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vista',
            options={'verbose_name': 'Vista', 'verbose_name_plural': 'Viste'},
        ),
    ]
