# Generated by Django 5.0.1 on 2024-07-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gic', '0029_alter_vista_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='tempo_aumento',
            field=models.IntegerField(blank=True, help_text='Tempo dopo il quale la priorità aumenta di grado. Il valore si intende indicato in giornate', null=True, verbose_name='Tempo di aumento della priorità'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tempo_stimato',
            field=models.IntegerField(blank=True, help_text='Il valore si intende indicato in ore/uomo', null=True, verbose_name='Tempo stimato di soluzione'),
        ),
    ]
