# Generated by Django 5.0.1 on 2024-08-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gic', '0032_alter_tema_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='attivita',
            name='fa_visible',
            field=models.BooleanField(default=True, verbose_name='Icona Visibile'),
        ),
        migrations.AddField(
            model_name='cdc',
            name='fa_visible',
            field=models.BooleanField(default=True, verbose_name='Icona Visibile'),
        ),
        migrations.AddField(
            model_name='evento',
            name='fa_visible',
            field=models.BooleanField(default=True, verbose_name='Icona Visibile'),
        ),
        migrations.AddField(
            model_name='mansione',
            name='fa_visible',
            field=models.BooleanField(default=True, verbose_name='Icona Visibile'),
        ),
        migrations.AddField(
            model_name='priorita',
            name='fa_visible',
            field=models.BooleanField(default=True, verbose_name='Icona Visibile'),
        ),
        migrations.AddField(
            model_name='squadra',
            name='fa_visible',
            field=models.BooleanField(default=True, verbose_name='Icona Visibile'),
        ),
        migrations.AddField(
            model_name='struttura',
            name='fa_visible',
            field=models.BooleanField(default=True, verbose_name='Icona Visibile'),
        ),
        migrations.AddField(
            model_name='tipologia',
            name='fa_visible',
            field=models.BooleanField(default=True, verbose_name='Icona Visibile'),
        ),
    ]
