# Generated by Django 5.0.1 on 2025-03-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gic', '0033_attivita_fa_visible_cdc_fa_visible_evento_fa_visible_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='intervento',
            index=models.Index(fields=['stato'], name='gic_interve_stato_i_10ca5e_idx'),
        ),
        migrations.AddIndex(
            model_name='intervento',
            index=models.Index(fields=['struttura'], name='gic_interve_struttu_905fc3_idx'),
        ),
        migrations.AddIndex(
            model_name='intervento',
            index=models.Index(fields=['segnalazione'], name='gic_interve_segnala_d8098d_idx'),
        ),
        migrations.AddIndex(
            model_name='lavoro',
            index=models.Index(fields=['stato'], name='gic_lavoro_stato_i_8bb47a_idx'),
        ),
        migrations.AddIndex(
            model_name='lavoro',
            index=models.Index(fields=['collaboratore'], name='gic_lavoro_collabo_172039_idx'),
        ),
        migrations.AddIndex(
            model_name='lavoro',
            index=models.Index(fields=['team'], name='gic_lavoro_team_id_6cb813_idx'),
        ),
        migrations.AddIndex(
            model_name='segnalazione',
            index=models.Index(fields=['stato'], name='gic_segnala_stato_i_54cc39_idx'),
        ),
        migrations.AddIndex(
            model_name='segnalazione',
            index=models.Index(fields=['struttura'], name='gic_segnala_struttu_0de099_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['intervento'], name='gic_team_interve_8c3cb6_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['attivita'], name='gic_team_attivit_bf0862_idx'),
        ),
    ]
