# Generated by Django 5.0.1 on 2025-03-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0079_alter_dipendente_sesso_and_more'),
        ('gic', '0034_intervento_gic_interve_stato_i_10ca5e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='struttura',
            name='autorizzati',
            field=models.ManyToManyField(related_name='strutture', to='dipendenti.servizio'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='tema',
            field=models.CharField(choices=[('a', 'Tema a'), ('b', 'Tema b'), ('c', 'Tema c'), ('d', 'Tema d'), ('e', 'Tema e'), ('f', 'Tema f'), ('g', 'Tema g'), ('h', 'Tema h'), ('i', 'Tema i'), ('j', 'Tema j'), ('k', 'Tema k'), ('l', 'Tema l'), ('m', 'Tema m')], max_length=1, verbose_name='Tema'),
        ),
    ]
