# Generated by Django 5.0.1 on 2025-07-24 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gic', '0035_struttura_autorizzati_alter_tema_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segnalazione',
            name='eventi',
            field=models.ManyToManyField(blank=True, null=True, related_name='evento_segnalazioni', through='gic.EventoSegnalazione', to='gic.evento', verbose_name='Eventi collegati'),
        ),
        migrations.AlterField(
            model_name='segnalazione',
            name='origine',
            field=models.ForeignKey(limit_choices_to={'tipo': 'SO'}, on_delete=django.db.models.deletion.PROTECT, related_name='origine_segnalazioni', to='gic.tipologia', verbose_name='Origine della segnalazione'),
        ),
        migrations.AlterField(
            model_name='segnalazione',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tag_segnalazioni', to='gic.tag', verbose_name='Tag collegati'),
        ),
        migrations.AlterField(
            model_name='segnalazione',
            name='tipo',
            field=models.ForeignKey(limit_choices_to={'tipo': 'ST'}, on_delete=django.db.models.deletion.PROTECT, related_name='tipo_segnalazioni', to='gic.tipologia', verbose_name='Tipo di segnalazione'),
        ),
    ]
