# Generated by Django 3.2 on 2022-04-12 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dipendente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('cognome', models.CharField(max_length=40, verbose_name='Cognome')),
                ('userid', models.CharField(max_length=16, verbose_name='Nome Utente')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('telefono', models.CharField(blank=True, max_length=40, null=True, verbose_name='Telefono')),
                ('cellulare', models.CharField(blank=True, max_length=40, null=True, verbose_name='Cellulare')),
                ('catprotetta', models.BooleanField(default=False, verbose_name='Categoria Protetta')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note aggiuntive')),
            ],
            options={
                'verbose_name': 'Dipendente',
                'verbose_name_plural': 'Dipendenti',
                'ordering': ['cognome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Livello',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('livello', models.CharField(max_length=10, verbose_name='Livello')),
                ('indice', models.IntegerField(verbose_name='Indice')),
                ('coefficiente', models.IntegerField(verbose_name='Coefficiente premio produzione')),
            ],
            options={
                'verbose_name': 'Livello',
                'verbose_name_plural': 'Livelli',
                'ordering': ['indice'],
            },
        ),
        migrations.CreateModel(
            name='Ruolo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome Breve')),
                ('nome_it_m', models.CharField(max_length=40, verbose_name='Nome italiano maschile')),
                ('nome_it_f', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome italiano femminile')),
                ('nome_dt_m', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome tedesco maschile')),
                ('nome_dt_f', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome tedesco femminile')),
                ('dirigente', models.BooleanField(default=False, verbose_name='Ruolo dirigenziale')),
                ('coordinatore', models.BooleanField(default=False, verbose_name='Ruolo di coordinamento')),
                ('responsabile', models.BooleanField(default=False, verbose_name='Ruolo di responsabile')),
                ('segretario', models.BooleanField(default=False, verbose_name='Ruolo segretario generale')),
                ('ammsistema', models.BooleanField(default=False, verbose_name='Ruolo amministratore di sistema')),
                ('sindaco', models.BooleanField(default=False, verbose_name='Ruolo da sindaco')),
            ],
            options={
                'verbose_name': 'Ruolo',
                'verbose_name_plural': 'Ruoli',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Servizio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome Breve')),
                ('nome_it_m', models.CharField(max_length=40, verbose_name='Nome italiano maschile')),
                ('nome_it_f', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome italiano femminile')),
                ('nome_dt_m', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome tedesco maschile')),
                ('nome_dt_f', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome tedesco femminile')),
                ('esente_irap', models.BooleanField(default=False, verbose_name='Servizio esente IRAP')),
            ],
            options={
                'verbose_name': 'Servizio',
                'verbose_name_plural': 'Servizi',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Ufficio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome Breve')),
                ('nome_it_m', models.CharField(max_length=40, verbose_name='Nome italiano maschile')),
                ('nome_it_f', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome italiano femminile')),
                ('nome_dt_m', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome tedesco maschile')),
                ('nome_dt_f', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome tedesco femminile')),
            ],
            options={
                'verbose_name': 'Ufficio',
                'verbose_name_plural': 'Uffici',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Ufficio_Dirigente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_da', models.DateField(verbose_name='Data di inizio')),
                ('data_a', models.DateField(blank=True, null=True, verbose_name='Data di fine')),
                ('dirigente', models.ForeignKey(limit_choices_to={'ruolo__dirigente': True}, on_delete=django.db.models.deletion.CASCADE, to='dipendenti.dipendente')),
                ('ufficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipendenti.ufficio')),
            ],
            options={
                'verbose_name': 'Ufficio - Dirigente',
                'verbose_name_plural': 'Uffici - Dirigenti',
            },
        ),
        migrations.AddField(
            model_name='ufficio',
            name='dirigente',
            field=models.ManyToManyField(related_name='dirigente', through='dipendenti.Ufficio_Dirigente', to='dipendenti.Dipendente'),
        ),
        migrations.CreateModel(
            name='Servizio_Ufficio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_da', models.DateField(verbose_name='Data di inizio')),
                ('data_a', models.DateField(blank=True, null=True, verbose_name='Data di fine')),
                ('servizio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipendenti.servizio')),
                ('ufficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipendenti.ufficio')),
            ],
            options={
                'ordering': ['data_da'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Servizio_Responsabile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_da', models.DateField(verbose_name='Data di inizio')),
                ('data_a', models.DateField(blank=True, null=True, verbose_name='Data di fine')),
                ('responsabile', models.ForeignKey(limit_choices_to={'ruolo__responsabile': True}, on_delete=django.db.models.deletion.CASCADE, to='dipendenti.dipendente')),
                ('servizio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipendenti.servizio')),
            ],
            options={
                'verbose_name': 'Servizio - Responsabile',
                'verbose_name_plural': 'Servizi - Responsabili',
            },
        ),
        migrations.AddField(
            model_name='servizio',
            name='responsabile',
            field=models.ManyToManyField(related_name='responsabile', through='dipendenti.Servizio_Responsabile', to='dipendenti.Dipendente'),
        ),
        migrations.AddField(
            model_name='servizio',
            name='ufficio',
            field=models.ManyToManyField(through='dipendenti.Servizio_Ufficio', to='dipendenti.Ufficio'),
        ),
        migrations.CreateModel(
            name='Qualifica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome Breve')),
                ('nome_it_m', models.CharField(max_length=40, verbose_name='Nome italiano maschile')),
                ('nome_it_f', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome italiano femminile')),
                ('nome_dt_m', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome tedesco maschile')),
                ('nome_dt_f', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome tedesco femminile')),
                ('livello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipendenti.livello', verbose_name='Livello')),
            ],
            options={
                'verbose_name': 'Qualifica',
                'verbose_name_plural': 'Qualifiche',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Dipendente_Servizio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_da', models.DateField(verbose_name='Data di inizio')),
                ('data_a', models.DateField(blank=True, null=True, verbose_name='Data di fine')),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipendenti.dipendente')),
                ('servizio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipendenti.servizio')),
            ],
            options={
                'verbose_name': 'Dipendente - Servizio',
                'verbose_name_plural': 'Dipendenti - Servizi',
            },
        ),
        migrations.CreateModel(
            name='Dipendente_Ruolo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_da', models.DateField(verbose_name='Data di inizio')),
                ('data_a', models.DateField(blank=True, null=True, verbose_name='Data di fine')),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipendenti.dipendente')),
                ('ruolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipendenti.ruolo')),
            ],
            options={
                'verbose_name': 'Dipendente - Ruolo',
                'verbose_name_plural': 'Dipendenti - Ruoli',
            },
        ),
        migrations.CreateModel(
            name='Dipendente_Qualifica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('data_da', models.DateField(verbose_name='Data di inizio')),
                ('data_a', models.DateField(blank=True, null=True, verbose_name='Data di fine')),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipendenti.dipendente')),
                ('qualifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipendenti.qualifica')),
            ],
            options={
                'verbose_name': 'Dipendente - Qualifica',
                'verbose_name_plural': 'Dipendenti - Qualifiche',
            },
        ),
        migrations.AddField(
            model_name='dipendente',
            name='qualifica',
            field=models.ManyToManyField(through='dipendenti.Dipendente_Qualifica', to='dipendenti.Qualifica'),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='ruolo',
            field=models.ManyToManyField(through='dipendenti.Dipendente_Ruolo', to='dipendenti.Ruolo'),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='servizio',
            field=models.ManyToManyField(through='dipendenti.Dipendente_Servizio', to='dipendenti.Servizio'),
        ),
    ]
