# Generated by Django 3.2 on 2022-04-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dipendente',
            name='matricola',
            field=models.CharField(default='1', max_length=6, verbose_name='Matricola'),
            preserve_default=False,
        ),
    ]
