# Generated by Django 3.2 on 2022-04-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0002_dipendente_matricola'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servizio_ufficio',
            options={'verbose_name': 'Servizio - Ufficio', 'verbose_name_plural': 'Servizi - Uffici'},
        ),
        migrations.AlterField(
            model_name='qualifica',
            name='nome',
            field=models.CharField(max_length=20, verbose_name='Nome Qualifica'),
        ),
        migrations.AlterField(
            model_name='qualifica',
            name='nome_dt_f',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome tedesco femminile'),
        ),
        migrations.AlterField(
            model_name='qualifica',
            name='nome_dt_m',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome tedesco maschile'),
        ),
        migrations.AlterField(
            model_name='qualifica',
            name='nome_it_f',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome italiano femminile'),
        ),
        migrations.AlterField(
            model_name='qualifica',
            name='nome_it_m',
            field=models.CharField(max_length=100, verbose_name='Nome italiano maschile'),
        ),
        migrations.AlterField(
            model_name='ruolo',
            name='nome',
            field=models.CharField(max_length=20, verbose_name='Nome Ruolo'),
        ),
        migrations.AlterField(
            model_name='ruolo',
            name='nome_dt_f',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome tedesco femminile'),
        ),
        migrations.AlterField(
            model_name='ruolo',
            name='nome_dt_m',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome tedesco maschile'),
        ),
        migrations.AlterField(
            model_name='ruolo',
            name='nome_it_f',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome italiano femminile'),
        ),
        migrations.AlterField(
            model_name='ruolo',
            name='nome_it_m',
            field=models.CharField(max_length=100, verbose_name='Nome italiano maschile'),
        ),
        migrations.AlterField(
            model_name='servizio',
            name='nome',
            field=models.CharField(max_length=20, verbose_name='Nome Servizio'),
        ),
        migrations.AlterField(
            model_name='servizio',
            name='nome_dt_f',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome tedesco femminile'),
        ),
        migrations.AlterField(
            model_name='servizio',
            name='nome_dt_m',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome tedesco maschile'),
        ),
        migrations.AlterField(
            model_name='servizio',
            name='nome_it_f',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome italiano femminile'),
        ),
        migrations.AlterField(
            model_name='servizio',
            name='nome_it_m',
            field=models.CharField(max_length=100, verbose_name='Nome italiano maschile'),
        ),
        migrations.AlterField(
            model_name='ufficio',
            name='nome',
            field=models.CharField(max_length=20, verbose_name='Nome Ufficio'),
        ),
        migrations.AlterField(
            model_name='ufficio',
            name='nome_dt_f',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome tedesco femminile'),
        ),
        migrations.AlterField(
            model_name='ufficio',
            name='nome_dt_m',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome tedesco maschile'),
        ),
        migrations.AlterField(
            model_name='ufficio',
            name='nome_it_f',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome italiano femminile'),
        ),
        migrations.AlterField(
            model_name='ufficio',
            name='nome_it_m',
            field=models.CharField(max_length=100, verbose_name='Nome italiano maschile'),
        ),
    ]
