# Generated by Django 4.0.4 on 2022-04-14 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0004_dipendente_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportoLavoro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('descrizione', models.CharField(max_length=30, verbose_name='Descrizione')),
                ('n_minuti', models.IntegerField(verbose_name='Totale teorico settimanale di minuti lavorati')),
                ('coefficiente', models.DecimalField(decimal_places=5, max_digits=6, verbose_name='Coefficiente rapporto di lavoro')),
            ],
            options={
                'verbose_name': 'Rapporto di lavoro',
                'verbose_name_plural': 'Rapporti di lavoro',
                'ordering': ['-coefficiente'],
            },
        ),
        migrations.AddField(
            model_name='dipendente_qualifica',
            name='determinato',
            field=models.BooleanField(default=False, verbose_name='A tempo determinato'),
        ),
        migrations.AddField(
            model_name='dipendente_qualifica',
            name='rapportolavoro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dipendenti.rapportolavoro'),
            preserve_default=False,
        ),
    ]
