# Generated by Django 4.0.4 on 2022-04-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0005_rapportolavoro_dipendente_qualifica_determinato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dipendente',
            name='codicefiscale',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Codice Fiscale'),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='sesso',
            field=models.CharField(blank=True, choices=[('M', 'Maschio'), ('F', 'Femmina'), ('*', 'Non Binario')], max_length=1, null=True, verbose_name='Sesso'),
        ),
    ]
