# Generated by Django 4.0.4 on 2022-04-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0006_dipendente_codicefiscale_dipendente_sesso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dirigente',
            fields=[
            ],
            options={
                'verbose_name': 'Dirigente o responsabile',
                'verbose_name_plural': 'Dirigenti e Responsabili',
                'ordering': ['cognome', 'nome'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dipendenti.dipendente',),
        ),
        migrations.RemoveField(
            model_name='ruolo',
            name='coordinatore',
        ),
        migrations.AlterField(
            model_name='ruolo',
            name='responsabile',
            field=models.BooleanField(default=False, verbose_name='Ruolo di responsabile o coordinatore'),
        ),
    ]
