# Generated by Django 4.0.4 on 2022-04-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0007_dirigente_remove_ruolo_coordinatore_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servizio',
            options={'ordering': ['nome'], 'verbose_name': 'Servizio o gruppo di attività omogenee', 'verbose_name_plural': 'Servizi e gruppi di attività omogenee'},
        ),
        migrations.RemoveField(
            model_name='dipendente_qualifica',
            name='data_a',
        ),
        migrations.RemoveField(
            model_name='dipendente_ruolo',
            name='data_a',
        ),
        migrations.RemoveField(
            model_name='dipendente_servizio',
            name='data_a',
        ),
        migrations.RemoveField(
            model_name='servizio_responsabile',
            name='data_a',
        ),
        migrations.RemoveField(
            model_name='servizio_ufficio',
            name='data_a',
        ),
        migrations.RemoveField(
            model_name='ufficio_dirigente',
            name='data_a',
        ),
        migrations.AlterField(
            model_name='dipendente_qualifica',
            name='data_da',
            field=models.DateField(default='2022-01-01', verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='dipendente_ruolo',
            name='data_da',
            field=models.DateField(default='2022-01-01', verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='dipendente_servizio',
            name='data_da',
            field=models.DateField(default='2022-01-01', verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='servizio_responsabile',
            name='data_da',
            field=models.DateField(default='2022-01-01', verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='servizio_ufficio',
            name='data_da',
            field=models.DateField(default='2022-01-01', verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='ufficio_dirigente',
            name='data_da',
            field=models.DateField(default='2022-01-01', verbose_name='Data di inizio'),
        ),
    ]
