# Generated by Django 4.0.4 on 2022-04-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0008_alter_servizio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dipendente_qualifica',
            name='data_a',
            field=models.DateField(blank=True, null=True, verbose_name='Data di fine'),
        ),
        migrations.AddField(
            model_name='dipendente_ruolo',
            name='data_a',
            field=models.DateField(blank=True, null=True, verbose_name='Data di fine'),
        ),
        migrations.AddField(
            model_name='dipendente_servizio',
            name='data_a',
            field=models.DateField(blank=True, null=True, verbose_name='Data di fine'),
        ),
        migrations.AddField(
            model_name='servizio_responsabile',
            name='data_a',
            field=models.DateField(blank=True, null=True, verbose_name='Data di fine'),
        ),
        migrations.AddField(
            model_name='servizio_ufficio',
            name='data_a',
            field=models.DateField(blank=True, null=True, verbose_name='Data di fine'),
        ),
        migrations.AddField(
            model_name='ufficio_dirigente',
            name='data_a',
            field=models.DateField(blank=True, null=True, verbose_name='Data di fine'),
        ),
    ]
