# Generated by Django 4.0.4 on 2022-04-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0009_dipendente_qualifica_data_a_dipendente_ruolo_data_a_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('immagine', models.ImageField(upload_to='logo/', verbose_name='File immagine')),
                ('descrizione', models.CharField(max_length=50, unique=True, verbose_name='Descrizione del logo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='dipendente_qualifica',
            options={'ordering': ['dipendente__cognome', 'dipendente__nome', 'data_da'], 'verbose_name': 'Dipendente - Qualifica', 'verbose_name_plural': 'Dipendenti - Qualifiche'},
        ),
        migrations.AlterModelOptions(
            name='qualifica',
            options={'ordering': ['livello__indice', 'nome'], 'verbose_name': 'Qualifica', 'verbose_name_plural': 'Qualifiche'},
        ),
        migrations.AlterField(
            model_name='dipendente_qualifica',
            name='data_da',
            field=models.DateField(default='01/01/2022', verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='dipendente_ruolo',
            name='data_da',
            field=models.DateField(default='01/01/2022', verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='dipendente_servizio',
            name='data_da',
            field=models.DateField(default='01/01/2022', verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='servizio_responsabile',
            name='data_da',
            field=models.DateField(default='01/01/2022', verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='servizio_ufficio',
            name='data_da',
            field=models.DateField(default='01/01/2022', verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='ufficio_dirigente',
            name='data_da',
            field=models.DateField(default='01/01/2022', verbose_name='Data di inizio'),
        ),
    ]
