# Generated by Django 4.0.4 on 2022-05-16 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0010_logo_alter_dipendente_qualifica_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name': 'Logo', 'verbose_name_plural': 'Logo'},
        ),
    ]
