# Generated by Django 4.0.4 on 2022-07-07 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0011_alter_logo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dipendente_qualifica',
            name='data_da',
            field=models.DateField(default=datetime.datetime(2022, 7, 7, 11, 1, 16, 412479), verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='dipendente_qualifica',
            name='determinato',
            field=models.BooleanField(choices=[(True, 'Sì'), (False, 'No')], default=False, verbose_name='A tempo determinato'),
        ),
        migrations.AlterField(
            model_name='dipendente_ruolo',
            name='data_da',
            field=models.DateField(default=datetime.datetime(2022, 7, 7, 11, 1, 16, 412479), verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='dipendente_servizio',
            name='data_da',
            field=models.DateField(default=datetime.datetime(2022, 7, 7, 11, 1, 16, 412479), verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='servizio_responsabile',
            name='data_da',
            field=models.DateField(default=datetime.datetime(2022, 7, 7, 11, 1, 16, 412479), verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='servizio_ufficio',
            name='data_da',
            field=models.DateField(default=datetime.datetime(2022, 7, 7, 11, 1, 16, 412479), verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='ufficio_dirigente',
            name='data_da',
            field=models.DateField(default=datetime.datetime(2022, 7, 7, 11, 1, 16, 412479), verbose_name='Data di inizio'),
        ),
    ]
