# Generated by Django 4.0.4 on 2023-06-06 13:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0033_alter_dipendente_qualifica_data_da_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dipendente_qualifica',
            name='data_a',
            field=models.DateField(blank=True, help_text='Data di fine del periodo', null=True, verbose_name='Data di fine'),
        ),
        migrations.AlterField(
            model_name='dipendente_qualifica',
            name='data_da',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 15, 22, 28, 805670), help_text='Data di inizio del periodo', verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='dipendente_qualifica',
            name='dipendente',
            field=models.ForeignKey(help_text='Dipendnete collegato', on_delete=django.db.models.deletion.CASCADE, to='dipendenti.dipendente'),
        ),
        migrations.AlterField(
            model_name='dipendente_qualifica',
            name='id',
            field=models.AutoField(help_text='Id unico - chiave primaria', primary_key=True, serialize=False, verbose_name='Codice Identificativo'),
        ),
        migrations.AlterField(
            model_name='dipendente_ruolo',
            name='data_a',
            field=models.DateField(blank=True, help_text='Data di fine del periodo', null=True, verbose_name='Data di fine'),
        ),
        migrations.AlterField(
            model_name='dipendente_ruolo',
            name='data_da',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 15, 22, 28, 805670), help_text='Data di inizio del periodo', verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='dipendente_ruolo',
            name='dipendente',
            field=models.ForeignKey(help_text='Dipendnete collegato', on_delete=django.db.models.deletion.CASCADE, to='dipendenti.dipendente'),
        ),
        migrations.AlterField(
            model_name='dipendente_ruolo',
            name='id',
            field=models.AutoField(help_text='Id unico - chiave primaria', primary_key=True, serialize=False, verbose_name='Codice Identificativo'),
        ),
        migrations.AlterField(
            model_name='dipendente_servizio',
            name='data_a',
            field=models.DateField(blank=True, help_text='Data di fine del periodo', null=True, verbose_name='Data di fine'),
        ),
        migrations.AlterField(
            model_name='dipendente_servizio',
            name='data_da',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 15, 22, 28, 805670), help_text='Data di inizio del periodo', verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='dipendente_servizio',
            name='dipendente',
            field=models.ForeignKey(help_text='Dipendnete collegato', on_delete=django.db.models.deletion.CASCADE, to='dipendenti.dipendente'),
        ),
        migrations.AlterField(
            model_name='dipendente_servizio',
            name='id',
            field=models.AutoField(help_text='Id unico - chiave primaria', primary_key=True, serialize=False, verbose_name='Codice Identificativo'),
        ),
        migrations.AlterField(
            model_name='livello',
            name='coefficiente',
            field=models.IntegerField(help_text='Valore contrattuale da applicare ala quota premio produzione, relativo al livello.', verbose_name='Coefficiente premio produzione'),
        ),
        migrations.AlterField(
            model_name='livello',
            name='id',
            field=models.AutoField(help_text='Id unico - chiave primaria', primary_key=True, serialize=False, verbose_name='Codice Identificativo'),
        ),
        migrations.AlterField(
            model_name='livello',
            name='indice',
            field=models.IntegerField(help_text='posizione del livello, per elenchi ordinali.', verbose_name='Indice'),
        ),
        migrations.AlterField(
            model_name='livello',
            name='livello',
            field=models.CharField(help_text='Nome del livello, in numeri romani.', max_length=10, verbose_name='Livello'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='descrizione',
            field=models.CharField(help_text='testo descrittivo del logo', max_length=50, unique=True, verbose_name='Descrizione del logo'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='id',
            field=models.AutoField(help_text='Id unico - chiave primaria', primary_key=True, serialize=False, verbose_name='Codice Identificativo'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='immagine',
            field=models.ImageField(help_text='file di immagine del logo', upload_to='logo/', verbose_name='File immagine'),
        ),
        migrations.AlterField(
            model_name='qualifica',
            name='id',
            field=models.AutoField(help_text='Id unico - chiave primaria', primary_key=True, serialize=False, verbose_name='Codice Identificativo'),
        ),
        migrations.AlterField(
            model_name='qualifica',
            name='livello',
            field=models.ForeignKey(help_text='FK qualifica funzionale - livello relativo, come da T.U. del 02.07.2015.', on_delete=django.db.models.deletion.CASCADE, to='dipendenti.livello', verbose_name='Livello'),
        ),
        migrations.AlterField(
            model_name='qualifica',
            name='nome',
            field=models.CharField(help_text='Nome breve della qualifica funzionale, per i riferimenti interni.', max_length=20, verbose_name='Nome Qualifica'),
        ),
        migrations.AlterField(
            model_name='qualifica',
            name='nome_dt_f',
            field=models.CharField(blank=True, help_text='Nome esteso in tedesco, per soggetti femminili..', max_length=100, null=True, verbose_name='Nome tedesco femminile'),
        ),
        migrations.AlterField(
            model_name='qualifica',
            name='nome_dt_m',
            field=models.CharField(blank=True, help_text='Nome esteso in tedesco, per soggetti maschili.', max_length=100, null=True, verbose_name='Nome tedesco maschile'),
        ),
        migrations.AlterField(
            model_name='qualifica',
            name='nome_it_f',
            field=models.CharField(blank=True, help_text='Nome esteso in italiano, per soggetti femminili.', max_length=100, null=True, verbose_name='Nome italiano femminile'),
        ),
        migrations.AlterField(
            model_name='qualifica',
            name='nome_it_m',
            field=models.CharField(help_text='Nome esteso in italiano, per soggetti maschili.', max_length=100, verbose_name='Nome italiano maschile'),
        ),
        migrations.AlterField(
            model_name='rapportolavoro',
            name='coefficiente',
            field=models.DecimalField(decimal_places=5, help_text='Coefficiente REALE di rapporto tra minuti settimanali contrattuali e minuti teorici (2280).', max_digits=6, verbose_name='Coefficiente rapporto di lavoro'),
        ),
        migrations.AlterField(
            model_name='rapportolavoro',
            name='descrizione',
            field=models.CharField(help_text='Testo descrittivo ad uso interno per il rapporto di lavoro.', max_length=30, verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='rapportolavoro',
            name='id',
            field=models.AutoField(help_text='Id unico - chiave primaria', primary_key=True, serialize=False, verbose_name='Codice Identificativo'),
        ),
        migrations.AlterField(
            model_name='rapportolavoro',
            name='n_minuti',
            field=models.IntegerField(help_text='Si calcola sulla base di 2280 minuti, che sono equivalenti a 38 ore settimanali (full time).', verbose_name='Totale teorico contrattuale settimanale di minuti lavorati'),
        ),
        migrations.AlterField(
            model_name='ruolo',
            name='ammsistema',
            field=models.BooleanField(default=False, help_text='Indica che il ruolo ha pieno accesso alla banca dati, in qualità di amministratore di sistema.', verbose_name='Ruolo amministratore di sistema'),
        ),
        migrations.AlterField(
            model_name='ruolo',
            name='dirigente',
            field=models.BooleanField(default=False, help_text="Indica che il ruolo ricopre la carica direttiva e dirigenziale, a capo di un ufficio. L'utente compare nei dropdown relativi.", verbose_name='Ruolo dirigenziale'),
        ),
        migrations.AlterField(
            model_name='ruolo',
            name='id',
            field=models.AutoField(help_text='Id unico - chiave primaria', primary_key=True, serialize=False, verbose_name='Codice Identificativo'),
        ),
        migrations.AlterField(
            model_name='ruolo',
            name='nome',
            field=models.CharField(help_text='Nome del ruolo per i riferimenti interni al programma', max_length=20, verbose_name='Nome Ruolo'),
        ),
        migrations.AlterField(
            model_name='ruolo',
            name='nome_dt_f',
            field=models.CharField(blank=True, help_text='Nome esteso in tedesco, per soggetti femminili..', max_length=100, null=True, verbose_name='Nome tedesco femminile'),
        ),
        migrations.AlterField(
            model_name='ruolo',
            name='nome_dt_m',
            field=models.CharField(blank=True, help_text='Nome esteso in tedesco, per soggetti maschili.', max_length=100, null=True, verbose_name='Nome tedesco maschile'),
        ),
        migrations.AlterField(
            model_name='ruolo',
            name='nome_it_f',
            field=models.CharField(blank=True, help_text='Nome esteso in italiano, per soggetti femminili.', max_length=100, null=True, verbose_name='Nome italiano femminile'),
        ),
        migrations.AlterField(
            model_name='ruolo',
            name='nome_it_m',
            field=models.CharField(help_text='Nome esteso in italiano, per soggetti maschili.', max_length=100, verbose_name='Nome italiano maschile'),
        ),
        migrations.AlterField(
            model_name='ruolo',
            name='responsabile',
            field=models.BooleanField(default=False, help_text="Indica che il ruolo ricopre la carica di responsabile di servizio o coordinatore di unità organizzativa. L'utente compare nei dropdown relativi.", verbose_name='Ruolo di responsabile o coordinatore'),
        ),
        migrations.AlterField(
            model_name='ruolo',
            name='segretario',
            field=models.BooleanField(default=False, help_text='Indica che il ruolo ricopre la carica di segretario o vice-segretario generale.', verbose_name='Ruolo segretario generale'),
        ),
        migrations.AlterField(
            model_name='ruolo',
            name='sindaco',
            field=models.BooleanField(default=False, help_text='Il ruolo che compete al sindaco o vice-sindaco.', verbose_name='Ruolo da sindaco'),
        ),
        migrations.AlterField(
            model_name='servizio',
            name='id',
            field=models.AutoField(help_text='Id unico - chiave primaria', primary_key=True, serialize=False, verbose_name='Codice Identificativo'),
        ),
        migrations.AlterField(
            model_name='servizio',
            name='nome_dt_f',
            field=models.CharField(blank=True, help_text='Nome esteso in tedesco, per soggetti femminili..', max_length=100, null=True, verbose_name='Nome tedesco femminile'),
        ),
        migrations.AlterField(
            model_name='servizio',
            name='nome_dt_m',
            field=models.CharField(blank=True, help_text='Nome esteso in tedesco, per soggetti maschili.', max_length=100, null=True, verbose_name='Nome tedesco maschile'),
        ),
        migrations.AlterField(
            model_name='servizio',
            name='nome_it_f',
            field=models.CharField(blank=True, help_text='Nome esteso in italiano, per soggetti femminili.', max_length=100, null=True, verbose_name='Nome italiano femminile'),
        ),
        migrations.AlterField(
            model_name='servizio',
            name='nome_it_m',
            field=models.CharField(help_text='Nome esteso in italiano, per soggetti maschili.', max_length=100, verbose_name='Nome italiano maschile'),
        ),
        migrations.AlterField(
            model_name='servizio_responsabile',
            name='data_a',
            field=models.DateField(blank=True, help_text='Data di fine del periodo', null=True, verbose_name='Data di fine'),
        ),
        migrations.AlterField(
            model_name='servizio_responsabile',
            name='data_da',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 15, 22, 28, 805670), help_text='Data di inizio del periodo', verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='servizio_responsabile',
            name='id',
            field=models.AutoField(help_text='Id unico - chiave primaria', primary_key=True, serialize=False, verbose_name='Codice Identificativo'),
        ),
        migrations.AlterField(
            model_name='servizio_ufficio',
            name='data_a',
            field=models.DateField(blank=True, help_text='Data di fine del periodo', null=True, verbose_name='Data di fine'),
        ),
        migrations.AlterField(
            model_name='servizio_ufficio',
            name='data_da',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 15, 22, 28, 805670), help_text='Data di inizio del periodo', verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='servizio_ufficio',
            name='id',
            field=models.AutoField(help_text='Id unico - chiave primaria', primary_key=True, serialize=False, verbose_name='Codice Identificativo'),
        ),
        migrations.AlterField(
            model_name='ufficio',
            name='dirigente',
            field=models.ManyToManyField(help_text="Many to Many di associazione tra ufficio e relativo dirigente. La DDL relativa si compila con i dipendenti i cui ruoli hanno il diritto 'responsabile'", related_name='dirigente', through='dipendenti.Ufficio_Dirigente', to='dipendenti.dipendente'),
        ),
        migrations.AlterField(
            model_name='ufficio',
            name='id',
            field=models.AutoField(help_text='Id unico - chiave primaria', primary_key=True, serialize=False, verbose_name='Codice Identificativo'),
        ),
        migrations.AlterField(
            model_name='ufficio',
            name='nome',
            field=models.CharField(help_text="Testo descrittivo ad uso interno dell'ufficio.", max_length=20, verbose_name='Nome Ufficio'),
        ),
        migrations.AlterField(
            model_name='ufficio',
            name='nome_dt_f',
            field=models.CharField(blank=True, help_text='Nome esteso in tedesco, per soggetti femminili..', max_length=100, null=True, verbose_name='Nome tedesco femminile'),
        ),
        migrations.AlterField(
            model_name='ufficio',
            name='nome_dt_m',
            field=models.CharField(blank=True, help_text='Nome esteso in tedesco, per soggetti maschili.', max_length=100, null=True, verbose_name='Nome tedesco maschile'),
        ),
        migrations.AlterField(
            model_name='ufficio',
            name='nome_it_f',
            field=models.CharField(blank=True, help_text='Nome esteso in italiano, per soggetti femminili.', max_length=100, null=True, verbose_name='Nome italiano femminile'),
        ),
        migrations.AlterField(
            model_name='ufficio',
            name='nome_it_m',
            field=models.CharField(help_text='Nome esteso in italiano, per soggetti maschili.', max_length=100, verbose_name='Nome italiano maschile'),
        ),
        migrations.AlterField(
            model_name='ufficio_dirigente',
            name='data_a',
            field=models.DateField(blank=True, help_text='Data di fine del periodo', null=True, verbose_name='Data di fine'),
        ),
        migrations.AlterField(
            model_name='ufficio_dirigente',
            name='data_da',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 15, 22, 28, 805670), help_text='Data di inizio del periodo', verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='ufficio_dirigente',
            name='id',
            field=models.AutoField(help_text='Id unico - chiave primaria', primary_key=True, serialize=False, verbose_name='Codice Identificativo'),
        ),
    ]
