# Generated by Django 4.0.4 on 2023-06-06 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0035_alter_dipendente_qualifica_data_da_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dipendente_qualifica',
            name='data_da',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 16, 6, 43, 276418), help_text='Data di inizio del periodo', verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='dipendente_ruolo',
            name='data_da',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 16, 6, 43, 276418), help_text='Data di inizio del periodo', verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='dipendente_servizio',
            name='data_da',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 16, 6, 43, 276418), help_text='Data di inizio del periodo', verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='servizio_responsabile',
            name='data_da',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 16, 6, 43, 276418), help_text='Data di inizio del periodo', verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='servizio_ufficio',
            name='data_da',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 16, 6, 43, 276418), help_text='Data di inizio del periodo', verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='ufficio_dirigente',
            name='data_da',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 16, 6, 43, 276418), help_text='Data di inizio del periodo', verbose_name='Data di inizio'),
        ),
    ]
