# Generated by Django 4.0.4 on 2023-06-12 06:11

import datetime
from django.db import migrations, models
from django.utils import timezone 
import zoneinfo 
utc = zoneinfo.ZoneInfo("Europe/Rome")


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0039_alter_dipendente_qualifica_data_da_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dipendente_qualifica',
            name='data_da',
            field=models.DateField(default=datetime.datetime(2023, 6, 12, 6, 11, 38, 206782, tzinfo=utc), help_text='Data di inizio del periodo', verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='dipendente_ruolo',
            name='data_da',
            field=models.DateField(default=datetime.datetime(2023, 6, 12, 6, 11, 38, 206782, tzinfo=utc), help_text='Data di inizio del periodo', verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='dipendente_servizio',
            name='data_da',
            field=models.DateField(default=datetime.datetime(2023, 6, 12, 6, 11, 38, 206782, tzinfo=utc), help_text='Data di inizio del periodo', verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='servizio_responsabile',
            name='data_da',
            field=models.DateField(default=datetime.datetime(2023, 6, 12, 6, 11, 38, 206782, tzinfo=utc), help_text='Data di inizio del periodo', verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='servizio_ufficio',
            name='data_da',
            field=models.DateField(default=datetime.datetime(2023, 6, 12, 6, 11, 38, 206782, tzinfo=utc), help_text='Data di inizio del periodo', verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='ufficio_dirigente',
            name='data_da',
            field=models.DateField(default=datetime.datetime(2023, 6, 12, 6, 11, 38, 206782, tzinfo=utc), help_text='Data di inizio del periodo', verbose_name='Data di inizio'),
        ),
    ]
