# Generated by Django 4.0.4 on 2023-06-12 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0040_alter_dipendente_qualifica_data_da_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dipendente_qualifica',
            name='data_da',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data di inizio del periodo', verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='dipendente_ruolo',
            name='data_da',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data di inizio del periodo', verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='dipendente_servizio',
            name='data_da',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data di inizio del periodo', verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='servizio_responsabile',
            name='data_da',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data di inizio del periodo', verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='servizio_ufficio',
            name='data_da',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data di inizio del periodo', verbose_name='Data di inizio'),
        ),
        migrations.AlterField(
            model_name='ufficio_dirigente',
            name='data_da',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data di inizio del periodo', verbose_name='Data di inizio'),
        ),
    ]
