# Generated by Django 4.0.4 on 2023-07-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0041_alter_dipendente_qualifica_data_da_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dipendente',
            name='badge_p',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Numero Badge apertura porte'),
        ),
    ]
