# Generated by Django 5.0.1 on 2024-01-19 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0042_dipendente_badge_p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dipendente',
            name='user',
        ),
    ]
