# Generated by Django 5.0.1 on 2024-03-19 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0043_remove_dipendente_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dipendente',
            name='dirigente_alt',
            field=models.ForeignKey(blank=True, help_text='Lasciare in bianco per scegliere in automatico il dirigente corretto.', null=True, on_delete=django.db.models.deletion.PROTECT, to='dipendenti.dirigente', verbose_name="Dirigente sostitutivo nell'ambito di trattamento"),
        ),
    ]
