# Generated by Django 5.0.1 on 2024-03-19 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0044_dipendente_dirigente_alt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dipendente',
            name='dirigente_alt',
        ),
    ]
