# Generated by Django 5.0.1 on 2024-12-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0045_remove_dipendente_dirigente_alt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(help_text='Id unico - chiave primaria', primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(default='Testo di prova.', max_length=30, verbose_name='Nome della e-mail')),
                ('mittente', models.EmailField(default='mail@comune.laives.bz.it', max_length=254, verbose_name='Mittente')),
                ('oggetto', models.CharField(default='Comunicazione', max_length=60, verbose_name='Oggetto')),
                ('testo', models.TextField(help_text='Testo Aiuto', verbose_name='Testo della E-mail')),
            ],
            options={
                'verbose_name': 'Testo E-mail',
                'verbose_name_plural': 'Testi E-mail',
            },
        ),
        migrations.AddField(
            model_name='dipendente',
            name='citta',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='CAP e città di residenza'),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='data_nascita',
            field=models.DateField(blank=True, null=True, verbose_name='Data di nascita'),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='indirizzo',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Via e numero civico'),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='patentino',
            field=models.CharField(blank=True, choices=[('A2', 'Patentino A2'), ('B1', 'Patentino B1'), ('B2', 'Patentino B2'), ('C1', 'Patentino C1')], max_length=2, null=True, verbose_name='Patentino di bilinguismo'),
        ),
    ]
