# Generated by Django 5.0.1 on 2024-12-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0046_mail_dipendente_citta_dipendente_data_nascita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dipendente',
            name='luogo_nascita',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Luogo di nascita'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='testo',
            field=models.TextField(help_text='{nome}: nome del dipendente \n{cognome}: cognome del dipendente \n{indirizzo}: indirizzo del dipendente \n{citta}: cap e dittà del dipendente \n{cf}: codice fiscale del dipendente \n{patentino}: patentino del dipendente \n{datanascita}: data di nascita del dipendente \n{luogonascita}: luogo di nascita del dipendente \n{matricola}: matricole del dipendente \n{datainizio}: data di inquadramento del dipendente \n{profilo}: profilo professionale del dipendente \n{rapporto}: raporto di lavoro del dipendente \n{tpd}: tempo determinato - indeterminato \n{userid}: nome utente del dipendente \n{email}: e-mail del dipendente \n{tel}: numero di telefono del dipedente \n{serv}: servizio a cui È associato il dipendente \n{uff}: ufficio a cui è assegnato il dipendente ', verbose_name='Testo della E-mail'),
        ),
    ]
