# Generated by Django 5.0.1 on 2024-12-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0047_dipendente_luogo_nascita_alter_mail_testo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='cc',
            field=models.CharField(blank=True, help_text='Separare i destinatari con un punto e virgola (;).', max_length=512, null=True, verbose_name='Destinatari in copia conoscenza'),
        ),
        migrations.AddField(
            model_name='mail',
            name='to',
            field=models.CharField(default='edp@comune.laives.bz.it', help_text='Separare i destinatari con un punto e virgola (;).', max_length=512, verbose_name='Elenco destinatari'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mail',
            name='testo',
            field=models.TextField(help_text='{nome}: nome del dipendente \n{cognome}: cognome del dipendente \n{indirizzo}: indirizzo del dipendente \n{citta}: cap e dittà del dipendente \n{cf}: codice fiscale del dipendente \n{patentino}: patentino del dipendente \n{datanascita}: data di nascita del dipendente \n{luogonascita}: luogo di nascita del dipendente \n{matricola}: matricole del dipendente \n{datainizio}: data di inquadramento del dipendente \n{profilo}: profilo professionale del dipendente \n{rapporto}: raporto di lavoro del dipendente \n{tpd}: tempo determinato - indeterminato \n{userid}: nome utente del dipendente \n{email}: e-mail del dipendente \n{tel}: numero di telefono del dipedente \n{serv}: servizio a cui è associato il dipendente \n{uff}: ufficio a cui è assegnato il dipendente ', verbose_name='Testo della E-mail'),
        ),
    ]
