# Generated by Django 5.0.1 on 2024-12-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0048_mail_cc_mail_to_alter_mail_testo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='to',
            field=models.CharField(default='mail@comune.laives.bz.it', help_text='Separare i destinatari con un punto e virgola (;).', max_length=512, verbose_name='Elenco destinatari'),
        ),
    ]
