# Generated by Django 5.0.1 on 2024-12-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0051_alter_mail_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='cc',
            field=models.CharField(blank=True, help_text='Separare i destinatari con un punto e virgola (;). <br /> Non terminare la linea con un punto e virgola.', max_length=512, null=True, verbose_name='Destinatari in copia conoscenza'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='nome',
            field=models.CharField(default='Testo di prova.', max_length=30, unique=True, verbose_name='Nome della e-mail'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='testo',
            field=models.TextField(help_text='{nome}: nome del dipendente <br />\n{cognome}: cognome del dipendente<br />\n{indirizzo}: indirizzo del dipendente<br />\n{citta}: cap e dittà del dipendente<br />\n{cf}: codice fiscale del dipendente<br />\n{patentino}: patentino del dipendente<br />\n{datanascita}: data di nascita del dipendente<br />\n{luogonascita}: luogo di nascita del dipendente<br />\n{matricola}: matricole del dipendente<br />\n{datainizio}: data di inquadramento del dipendente<br />\n{profilo}: profilo professionale del dipendente<br />\n{rapporto}: raporto di lavoro del dipendente<br />\n{tpd}: tempo determinato - indeterminato<br />\n{userid}: nome utente del dipendente<br />\n{email}: e-mail del dipendente<br />\n{tel}: numero di telefono del dipedente<br />\n{cel}: numero di cellulare del dipedente<br />\n{serv}: servizio a cui è associato il dipendente<br />\n{uff}: ufficio a cui è assegnato il dipendente', verbose_name='Testo della E-mail'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='to',
            field=models.CharField(default='mail@comune.laives.bz.it', help_text='Separare i destinatari con un punto e virgola (;). <br /> Non terminare la linea con un punto e virgola.', max_length=512, verbose_name='Elenco destinatari'),
        ),
    ]
