# Generated by Django 5.0.1 on 2024-12-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0052_alter_mail_cc_alter_mail_nome_alter_mail_testo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dipendente',
            name='det_cessazione',
            field=models.FileField(blank=True, null=True, upload_to='atti_dip/%Y/', verbose_name='Determina o delibera di cessazione'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='testo',
            field=models.TextField(help_text='{nome}: nome del dipendente <br />\n{cognome}: cognome del dipendente<br />\n{indirizzo}: indirizzo del dipendente<br />\n{citta}: cap e dittà del dipendente<br />\n{cf}: codice fiscale del dipendente<br />\n{patentino}: patentino del dipendente<br />\n{datanascita}: data di nascita del dipendente<br />\n{luogonascita}: luogo di nascita del dipendente<br />\n{matricola}: matricole del dipendente<br />\n{datainizio}: data di inquadramento del dipendente<br />\n{datafine}: data di cessazione del dipendente<br />\n{profilo}: profilo professionale del dipendente<br />\n{rapporto}: raporto di lavoro del dipendente<br />\n{tpd}: tempo determinato - indeterminato<br />\n{userid}: nome utente del dipendente<br />\n{email}: e-mail del dipendente<br />\n{tel}: numero di telefono del dipedente<br />\n{cel}: numero di cellulare del dipedente<br />\n{serv}: servizio a cui è associato il dipendente<br />\n{uff}: ufficio a cui è assegnato il dipendente', verbose_name='Testo della E-mail'),
        ),
    ]
