# Generated by Django 5.0.1 on 2024-12-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0053_dipendente_det_cessazione_alter_mail_testo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='del_cessazione',
            field=models.BooleanField(default=False, verbose_name='Inviare atto di cessazione?'),
        ),
    ]
