# Generated by Django 5.0.1 on 2024-12-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0054_mail_del_cessazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='servizio',
            name='formula_responsabile_dt',
            field=models.CharField(default='Verantwortlicher des Dienstes', max_length=100, verbose_name='Denominazione del responsabile in tedesco'),
        ),
        migrations.AddField(
            model_name='servizio',
            name='formula_responsabile_it',
            field=models.CharField(default='Responsabile del servizio', max_length=100, verbose_name='Denominazione del responsabile in italiano'),
        ),
        migrations.AddField(
            model_name='ufficio',
            name='formula_responsabile_dt',
            field=models.CharField(default='Amtsleiter', max_length=100, verbose_name='Denominazione del dirigente in tedesco'),
        ),
        migrations.AddField(
            model_name='ufficio',
            name='formula_responsabile_it',
            field=models.CharField(default="Dirigente dell'Ufficio", max_length=100, verbose_name='Denominazione del dirigente in italiano'),
        ),
    ]
