# Generated by Django 5.0.1 on 2024-12-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0055_servizio_formula_responsabile_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ufficio',
            name='formula_responsabile_dt',
            field=models.CharField(default='Leiter des Amtes', max_length=100, verbose_name='Denominazione del dirigente in tedesco'),
        ),
        migrations.AlterField(
            model_name='ufficio',
            name='formula_responsabile_it',
            field=models.CharField(default="Direttore dell'Ufficio", max_length=100, verbose_name='Denominazione del dirigente in italiano'),
        ),
    ]
