# Generated by Django 5.0.1 on 2024-12-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0056_alter_ufficio_formula_responsabile_dt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servizio',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='servizio',
            name='telefono',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail'),
        ),
    ]
