# Generated by Django 5.0.1 on 2024-12-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0058_alter_servizio_formula_responsabile_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servizio',
            name='formula_responsabile_dt',
            field=models.CharField(default='Verantwortlicher des Dienstes', max_length=100, verbose_name='Denominazione del responsabile in tedesco'),
        ),
    ]
