# Generated by Django 5.0.1 on 2024-12-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0059_alter_servizio_formula_responsabile_dt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dirigente',
            options={'ordering': ['cognome', 'nome'], 'verbose_name': 'Dirigente / responsabile', 'verbose_name_plural': 'Dirigenti e Responsabili'},
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='det_cessazione',
            field=models.FileField(blank=True, null=True, upload_to='atti_dip/%Y/', verbose_name='Determina / delibera di cessazione'),
        ),
    ]
