# Generated by Django 5.0.1 on 2024-12-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0060_alter_dirigente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dipendente',
            name='titprinc_dt',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Titolo principale in tedesco'),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='titprinc_it',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Titolo principale in italiano'),
        ),
    ]
