# Generated by Django 5.0.1 on 2024-12-09 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0061_dipendente_titprinc_dt_dipendente_titprinc_it'),
    ]

    operations = [
        migrations.CreateModel(
            name='Immagine',
            fields=[
                ('id', models.AutoField(help_text='Id unico - chiave primaria', primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=30, unique=True, verbose_name="Nome dell'imagine")),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione alternativa')),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='immagini/', verbose_name='Immagine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.AutoField(help_text='Id unico - chiave primaria', primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=30, unique=True, verbose_name='Nome della pagina')),
                ('testo', models.TextField(default='Testo', verbose_name='Testo della pagina')),
            ],
            options={
                'verbose_name': 'Pagina',
                'verbose_name_plural': 'Pagine',
            },
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='titprinc_dt',
            field=models.CharField(blank=True, help_text='Se valorizzato, sovrascrive qualunque altro titolo previsto.', max_length=140, null=True, verbose_name='Titolo principale in tedesco'),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='titprinc_it',
            field=models.CharField(blank=True, help_text='Se valorizzato, sovrascrive qualunque altro titolo previsto.', max_length=140, null=True, verbose_name='Titolo principale in italiano'),
        ),
        migrations.CreateModel(
            name='Capoverso',
            fields=[
                ('id', models.AutoField(help_text='Id unico - chiave primaria', primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('ordine', models.IntegerField(default=1, verbose_name='Ordine del capoverso')),
                ('testo', models.TextField(verbose_name='Testo del capoverso')),
                ('immagine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dipendenti.immagine', verbose_name='Immagine del capoverso')),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dipendenti.pagina', verbose_name='Pagina relativa')),
            ],
            options={
                'verbose_name': 'Capoverso',
                'verbose_name_plural': 'Capoversi',
            },
        ),
    ]
