# Generated by Django 5.0.1 on 2024-12-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0062_immagine_pagina_alter_dipendente_titprinc_dt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immagine',
            name='immagine',
        ),
        migrations.AddField(
            model_name='pagina',
            name='titolo',
            field=models.CharField(default='Titolo', max_length=50, verbose_name='Titolo della pagina'),
        ),
    ]
