# Generated by Django 5.0.1 on 2024-12-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0063_remove_immagine_immagine_pagina_titolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='immagine',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='immagini/', verbose_name='Immagine'),
        ),
    ]
