# Generated by Django 5.0.1 on 2024-12-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0064_immagine_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='immagine',
            name='risoluzione',
            field=models.CharField(default='320x200', max_length=15, verbose_name="Risoluzione dell'immagine"),
        ),
    ]
