# Generated by Django 5.0.1 on 2024-12-10 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0065_immagine_risoluzione'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capoverso',
            options={'ordering': ['ordine'], 'verbose_name': 'Capoverso', 'verbose_name_plural': 'Capoversi'},
        ),
        migrations.AlterField(
            model_name='capoverso',
            name='immagine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dipendenti.immagine', verbose_name='Immagine del capoverso'),
        ),
    ]
