# Generated by Django 5.0.1 on 2024-12-10 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0066_alter_capoverso_options_alter_capoverso_immagine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voce',
            fields=[
                ('id', models.AutoField(help_text='Id unico - chiave primaria', primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=30, unique=True, verbose_name='Nome della voce')),
                ('titolo', models.CharField(default='Titolo', max_length=50, verbose_name='Titolo della voce')),
                ('testo', models.TextField(default='Testo', verbose_name='Testo della voce')),
            ],
            options={
                'verbose_name': 'Pagina',
                'verbose_name_plural': 'Pagine',
            },
        ),
        migrations.RemoveField(
            model_name='capoverso',
            name='pagina',
        ),
        migrations.AddField(
            model_name='capoverso',
            name='voce',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dipendenti.voce', verbose_name='Voce relativa'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Pagina',
        ),
    ]
