# Generated by Django 5.0.1 on 2024-12-10 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0067_voce_remove_capoverso_pagina_capoverso_voce_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.AutoField(help_text='Id unico - chiave primaria', primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=30, unique=True, verbose_name='Nome della pagina')),
                ('titolo', models.CharField(default='Titolo', max_length=50, verbose_name='Titolo della pagina')),
                ('testo', models.TextField(default='Testo', verbose_name='Testo della pagina')),
            ],
            options={
                'verbose_name': 'Pagina',
                'verbose_name_plural': 'Pagine',
            },
        ),
        migrations.AlterModelOptions(
            name='voce',
            options={'verbose_name': 'Voce', 'verbose_name_plural': 'Voci'},
        ),
        migrations.CreateModel(
            name='Sezione',
            fields=[
                ('id', models.AutoField(help_text='Id unico - chiave primaria', primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=30, unique=True, verbose_name='Nome della sezione')),
                ('titolo', models.CharField(default='Titolo', max_length=50, verbose_name='Titolo della sezione')),
                ('testo', models.TextField(default='Testo', verbose_name='Testo della sezione')),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dipendenti.pagina', verbose_name='Pagina relativa')),
            ],
            options={
                'verbose_name': 'Sezione',
                'verbose_name_plural': 'Sezioni',
            },
        ),
        migrations.AddField(
            model_name='voce',
            name='sezione',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dipendenti.sezione', verbose_name='Sezione relativa'),
            preserve_default=False,
        ),
    ]
