# Generated by Django 5.0.1 on 2024-12-10 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0068_pagina_alter_voce_options_sezione_voce_sezione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sezione',
            name='pagina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dipendenti.pagina', verbose_name='Pagina relativa'),
        ),
        migrations.AlterField(
            model_name='voce',
            name='sezione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dipendenti.sezione', verbose_name='Sezione relativa'),
        ),
    ]
