# Generated by Django 5.0.1 on 2024-12-10 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0069_alter_sezione_pagina_alter_voce_sezione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capoverso',
            name='immagine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dipendenti.immagine', verbose_name='Immagine'),
        ),
        migrations.AlterField(
            model_name='capoverso',
            name='testo',
            field=models.TextField(default='Testo', verbose_name='Testo'),
        ),
        migrations.AlterField(
            model_name='immagine',
            name='nome',
            field=models.CharField(max_length=30, unique=True, verbose_name="Nome dell'immagine"),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='nome',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='testo',
            field=models.TextField(default='Testo', verbose_name='Testo'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='titolo',
            field=models.CharField(default='Titolo', max_length=50, verbose_name='Titolo'),
        ),
        migrations.AlterField(
            model_name='sezione',
            name='nome',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='sezione',
            name='testo',
            field=models.TextField(default='Testo', verbose_name='Testo'),
        ),
        migrations.AlterField(
            model_name='sezione',
            name='titolo',
            field=models.CharField(default='Titolo', max_length=50, verbose_name='Titolo'),
        ),
        migrations.AlterField(
            model_name='voce',
            name='nome',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='voce',
            name='testo',
            field=models.TextField(default='Testo', verbose_name='Testo'),
        ),
        migrations.AlterField(
            model_name='voce',
            name='titolo',
            field=models.CharField(default='Titolo', max_length=50, verbose_name='Titolo'),
        ),
        migrations.CreateModel(
            name='Allegato',
            fields=[
                ('id', models.AutoField(help_text='Id unico - chiave primaria', primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=30, unique=True, verbose_name="Nome dell'allegato")),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione alternativa')),
                ('file', models.FileField(blank=True, null=True, upload_to='allegati/%Y/', verbose_name='File')),
                ('posizione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dipendenti.capoverso', verbose_name='Posizione')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
