# Generated by Django 5.0.1 on 2024-12-10 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0070_alter_capoverso_immagine_alter_capoverso_testo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allegato',
            name='posizione',
        ),
        migrations.AddField(
            model_name='capoverso',
            name='allegato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dipendenti.allegato', verbose_name='Allegato'),
        ),
    ]
