# Generated by Django 5.0.1 on 2024-12-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0071_remove_allegato_posizione_capoverso_allegato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allegato',
            options={'verbose_name': 'Wiki - Allegato', 'verbose_name_plural': 'Wiki - Allegati'},
        ),
        migrations.AlterModelOptions(
            name='capoverso',
            options={'ordering': ['ordine'], 'verbose_name': 'Wiki - Capoverso', 'verbose_name_plural': 'Wiki - Capoversi'},
        ),
        migrations.AlterModelOptions(
            name='immagine',
            options={'verbose_name': 'Wiki - Immagine', 'verbose_name_plural': 'Wiki - Immagini'},
        ),
        migrations.AlterModelOptions(
            name='pagina',
            options={'verbose_name': 'Wiki - Pagina', 'verbose_name_plural': 'Wiki - Pagine'},
        ),
        migrations.AlterModelOptions(
            name='sezione',
            options={'verbose_name': 'Wiki - Sezione', 'verbose_name_plural': 'Wiki - Sezioni'},
        ),
        migrations.AlterModelOptions(
            name='voce',
            options={'verbose_name': 'Wiki - Voce', 'verbose_name_plural': 'Wiki - Voci'},
        ),
        migrations.AddField(
            model_name='pagina',
            name='ordine',
            field=models.IntegerField(default=1, verbose_name='Ordine'),
        ),
        migrations.AddField(
            model_name='sezione',
            name='ordine',
            field=models.IntegerField(default=1, verbose_name='Ordine'),
        ),
        migrations.AddField(
            model_name='voce',
            name='ordine',
            field=models.IntegerField(default=1, verbose_name='Ordine'),
        ),
    ]
