# Generated by Django 5.0.1 on 2024-12-10 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0072_alter_allegato_options_alter_capoverso_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagina',
            options={'ordering': ['ordine'], 'verbose_name': 'Wiki - Pagina', 'verbose_name_plural': 'Wiki - Pagine'},
        ),
        migrations.AlterModelOptions(
            name='sezione',
            options={'ordering': ['ordine'], 'verbose_name': 'Wiki - Sezione', 'verbose_name_plural': 'Wiki - Sezioni'},
        ),
        migrations.AlterModelOptions(
            name='voce',
            options={'ordering': ['ordine'], 'verbose_name': 'Wiki - Voce', 'verbose_name_plural': 'Wiki - Voci'},
        ),
    ]
