# Generated by Django 5.0.1 on 2024-12-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0073_alter_pagina_options_alter_sezione_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allegato',
            name='descrizione',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione link'),
        ),
    ]
