# Generated by Django 5.0.1 on 2024-12-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0074_alter_allegato_descrizione'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='pubblicato',
            field=models.BooleanField(default=False, verbose_name='In pubblicazione'),
        ),
        migrations.AddField(
            model_name='sezione',
            name='pubblicato',
            field=models.BooleanField(default=False, verbose_name='In pubblicazione'),
        ),
        migrations.AddField(
            model_name='voce',
            name='pubblicato',
            field=models.BooleanField(default=False, verbose_name='In pubblicazione'),
        ),
    ]
