# Generated by Django 5.0.1 on 2025-01-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0075_pagina_pubblicato_sezione_pubblicato_voce_pubblicato'),
    ]

    operations = [
        migrations.AddField(
            model_name='servizio',
            name='cdc',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Centro di Costo'),
        ),
    ]
