# Generated by Django 5.0.1 on 2025-03-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0077_historicaldipendente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dipendente',
            name='matricola',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Matricola'),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='userid',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Nome Utente'),
        ),
        migrations.AlterField(
            model_name='historicaldipendente',
            name='matricola',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Matricola'),
        ),
        migrations.AlterField(
            model_name='historicaldipendente',
            name='userid',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Nome Utente'),
        ),
    ]
