# Generated by Django 5.0.1 on 2025-03-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipendenti', '0078_alter_dipendente_matricola_alter_dipendente_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dipendente',
            name='sesso',
            field=models.CharField(blank=True, choices=[('M', 'Maschio'), ('F', 'Femmina'), ('*', 'Non Espresso')], max_length=1, null=True, verbose_name='Sesso'),
        ),
        migrations.AlterField(
            model_name='historicaldipendente',
            name='sesso',
            field=models.CharField(blank=True, choices=[('M', 'Maschio'), ('F', 'Femmina'), ('*', 'Non Espresso')], max_length=1, null=True, verbose_name='Sesso'),
        ),
    ]
